### ISSUE TITLE
[stable/postgresql] Metrics Sidecar Container not Starting

### ISSUE THREAD

**Issue by dominik-bln** [helm/charts#10136]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Helm and Kubernetes**:

Helm v2.11.0
Kubernetes v1.12.3

**Which chart**:

stable/postgresql v3.2.0

**What happened**:

Metrics Sidecar is CrashLooping and always runs into timeout when trying to establish database connection.

**What you expected to happen**:

Metrics Sidecar starts normally

**How to reproduce it** (as minimally and precisely as possible):

```bash
helm install --name=testdb stable/postgresql --set metrics.enabled=true,postgresqlPassword=testdb,postgresqlDatabase=testdb,livenessProbe.initialDelaySeconds=300
```

Increasing the `livenessProbe.initialDelaySeconds` is helpful to debug the problem because otherwise the container is restarted before the 2 minute timeout occurs.

**Anything else we need to know**:

Log output of the crashing container:

```text
$ k logs --previous  testdb-postgresql-0 metrics
time="2018-12-19T13:26:40Z" level=info msg="Established new database connection." source="postgres_exporter.go:995"
time="2018-12-19T13:28:50Z" level=info msg="Error while closing non-pinging DB connection: <nil>" source="postgres_exporter.go:1001"
time="2018-12-19T13:28:50Z" level=info msg="Error opening connection to database (postgresql://postgres:PASSWORD_REMOVED@localhost:5432/testdb?sslmode=disable): dial tcp 10.130.128.171:5432: connect: connection timed out" source="postgres_exporter.go:1030"
time="2018-12-19T13:28:50Z" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1137"
time="2018-12-19T13:29:05Z" level=info msg="Established new database connection." source="postgres_exporter.go:995"
time="2018-12-19T13:31:13Z" level=info msg="Error while closing non-pinging DB connection: <nil>" source="postgres_exporter.go:1001"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4d6b27]

goroutine 83 [running]:
database/sql.(*DB).Close(0x0, 0x927b00, 0xc420128230)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/database/sql/sql.go:720 +0x37
main.(*Exporter).getDB(0xc4202a4100, 0xc420037770, 0x42, 0xbefeafcfc8cda970, 0x289d2855f5, 0xb930c0)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:1000 +0x18a
main.(*Exporter).scrape(0xc4202a4100, 0xc4202fa8a0)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:1018 +0xde
main.(*Exporter).Collect(0xc4202a4100, 0xc4202fa8a0)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:767 +0x3c
github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc4202e3940, 0xc4202fa8a0, 0x92a4e0, 0xc4202a4100)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:383 +0x61
created by github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:381 +0x302
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4d6b27]

goroutine 147 [running]:
database/sql.(*DB).Close(0x0, 0x927b00, 0xc420128230)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/database/sql/sql.go:720 +0x37
main.(*Exporter).getDB(0xc4202a4100, 0xc420037770, 0x42, 0xbefeafe648c77829, 0x3d918d28b0, 0xb930c0)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:1000 +0x18a
main.(*Exporter).scrape(0xc4202a4100, 0xc420109ce0)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:1018 +0xde
main.(*Exporter).Collect(0xc4202a4100, 0xc420109ce0)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:767 +0x3c
github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc4205520d0, 0xc420109ce0, 0x92a4e0, 0xc4202a4100)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:383 +0x61
created by github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:381 +0x302
```

This looks related, but not helpful:

https://github.com/wrouesnel/postgres_exporter/issues/194

**Comment by dominik-bln** [comment]
We are seeing the same with version v2.7.10. Production is at v2.6.6 and works fine.

**Comment by tompizmor** [comment]
Hello @dominik-bln,

I am not able to reproduce the issue. This is what I have done:

Install postgresql chart (Version 3.7.2)

```
$ helm install --name=postgresql stable/postgresql --set metrics.enabled=true,postgresqlPassword=qwer1234,postgresqlDatabase=testdb
```

Check the logs of the metrics container:

```
$ kubectl logs -f postgresql-postgresql-0 -c metrics
time="2019-01-03T08:53:50Z" level=info msg="Established new database connection." source="postgres_exporter.go:995"
time="2019-01-03T08:53:50Z" level=info msg="Error while closing non-pinging DB connection: <nil>" source="postgres_exporter.go:1001"
time="2019-01-03T08:53:50Z" level=info msg="Error opening connection to database (postgresql://postgres:PASSWORD_REMOVED@localhost:5432/testdb?sslmode=disable): dial tcp [::1]:5432: connect: connection refused" source="postgres_exporter.go:1030"
time="2019-01-03T08:53:50Z" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1137"
time="2019-01-03T08:54:06Z" level=info msg="Established new database connection." source="postgres_exporter.go:995"
time="2019-01-03T08:54:06Z" level=info msg="Semantic Version Changed: 0.0.0 -> 10.6.0" source="postgres_exporter.go:925"
```

Then I installed Prometheus and Grafana and import a PostgreSQL dashboard and I am able to see the metrics:

![screenshot 2019-01-03 at 10 04 11](https://user-images.githubusercontent.com/4026184/50629943-f4be1e00-0f3e-11e9-933b-bc37fdf8b3be.png)


Can you try using an updated version of the PostgreSQL chart?

**Comment by dominik-bln** [comment]
Looks like it works with the newest version. Thanks for looking into this.
