### ISSUE TITLE
Get Readiness probe failed error message when running Elasticsearch

### ISSUE THREAD

**Issue by robinho81** [helm/charts#10478]
Bug

**Version of Helm and Kubernetes**:

Docker for Desktop Kubernetes (Windows 10)
Kubernetes: 1.10.3
Helm: 2.12.0

**Which chart**:
stable/elasticsearch
Run:
helm install --name my-release stable/elasticsearch --namespace logging

**What happened**:
Elastic search does not run. I get the error message:
Readiness probe failed: Get http://10.1.0.90:9200/_cluster/health: dial tcp 10.1.0.90:9200: connect: connection refused

**What you expected to happen**:
Elastic search to run / Pods to be healthy

**How to reproduce it** (as minimally and precisely as possible):
helm install --name my-release stable/elasticsearch --namespace logging
(Obviously I can change the release name here but it shouldn't matter)

**Anything else we need to know**:
From the Pod logs I get the following:
java.net.UnknownHostException: my-release-elasticsearch-discovery
	at java.net.InetAddress$CachedAddresses.get(InetAddress.java:797) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1505) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1364) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1298) ~[?:?]
	at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:707) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:662) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:768) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$resolveHostsLists$0(UnicastZenPing.java:184) ~[elasticsearch-6.5.4.jar:6.5.4]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) [elasticsearch-6.5.4.jar:6.5.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[2019-01-08T15:43:28,174][WARN ][o.e.d.z.ZenDiscovery     ] [my-release-elasticsearch-client-5887d5d8cd-2lkkf] not enough master nodes discovered during pinging (found [[]], but needed [2]), pinging again
[2019-01-08T15:43:28,207][WARN ][o.e.d.z.UnicastZenPing   ] [my-release-elasticsearch-client-5887d5d8cd-2lkkf] failed to resolve host [my-release-elasticsearch-discovery]
java.net.UnknownHostException: my-release-elasticsearch-discovery: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
	at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929) ~[?:?]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515) ~[?:?]

**Comment by robinho81** [comment]
I have been looking at this in more detail. When I look at the my-release-elasticsearch-discovery Service in Kubernetes, I seem to be getting the following error message:-

> pod has unbound PersistentVolumeClaims
> Error: failed to start container "chown": Error response from daemon: error while creating mount source path '/host_mnt/c/Users/(username)/.docker/Volumes/data-my-release-elasticsearch-master-0/pvc-3fc181f7-13f2-11e9-b512-00155d8a4308': mkdir /host_mnt/c/Users/(username)/.docker/Volumes: permission denied
> Back-off restarting failed container

So it seems that this is a storage problem, and the PersistentVolumeClaims cannot be bound successfully. 

I had assumed that Docker for desktop adds a default hostpath storage class, and that this would be all that is needed for these PersistentVolumeClaims to access volumes on the local drive.

But then I remembered that I had encountered a problem with Sharing Windows Drives in Docker for Desktop, as I am using an AD account. See: http://peterjohnlightfoot.com/docker-for-windows-on-hyper-v-fix-the-host-volume-sharing-issue/

After "fixing" the permissions on the ".docker" folder, everything works. Hacky though.
