### ISSUE TITLE
elasticsearch cluster failing by connection refused to port 9200 and discovery fails

### ISSUE THREAD

**Issue by manojtr** [helm/charts#10791]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: K8 - 1.11.3, helm - 2.7.2

**Which chart**: elasticsearch

**What happened**: Tried to install elasticsearch (5.6.14) cluster on k8 using the helm chart without much changes in the charts except the appversion but the cluster didn't come up. The error saying. 

The error says:

```
Readiness probe failed: Get http://10.2.13.10:9200/_cluster/health: dial tcp 10.2.13.10:9200: connect: connection refused
```
This is the error on every single pod in the cluster. None of the pods come up and all saying the above error.  When I look at the logs of the master I see a different error: 

```
[2019-01-21T00:30:41,722][WARN ][o.e.d.z.UnicastZenPing   ] [sp-es-beta-elasticsearch-master-0] failed to resolve host [sp-es-beta-elasticsearch-discovery]
java.net.UnknownHostException: sp-es-beta-elasticsearch-discovery
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281) ~[?:1.8.0_191]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0_191]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_191]
	at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:911) ~[elasticsearch-5.6.14.jar:5.6.14]
	at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:866) ~[elasticsearch-5.6.14.jar:5.6.14]
	at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:709) ~[elasticsearch-5.6.14.jar:5.6.14]
	at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$null$0(UnicastZenPing.java:212) ~[elasticsearch-5.6.14.jar:5.6.14]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:576) [elasticsearch-5.6.14.jar:5.6.14]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

I tried the following: 

1. Tried to expose the http port in master and data in values.yml (`exposeHttp: true`)
2. Convert the discovery service to a Loadbalancer type and now the errors are, connection refused to port 9200 and "not enough master" . 

**What you expected to happen**: The cluster should come up and working

**How to reproduce it** (as minimally and precisely as possible):
Using the elasticsearch 5.6.14 docker image, try to build the cluster on a k8 cluster using the stable helm chart in this repo. 

**Anything else we need to know**:

**Comment by wolfpack94** [comment]
Running into the same issue. Any update?

**Comment by anapsix** [comment]
You should set `appVersion` to match the image tag you are using.
see more details in https://github.com/helm/charts/pull/9910#issuecomment-464061523
