### ISSUE TITLE
[stable/prometheus-operator] [stable/granfana] grafana sidecar SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by wu105** [helm/charts#11287]
This seems the same issue as  https://github.com/helm/charts/issues/9118 which was closed after go stale without any reference to fixes.  I don't know how to reopen it.  This is a showstopper for grafana under prometheus or used with kubernetes, because the grafana is not working with the sidecar failures like this, thus we should not close this issue unless it is fixed.

I have hit a similar error using stable/prometheus-operator 1.8.0, which uses subchart stable/grafana 1.24.2.  This issue did not exist in coreos/prometheus-operator + coreos/kube-prometheus.

Apparently we need an option or instruction to supply the certificate to verify the ssl certificate of the h ttps server, the kubernetes apiserver to be exact, or turning off the verification.   

A related issue on the upstream grafana sidecar image 0.0.6 can be found here: https://github.com/kiwigrid/k8s-sidecar/issues/18

Here is the log produced by one of the sidecar containers:

```
  Starting config map collector
Config for cluster api loaded...
2019-02-08 19:01:25,019 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),)': /api/v1/namespaces/monitoring/configmaps?watch=True
2019-02-08 19:01:25,026 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),)': /api/v1/namespaces/monitoring/configmaps?watch=True
2019-02-08 19:01:25,032 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),)': /api/v1/namespaces/monitoring/configmaps?watch=True
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 372, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
    for event in stream:
  File "/usr/local/lib/python3.6/site-packages/kubernetes/watch/watch.py", line 122, in stream
    resp = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11650, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11753, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 322, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.96.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/monitoring/configmaps?watch=True (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),))
```

**Comment by wu105** [comment]
We have a fix on the grafana sidecar https://github.com/kiwigrid/k8s-sidecar/pull/19
Would you please

-  update the grafana subchart to use the new sidecar version kiwigrid/k8s-sidecar:0.0.11 and add the new configurable env SKIP_TLS_VERIFY to both the values.yaml and the deployment.yaml

- update the prometneus-operator chart to use the new grafana subchart

**Comment by den-is** [comment]
Hey? ISSUE IS NOT CLOSED ! It still persists , give us ability to pass environment variables to that image
