### ISSUE TITLE
[stable/jenkins] mkdir: cannot create directory ‘/usr/share/jenkins/ref/plugins’: Read-only file system

### ISSUE THREAD

**Issue by erihanse** [helm/charts#11585]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm 2.12.2
Kubernetes 1.11.5

**Which chart**:
stable/jenkins

**What happened**:
Getting 
>mkdir: cannot create directory ‘/usr/share/jenkins/ref/plugins’: Read-only file system

in init-container(copy-default-config) when trying to deploy Jenkins. No plugins are loaded. 

**What you expected to happen**:
Plugins are downloaded and installed. 

**How to reproduce it** (as minimally and precisely as possible):
Enable readonlyrootfilesystem and install Jenkins.

**Anything else we need to know**:
readOnlyRootFilesystem is considered a best-practice for running containers in kubernetes. It should be possible to deploy jenkins with this security setting.

**Comment by erihanse** [comment]
I made the chart work by adding /tmp and /usr/share/jenkins/ref/plugins as volumeMounts to the init-container as well. Seems strange that the script references this last directory? If that's correct it should be added to volumeMounts as well.

**Comment by erihanse** [comment]
In addition with the side car:

```
✗ k logs jenkins-erik-645584b6d5-g7rfc jenkins-sc-config 
Traceback (most recent call last):
  File "/app/sidecar.py", line 190, in <module>
    main()
  File "/app/sidecar.py", line 133, in main
    logger = setup_custom_logger('sidecar')
  File "/app/sidecar.py", line 73, in setup_custom_logger
    handler = logging.FileHandler('log.txt', mode='w')
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/app/log.txt'

```
