### ISSUE TITLE
[stable/gitlab-ce] my-gitlab-gitlab-ce  pod - The following is the wrong repor

### ISSUE THREAD

**Issue by kissingtiger** [helm/charts#11944]
![Uploading image.png…]()

**Comment by kissingtiger** [comment]
Preparing services...
Starting services...
Configuring GitLab package...
/opt/gitlab/embedded/bin/runsvdir-start: line 37: /proc/sys/fs/file-max: Read-only file system
Configuring GitLab...


  * Moving existing certificates found in /opt/gitlab/embedded/ssl/certs

  * Symlinking existing certificates found in /etc/gitlab/trusted-certs

================================================================================
Error executing action `run` on resource 'bash[migrate gitlab-rails database]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of "bash"  "/tmp/chef-script20190306-32-qjt8f4" ----
STDOUT: rake aborted!
SocketError: getaddrinfo: Name or service not known
/opt/gitlab/embedded/service/gitlab-rails/app/models/application_setting.rb:200:in `cached'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/current_settings.rb:27:in `cached_application_settings'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/current_settings.rb:22:in `ensure_application_settings!'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/current_settings.rb:7:in `current_application_settings'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/metrics/influx_db.rb:20:in `settings'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/metrics/influx_db.rb:11:in `influx_metrics_enabled?'
/opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/metrics.rb:7:in `enabled?'
/opt/gitlab/embedded/service/gitlab-rails/config/initializers/8_metrics.rb:129:in `<top (required)>'
/opt/gitlab/embedded/service/gitlab-rails/config/environment.rb:5:in `<top (required)>'
/opt/gitlab/embedded/bin/bundle:22:in `load'
/opt/gitlab/embedded/bin/bundle:22:in `<main>'
Tasks: TOP => gitlab:db:configure => environment
(See full trace by running task with --trace)
STDERR: 
---- End output of "bash"  "/tmp/chef-script20190306-32-qjt8f4" ----
Ran "bash"  "/tmp/chef-script20190306-32-qjt8f4" returned 1

Resource Declaration:
---------------------
# In /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/recipes/database_migrations.rb

 51: bash "migrate gitlab-rails database" do
 52:   code <<-EOH
 53:     set -e
 54:     log_file="#{node['gitlab']['gitlab-rails']['log_directory']}/gitlab-rails-db-migrate-$(date +%Y-%m-%d-%H-%M-%S).log"
 55:     umask 077
 56:     /opt/gitlab/bin/gitlab-rake gitlab:db:configure 2>& 1 | tee ${log_file}
 57:     STATUS=${PIPESTATUS[0]}
 58:     echo $STATUS > #{db_migrate_status_file}
 59:     exit $STATUS
 60:   EOH
 61:   environment env_variables unless env_variables.empty?
 62:   notifies :run, 'execute[enable pg_trgm extension]', :before if omnibus_helper.service_enabled?('postgresql')
 63:   notifies :run, "execute[clear the gitlab-rails cache]", :immediately
 64:   dependent_services.each do |svc|
 65:     notifies :restart, svc, :immediately
 66:   end
 67:   not_if "(test -f #{db_migrate_status_file}) && (cat #{db_migrate_status_file} | grep -Fx 0)"
 68:   only_if { node['gitlab']['gitlab-rails']['auto_migrate'] }
 69: end

Compiled Resource:
------------------
# Declared in /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/recipes/database_migrations.rb:51:in `from_file'

bash("migrate gitlab-rails database") do
  action [:run]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  command "migrate gitlab-rails database"
  backup 5
  environment {"GITLAB_ROOT_PASSWORD"=>"Qwa!2W0"}
  returns 0
  code "    set -e\n    log_file=\"/var/log/gitlab/gitlab-rails/gitlab-rails-db-migrate-$(date +%Y-%m-%d-%H-%M-%S).log\"\n    umask 077\n    /opt/gitlab/bin/gitlab-rake gitlab:db:configure 2>& 1 | tee ${log_file}\n    STATUS=${PIPESTATUS[0]}\n    echo $STATUS > /var/opt/gitlab/gitlab-rails/upgrade-status/db-migrate-ccb26d3db96503f123efa1224db87c1a-6678b4e\n    exit $STATUS\n"
  interpreter "bash"
  declared_type :bash
  cookbook_name "gitlab"
  recipe_name "database_migrations"
  not_if "(test -f /var/opt/gitlab/gitlab-rails/upgrade-status/db-migrate-ccb26d3db96503f123efa1224db87c1a-6678b4e) && (cat /var/opt/gitlab/gitlab-rails/upgrade-status/db-migrate-ccb26d3db96503f123efa1224db87c1a-6678b4e | grep -Fx 0)"
  only_if { #code block }
end

Platform:
---------
x86_64-linux
