### ISSUE TITLE
[stable/airflow] airflow webserver generates python error

### ISSUE THREAD

**Issue by rschoenbeck** [helm/charts#12042]
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report

**Version of Helm and Kubernetes**:

Helm: v2.13.0
kubectl: v1.13.4
minikube: v0.34.1

**Which chart**:
stable/airflow 2.1.0

**What happened**:

Requests to access the Airflow web server in a browser produce the following error -- TypeError: b'Content-Type' is not a string

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/wsgi.py", line 826, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/airflow/www/app.py", line 173, in root_app
    resp(b'404 Not Found', [(b'Content-Type', b'text/plain')])
  File "/usr/local/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 253, in start_response
    self.process_headers(headers)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 260, in process_headers
    raise TypeError('%r is not a string' % name)
TypeError: b'Content-Type' is not a string
172.17.0.1 - - [10/Mar/2019:00:16:36 +0000] "GET / HTTP/1.1" 500 0 "-" "-"
[2019-03-10 00:16:36 +0000] [25] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/wsgi.py", line 826, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/airflow/www/app.py", line 173, in root_app
    resp(b'404 Not Found', [(b'Content-Type', b'text/plain')])
  File "/usr/local/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 253, in start_response
    self.process_headers(headers)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 260, in process_headers
    raise TypeError('%r is not a string' % name)
TypeError: b'Content-Type' is not a string
```
Potentially related to https://issues.apache.org/jira/browse/AIRFLOW-2190

**What you expected to happen**:

To be able to access the admin panel of airflow normally

**How to reproduce it** (as minimally and precisely as possible):

From the charts/airflow directory...

1. minikube start
2. helm init
3. helm dependency build ${PWD}
4. helm install --namespace "airflow" --name "airflow" -f examples/minikube-values.yaml ${PWD}
5. wait for services to spin up
6. minikube service -n airflow airflow-web
7. Observe the "Internal server error" at the web page and the above error in the logs.

**Comment by gsemet** [comment]
Hi. Have you tried with latest airflow image (from puckel)?

**Comment by scyantist** [comment]
I also saw this TypeError when installing from the example/minikube-values.yaml. But, I did not see this error when installing from values.yaml

**Comment by stijndehaes** [comment]
Yeah I think the ingress configuration in the example/minikube-values.yaml ensures this error.
