### ISSUE TITLE
stable/neo4j - "Connection refused" when trying to exec cypher-shell

### ISSUE THREAD

**Issue by joeatdais** [helm/charts#12194]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm Client: v2.9.1
Helm Server:v2.9.1
Kubernetes: 1.13.0

**Which chart**:
https://github.com/helm/charts/tree/master/stable/neo4j

**What happened**:
"Connection Refused" is returned when trying to execute cypher shell. 

Input:
```
kubectl exec neo4j-neo4j-replica-6dfcfcf675-btnhg -- bin/cypher-shell --format verbose \
"CALL dbms.cluster.overview() YIELD id, role RETURN id, role"
```
Output:
```
Connection refused
command terminated with exit code 1
```

Additionally, if I exec into the container, I'm still unable to access the cypher-shell.
```
bash-4.4# ./bin/cypher-shell
Connection refused
```

**What you expected to happen**:
I expected to be returned some results like the example shows:
```
$ kubectl exec neo-helm-neo4j-core-0 -- bin/cypher-shell --format verbose \
"CALL dbms.cluster.overview() YIELD id, role RETURN id, role"
+---------------------------------------------------------+
| id                                     | role           |
+---------------------------------------------------------+
| "32e6b76d-4f52-4aaa-ad3b-11bc4a3a5db6" | "LEADER"       |
| "1070d088-cc5f-411d-9e64-f5669198f5b2" | "FOLLOWER"     |
| "e2b0ef4c-6caf-4621-ab30-ba659e0f79a1" | "FOLLOWER"     |
| "f79dd7e7-18e7-4d82-939a-1bf09f8c0f42" | "READ_REPLICA" |
| "b8f4620c-4232-498e-b39f-8d57a512fa0e" | "READ_REPLICA" |
| "74c9cb59-f400-4621-ac54-994333f0278f" | "READ_REPLICA" |
+---------------------------------------------------------+
```

**How to reproduce it** (as minimally and precisely as possible):
Followed [this guide](https://neo4j.com/blog/kubernetes-deploy-neo4j-clusters/)

After installing and scaling the replica set, run the following command:
```
helm install --name neo4j-helm stable/neo4j --set acceptLicenseAgreement=yes --set neo4jPassword=mySecretPassword
```

**Anything else we need to know**:
This is all new to me, and I barely know what I'm doing, but I can certainly answer questions about what I did.

**Comment by arafatmohammed** [comment]
We also see this error:

`Please see the attached cause exception "Failed to join a cluster with members {clusterId=null, bootstrappable=false, coreMembers={}}. Another member should have published a clusterId but none was detected. Please restart the cluster.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
	at com.neo4j.causalclustering.core.CommercialCoreGraphDatabase.<init>(CommercialCoreGraphDatabase.java:35)
	at com.neo4j.causalclustering.core.CommercialCoreGraphDatabase.<init>(CommercialCoreGraphDatabase.java:26)
	at com.neo4j.server.enterprise.CommercialNeoServer.lambda$static$0(CommercialNeoServer.java:29)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.causalclustering.core.state.CoreLife@61942c1' was successfully initialized, but failed to start. Please see the attached cause exception "Failed to join a cluster with members {clusterId=null, bootstrappable=false, coreMembers={}}. Another member should have published a clusterId but none was detected. Please restart the cluster.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
	... 10 more
Caused by: java.util.concurrent.TimeoutException: Failed to join a cluster with members {clusterId=null, bootstrappable=false, coreMembers={}}. Another member should have published a clusterId but none was detected. Please restart the cluster.
	at org.neo4j.causalclustering.identity.ClusterBinder.bindToCluster(ClusterBinder.java:167)
	at org.neo4j.causalclustering.core.state.CoreLife.start0(CoreLife.java:74)
	at org.neo4j.kernel.lifecycle.SafeLifecycle.transition(SafeLifecycle.java:124)
	at org.neo4j.kernel.lifecycle.SafeLifecycle.start(SafeLifecycle.java:138)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)`

**Comment by alegargar** [comment]
Any update? 
I have the same issue. I'have tried it using different environments:  minikube, Mac OS Desktop docker kubernetes, and Amazon EKS cluster.. And different computers (all Macs). Same result everywhere: "Connection Refused". 
It occurs with auth enabled and without it too.

**Comment by praseedasathaye** [comment]
Any update on this issue. I am also getting same error.
