### ISSUE TITLE
Nexus is failing in my kubernetes cluster due to the (Error occurred while executing a write operation to database 'OSystem' due to limited free space on the disk (868 MB).)

### ISSUE THREAD

**Issue by Sam123ben** [helm/charts#12298]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**Version of Helm and Kubernetes**:
k8s: Server Version: v1.11.8-eks-7c34c0
helm: Server: v2.13.0+g79d0794

**Which chart**:
nexus stable/sonatype-nexus

**What happened**:
The helm command I executed:
helm upgrade --namespace tools --install nexus stable/sonatype-nexus --set rbac.create=true \
    --set nexusProxy.targetPort=80 --set nexusProxy.port=80 \
    --set nexus.service.type=ClusterIP \
    --set ingress.enabled=true \
    --set ingress.tls.enabled=false \
    --set ingress.annotations."kubernetes\.io/ingress.class"="nginx" \
    --set ingress.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-proxy-protocol"="*" \
    --set ingress.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-connection-idle-timeout"="60" \
    --set nexusProxy.env.nexusHttpHost="nexus.tools.${platform}.$FLAVOUR.${dns_suffix}" \
    --set persistence.enabled=true --set persistence.storageSize=200 --set persistence.storageClass=aws-gp2

Was able to bring up the nexus pod but the enxus application started going into crashloops:

> com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'OSystem' due to limited free space on the disk (868 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 4096 MB. Required space is now set to 4096MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .

**What you expected to happen**:
Should be able to run the nexus app and should be able to access nexus

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by Sam123ben** [comment]
OSystem`: 2.2.36 (build d3beb772c02098ceaea89779a7afd4b7305d3788, branch 2.2.x)
com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'OSystem' due to limited free space on the disk (868 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 4096 MB. Required space is now set to 4096MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .
	DB name="OSystem"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpaceRequestsAndReadOnlyConditions(OAbstractPaginatedStorage.java:5073)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:1339)
	at com.orientechnologies.orient.core.config.OStorageConfigurationImpl.create(OStorageConfigurationImpl.java:707)
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.create(OStorageConfigurationSegment.java:121)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:489)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:131)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:438)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:160)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:44)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1309)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:367)
	at org.sonatype.nexus.internal.orient.DatabaseServerImpl.doStart(DatabaseServerImpl.java:186)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:67)
	at org.sonatype.nexus.internal.orient.DatabaseServerImpl$$EnhancerByGuice$$fa2436b0.CGLIB$start$10(<generated>)
	at org.sonatype.nexus.internal.orient.DatabaseServerImpl$$EnhancerByGuice$$fa2436b0$$FastClassByGuice$$3053a5d0.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:56)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
	at org.sonatype.nexus.internal.orient.DatabaseServerImpl$$EnhancerByGuice$$fa2436b0.start(<generated>)
	at org.sonatype.nexus.internal.orient.OrientBootstrap.doStart(OrientBootstrap.java:78)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:67)
	at org.sonatype.nexus.internal.orient.OrientBootstrap$$EnhancerByGuice$$221620cd.CGLIB$start$4(<generated>)
	at org.sonatype.nexus.internal.orient.OrientBootstrap$$EnhancerByGuice$$221620cd$$FastClassByGuice$$c04bff7f.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:56)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
	at org.sonatype.nexus.internal.orient.OrientBootstrap$$EnhancerByGuice$$221620cd.start(<generated>)
	at org.sonatype.nexus.extender.NexusLifecycleManager.startComponent(NexusLifecycleManager.java:168)
	at org.sonatype.nexus.extender.NexusLifecycleManager.to(NexusLifecycleManager.java:100)
	at org.sonatype.nexus.extender.NexusContextListener.frameworkEvent(NexusContextListener.java:195)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1429)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
2019-03-16 01:20:59,831+0000 ERROR [FelixStartLevel] *SYSTEM com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage - Exception `582E6598` in storage `plocal:/nexus-data/db/OSystem`: 2.2.36 (build d3beb772c02098ceaea89779a7afd4b7305d3788, branch 2.2.x)
com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'OSystem' due to limited free space on the disk (868 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 4096 MB. Required space is now set to 4096MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .
	DB name="OSystem"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpaceRequestsAndReadOnlyConditions(OAbstractPaginatedStorage.java:5073)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:1339)
	at com.orientechnologies.orient.core.config.OStorageConfigurationImpl.create(OStorageConfigurationImpl.java:707)
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.create(OStorageConfigurationSegment.java:121)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:489)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:131)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:438)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:160)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:44)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1309)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:367)
	at org.sonatype.nexus.internal.orient.DatabaseServerImpl.doStart(DatabaseServerImpl.java:186)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:67)
	at org.sonatype.nexus.internal.orient.DatabaseServerImpl$$EnhancerByGuice$$fa2436b0.CGLIB$start$10(<generated>)
	at org.sonatype.nexus.internal.orient.DatabaseServerImpl$$EnhancerByGuice$$fa2436b0$$FastClassByGuice$$3053a5d0.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:56)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
	at org.sonatype.nexus.internal.orient.DatabaseServerImpl$$EnhancerByGuice$$fa2436b0.start(<generated>)
	at org.sonatype.nexus.internal.orient.OrientBootstrap.doStart(OrientBootstrap.java:78)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:67)
	at org.sonatype.nexus.internal.orient.OrientBootstrap$$EnhancerByGuice$$221620cd.CGLIB$start$4(<generated>)
	at org.sonatype.nexus.internal.orient.OrientBootstrap$$EnhancerByGuice$$221620cd$$FastClassByGuice$$c04bff7f.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:56)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
	at org.sonatype.nexus.internal.orient.OrientBootstrap$$EnhancerByGuice$$221620cd.start(<generated>)
	at org.sonatype.nexus.extender.NexusLifecycleManager.startComponent(NexusLifecycleManager.java:168)
	at org.sonatype.nexus.extender.NexusLifecycleManager.to(NexusLifecycleManager.java:100)
	at org.sonatype.nexus.extender.NexusContextListener.frameworkEvent(NexusContextListener.java:195)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1429)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
2019-03-16 01:20:59,844+0000 ERROR [FelixStartLevel] *SYSTEM com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage - Exception `582E6598` in storage `plocal:/nexus-data/db/OSystem`: 2.2.36 (build d3beb772c02098ceaea89779a7afd4b7305d3788, branch 2.2.x)
com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'OSystem' due to limited free space on the disk (868 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 4096 MB. Required space is now set to 4096MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .
	DB name="OSystem"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpaceRequestsAndReadOnlyConditions(OAbstractPaginatedStorage.java:5073)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:1339)
	at com.orientechnologies.orient.core.config.OStorageConfigurationImpl.create(OStorageConfigurationImpl.java:707)
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.create(OStorageConfigurationSegment.java:121)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:489)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:131)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:438)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:160)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:44)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1309)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:367)
	at org.sonatype.nexus.internal.orient.DatabaseServerImpl.doStart(DatabaseServerImpl.java:186)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:67)
	at org.sonatype.nexus.internal.orient.DatabaseServerImpl$$EnhancerByGuice$$fa2436b0.CGLIB$start$10(<generated>)
	at org.sonatype.nexus.internal.orient.DatabaseServerImpl$$EnhancerByGuice$$fa2436b0$$FastClassByGuice$$3053a5d0.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:56)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
	at org.sonatype.nexus.internal.orient.DatabaseServerImpl$$EnhancerByGuice$$fa2436b0.start(<generated>)
	at org.sonatype.nexus.internal.orient.OrientBootstrap.doStart(OrientBootstrap.java:78)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:67)
	at org.sonatype.nexus.internal.orient.OrientBootstrap$$EnhancerByGuice$$221620cd.CGLIB$start$4(<generated>)
	at org.sonatype.nexus.internal.orient.OrientBootstrap$$EnhancerByGuice$$221620cd$$FastClassByGuice$$c04bff7f.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:56)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:77)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
	at org.sonatype.nexus.internal.orient.OrientBootstrap$$EnhancerByGuice$$221620cd.start(<generated>)
	at org.sonatype.nexus.extender.NexusLifecycleManager.startComponent(NexusLifecycleManager.java:168)
	at org.sonatype.nexus.extender.NexusLifecycleManager.to(NexusLifecycleManager.java:100)
	at org.sonatype.nexus.extender.NexusContextListener.frameworkEvent(NexusContextListener.java:195)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1429)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
2019-03-16 01:20:59,871+0000 ERROR [FelixStartLevel] *SYSTEM org.sonatype.nexus.internal.orient.DatabaseServerImpl - Failed transition: NEW -> STARTED
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'OSystem'
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:506)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:160)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:44)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1309)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:367)
	at org.sonatype.nexus.internal.orient.DatabaseServerImpl.doStart(DatabaseServerImpl.java:186)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:67)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:56)
	at org.sonatype.nexus.internal.orient.OrientBootstrap.doStart(OrientBootstrap.java:78)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:67)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:56)
	at org.sonatype.nexus.extender.NexusLifecycleManager.startComponent(NexusLifecycleManager.java:168)
	at org.sonatype.nexus.extender.NexusLifecycleManager.to(NexusLifecycleManager.java:100)
	at org.sonatype.nexus.extender.NexusContextListener.frameworkEvent(NexusContextListener.java:195)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1429)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'OSystem' due to limited free space on the disk (868 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 4096 MB. Required space is now set to 4096MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .
	DB name="OSystem"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpaceRequestsAndReadOnlyConditions(OAbstractPaginatedStorage.java:5073)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:1339)
	at com.orientechnologies.orient.core.config.OStorageConfigurationImpl.create(OStorageConfigurationImpl.java:707)
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.create(OStorageConfigurationSegment.java:121)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:489)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:131)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:438)
	... 20 common frames omitted
2019-03-16 01:20:59,874+0000 ERROR [FelixStartLevel] *SYSTEM org.sonatype.nexus.internal.orient.OrientBootstrap - Failed transition: NEW -> STARTED
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'OSystem'
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:506)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:160)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:44)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1309)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:367)
	at org.sonatype.nexus.internal.orient.DatabaseServerImpl.doStart(DatabaseServerImpl.java:186)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:67)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:56)
	at org.sonatype.nexus.internal.orient.OrientBootstrap.doStart(OrientBootstrap.java:78)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:67)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:56)
	at org.sonatype.nexus.extender.NexusLifecycleManager.startComponent(NexusLifecycleManager.java:168)
	at org.sonatype.nexus.extender.NexusLifecycleManager.to(NexusLifecycleManager.java:100)
	at org.sonatype.nexus.extender.NexusContextListener.frameworkEvent(NexusContextListener.java:195)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1429)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'OSystem' due to limited free space on the disk (868 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 4096 MB. Required space is now set to 4096MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .
	DB name="OSystem"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpaceRequestsAndReadOnlyConditions(OAbstractPaginatedStorage.java:5073)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:1339)
	at com.orientechnologies.orient.core.config.OStorageConfigurationImpl.create(OStorageConfigurationImpl.java:707)
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.create(OStorageConfigurationSegment.java:121)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:489)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:131)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:438)
	... 20 common frames omitted
2019-03-16 01:20:59,875+0000 ERROR [FelixStartLevel] *SYSTEM org.sonatype.nexus.extender.NexusContextListener - Failed to start nexus
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'OSystem'
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:506)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:160)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:44)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1309)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:367)
	at org.sonatype.nexus.internal.orient.DatabaseServerImpl.doStart(DatabaseServerImpl.java:186)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:67)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:56)
	at org.sonatype.nexus.internal.orient.OrientBootstrap.doStart(OrientBootstrap.java:78)
	at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:67)
	at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
	at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
	at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:56)
	at org.sonatype.nexus.extender.NexusLifecycleManager.startComponent(NexusLifecycleManager.java:168)
	at org.sonatype.nexus.extender.NexusLifecycleManager.to(NexusLifecycleManager.java:100)
	at org.sonatype.nexus.extender.NexusContextListener.frameworkEvent(NexusContextListener.java:195)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1429)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'OSystem' due to limited free space on the disk (868 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 4096 MB. Required space is now set to 4096MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .
	DB name="OSystem"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpaceRequestsAndReadOnlyConditions(OAbstractPaginatedStorage.java:5073)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:1339)
	at com.orientechnologies.orient.core.config.OStorageConfigurationImpl.create(OStorageConfigurationImpl.java:707)
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.create(OStorageConfigurationSegment.java:121)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:489)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:131)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:438)
	... 20 common frames omitted

**Comment by Sam123ben** [comment]
Resolved this issue

**Comment by dimitraz** [comment]
How did you resolve this? @Sam123ben

**Comment by sunilbolleddu** [comment]
Same issue, how to resolve this? I tried removing *.wal files under db/component but they are very small size.
