### ISSUE TITLE
[stable/jenkins] CrashLoopBackOff sidecar container with Active-Directory

### ISSUE THREAD

**Issue by tomerleib** [helm/charts#12370]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Version of Helm and Kubernetes**:
```
helm version                     
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:24:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
Jenkins v.0.35.0

**What happened**:
Jcasc Sidecar is in CrashLoopBack when setting up Active-Directory authentication and changing the admin user.

**What you expected to happen**:
Jcasc will not crush and after the pod is up, authentication via Active-Directory will work.

**How to reproduce it** (as minimally and precisely as possible):
1. `JCasc.ConfigScripts` is set to:
```yaml
Master:
  AdminUser: bind
  AdminPassword: "my@secret"
  JCasC:
    enabled: true
    PluginVersion: 1.5
    SupportPluginVersion: 1.5
    ConfigScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our CI\CD server.  This Jenkins is configured and managed 'as code'.
      active-directory: |
        jenkins:
          SecurityRealm:
            activeDirectory:
                cache:
                    size: 256
                    ttl: 600
                customDomain: true
                groupLookupStrategy: AUTO
                domains:
                    - name: "domain.local"
                      servers: "1.2.3.4:3268"
                      bindName: "bind@domain.local"
                      bindPassword: "my@secret"
      matrix-auth: |
        jenkins:
          authorizationStrategy:
            projectMatrix:
              grantedPermissions:
                - "Overall/Administer:bind@domain.local"
  Sidecars:
    configAutoReload:
      enabled: true
```

Using this code result in the following errors in the side-car:
```
kubectl logs -f -n jenkins jnk-jenkins-854566754f-69tjm jenkins-sc-config
2019-03-19 10:27:42 INFO     Starting config map collector
2019-03-19 10:27:42 INFO     label is: jenkins_config
2019-03-19 10:27:42 INFO     targetFolder is: /var/jenkins_home/casc_configs
2019-03-19 10:27:42 INFO     Config for cluster api loaded...
2019-03-19 10:27:42 INFO     namespace is: jenkins
2019-03-19 10:27:42 INFO     ssh_port is: 1044
2019-03-19 10:27:42 INFO     admin_user is: bind
2019-03-19 10:27:42 INFO     Jenkins is contactable, continuing.
2019-03-19 10:27:42 INFO     Working on configmap jenkins/jnk-jenkins-tests
2019-03-19 10:27:42 INFO     Working on configmap jenkins/jenkins-config-jnk-jenkins-matrix-auth
2019-03-19 10:27:42 INFO     Working on configmap jenkins/jenkins-config-jnk-jenkins-matrix-auth
2019-03-19 10:27:42 INFO     Configmap with label found
2019-03-19 10:27:42 INFO     File in configmap matrix-auth.yaml ADDED
Traceback (most recent call last):
  File "/app/sidecar.py", line 190, in <module>
    main()
  File "/app/sidecar.py", line 185, in main
    ssh_port)
  File "/app/sidecar.py", line 123, in watchForChanges
    jenkinsReloadConfig(admin_private_key, admin_user, ssh_port, logger)
  File "/app/sidecar.py", line 22, in jenkinsReloadConfig
    ssh_client.connect('127.0.0.1', port=ssh_port, username=admin_user, pkey=private_key)
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 437, in connect
    passphrase,
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 749, in _auth
    raise saved_exception
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 649, in _auth
    self._transport.auth_publickey(username, pkey)
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1507, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/local/lib/python3.6/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```

**Comment by maorfr** [comment]
@holmes wdyt?

**Comment by tomerleib** [comment]
Anything?

**Comment by maorfr** [comment]
@torstenwalter can you ptal?

**Comment by torstenwalter** [comment]
Please configure `Master.AdminUser` or as it is called now `master.adminUser` as well.

I suspect this to be related to what is described within `values.yaml`:

> When enabling LDAP or another non-Jenkins identity source, the built-in admin account will no longer exist.
> Since the AdminUser is used by configAutoReload, in order to use configAutoReload you must change the `.master.adminUser` to a valid username on your LDAP (or other) server.  This user does not need
> to have administrator rights in Jenkins (the default Overall:Read is sufficient) nor will it be granted any
> additional rights.  Failure to do this will cause the sidecar container to fail to authenticate via SSH and enter a restart loop.

**Comment by tomerleib** [comment]
Thanks.
As you can see in my yaml above, I've already configured `Master.AdminUser` to be a valid username from my AD.
It did not help so much

**Comment by torstenwalter** [comment]
Did you login to your Jenkins instance once so that the user is created within Jenkins?
You can check if the user is created using a url like this:
http://jenkins-url:8080/asynchPeople/

If the user exists then you could check if the `SSH Public Key` is configured:
http://jenkins-url:8080/user/bind/configure

**Comment by tomerleib** [comment]
I've managed to reproduce it so I can provide a better understanding of the issue:
If you configure values.yaml with the following settings:
```yaml
master:
  adminUser: "bind"
.......
  JCasC:
    enabled: true
    pluginVersion: 1.5
    supportPluginVersion: 1.5
    configScripts:
      activedirectory: |
        jenkins:
          SecurityRealm:
            activeDirectory:
              domains:
                - name: "domain.local"
                  servers: "1.1.1.1:3268"
                  bindName: "bind@domain.local"
                  bindPassword: "password@1"
....
  sidecars:
    configAutoReload:
      enabled: true
```

Both sidecar and the Jenkins container will be up and the pod is set to 2/2 ready.
However, if you will try to log in with the adminUser and the password - you will get login failed.
In fact, any attempt to log in will fail.

At this stage, I've tried to adjust the settings of AD with the following values:
```yaml
...
  JCasC:
    enabled: true
    pluginVersion: 1.5
    supportPluginVersion: 1.5
    configScripts:
      activedirectory: |
        jenkins:
          SecurityRealm:
            activeDirectory:
              groupLookupStrategy: AUTO
              startTls: true
              domains:
                - name: "domain.local"
                  servers: "1.1.1.1:3268"
                  bindName: "bind@domain.local"
                  bindPassword: "password@1"
...
```
Followed by `helm upgrade jnk -f values.yaml .`
I've checked for the status of the pod and saw that it got into error because jenkins-sc-config is in CrashLoopBackOff due to authentication failure:
```bash
kubectl get po -n jenkins -w      
NAME                          READY   STATUS   RESTARTS   AGE
jnk-jenkins-69f4b8794-klznf   1/2     Error    1          2m2s
jnk-jenkins-69f4b8794-klznf   1/2   CrashLoopBackOff   1     2m12s
jnk-jenkins-69f4b8794-klznf   2/2   Running   2     2m14s
jnk-jenkins-69f4b8794-klznf   1/2   Error   2     2m15s
jnk-jenkins-69f4b8794-klznf   1/2   CrashLoopBackOff   2     2m25s
jnk-jenkins-69f4b8794-klznf   1/2   Error   3     2m38s

kubectl describe  po -n jenkins jnk-jenkins-69f4b8794-klznf
Name:               jnk-jenkins-69f4b8794-klznf
...
Containers:
  ...
  jenkins-sc-config:
    Container ID:   docker://d87f5acfe38ba6e695613633902e012c266553cb09fdbc54aa92e0fe2cec5012
    Image:          shadwell/k8s-sidecar:0.0.2
    Image ID:       docker-pullable://shadwell/k8s-sidecar@sha256:a929ae125a51a244da09243a851536349cb408c149799a45136196cafdbcad62
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 23 Apr 2019 17:21:35 +0300
      Finished:     Tue, 23 Apr 2019 17:21:35 +0300
    Ready:          False

kubectl logs -n jenkins jnk-jenkins-69f4b8794-klznf jenkins-sc-config                                                           
2019-04-23 14:26:50 INFO     Starting config map collector
2019-04-23 14:26:50 INFO     label is: jnk-jenkins-jenkins-config
2019-04-23 14:26:50 INFO     targetFolder is: /var/jenkins_home/casc_configs
2019-04-23 14:26:50 INFO     Config for cluster api loaded...
2019-04-23 14:26:50 INFO     namespace is: jenkins
2019-04-23 14:26:50 INFO     ssh_port is: 1044
2019-04-23 14:26:50 INFO     admin_user is: bind
2019-04-23 14:26:50 INFO     Jenkins is contactable, continuing.
2019-04-23 14:26:50 INFO     Working on configmap jenkins/jnk-jenkins-jenkins-config-mailer
2019-04-23 14:26:50 INFO     Working on configmap jenkins/jnk-jenkins-jenkins-config-mailer
2019-04-23 14:26:50 INFO     Configmap with label found
2019-04-23 14:26:50 INFO     File in configmap mailer.yaml ADDED
Traceback (most recent call last):
  File "/app/sidecar.py", line 190, in <module>
    main()
  File "/app/sidecar.py", line 185, in main
    ssh_port)
  File "/app/sidecar.py", line 123, in watchForChanges
    jenkinsReloadConfig(admin_private_key, admin_user, ssh_port, logger)
  File "/app/sidecar.py", line 22, in jenkinsReloadConfig
    ssh_client.connect('127.0.0.1', port=ssh_port, username=admin_user, pkey=private_key)
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 437, in connect
    passphrase,
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 749, in _auth
    raise saved_exception
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 649, in _auth
    self._transport.auth_publickey(username, pkey)
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1507, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/local/lib/python3.6/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```

However, I've tested it with different settings, in the other case, if in the AD settings I've added both `groupLookupStrategy: AUTO` and `startTls: true` from the first run, any upgrade to the chart does not result in such issues.

**Comment by torstenwalter** [comment]
I suggest to disable auto reload with:

```
  sidecars:
    configAutoReload:
      enabled: false
```

That gives you the chance to fix LDAP authentication first. Once you can successfully login via LDAP, you can try auto reload again.

**Comment by tomerleib** [comment]
Thanks, this one is indeed working.

**Comment by holmesb** [comment]
@tomelei "This user does not need to have administrator rights in Jenkins (the default Overall:Read is sufficient)" is wrong, the adminUser needs Overall:Administer rights.  [The Readme](https://github.com/helm/charts/tree/master/stable/jenkins#auto-reload-with-non-jenkins-identities) is correct, but values.yaml is wrong.  I'll create a PR to correct.
