### ISSUE TITLE
rabbitmqctl list_queues return protocol undefined error

### ISSUE THREAD

**Issue by haiyangu** [helm/charts#12563]
**Version of Helm and Kubernetes**:
```
# helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
# kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
rabbitmq

**What happened**:
When deploy rabbitmq helm chart on k8s with istio enabled, return protocol undefined error as follow.

bash-4.2$ rabbitmqctl list_queues
```
Timeout: 60.0 seconds ...
Listing queues for vhost / ...
name    messages
test    0
** (Protocol.UndefinedError) protocol Enumerable not implemented for :error. This protocol is implemented for: Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/stream.ex:923: Stream.do_enum_transform/7
    (elixir) lib/enum.ex:1942: Enum.reduce_while/3
    (rabbitmqctl) lib/rabbitmq/cli/core/output.ex:45: RabbitMQ.CLI.Core.Output.print_output_0/3
    (rabbitmqctl) lib/rabbitmq/cli/core/output.ex:31: RabbitMQ.CLI.Core.Output.print_output/3
    (rabbitmqctl) lib/rabbitmqctl.ex:132: RabbitMQCtl.process_output/3
    (rabbitmqctl) lib/rabbitmqctl.ex:36: RabbitMQCtl.main/1
```
**What you expected to happen**:
Hope the queues can be listed out successfully.

**How to reproduce it** (as minimally and precisely as possible):
Deploy rabbitmq helm chart with envoy sidecar.

**Anything else we need to know**:

**Comment by haiyangu** [comment]
There is the analysis of this issue from rabbitmq support team:
https://groups.google.com/forum/#!topic/rabbitmq-users/KZeZcpj_EmA

Here is the service definition of internal service:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ template "rabbitmq.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: epmd
    port: 4369
    targetPort: epmd
  - name: dist
    port: {{ .Values.rabbitmq.amqpPort | add 20000 }}
    targetPort: dist
  selector:
    app: {{ template "rabbitmq.name" . }}
    release: "{{ .Release.Name }}"

```

**Comment by juan131** [comment]
Hi @haiyangu 

What version of the RabbitMQ chart are you using? The current templates uses to define the RabbitMQ services (both the `svc` and the `svc-headless`) are very different. See:

- https://github.com/helm/charts/blob/master/stable/rabbitmq/templates/svc-headless.yaml
- https://github.com/helm/charts/blob/master/stable/rabbitmq/templates/svc.yaml

What do you obtain when running the command below?

```bash
$ helm search stable/rabbitmq
```

Please note you can update the chart to the latest version by running the command: `$ helm repo update`
