### ISSUE TITLE
Kafka Charts: Pods keeps crashing

### ISSUE THREAD

**Issue by chethanuk** [helm/charts#13183]
**Which chart**:
incubator/kafka

**What happened**:
After installing the chart, 

Pods just crashing 
```
kafka-0                             2/3       Error                   6          10m
kafka-1                             2/3       CrashLoopBackOff        6          9m
kafka-2                             2/3       CrashLoopBackOff        5          8m
kafka-exporter-9d78768f7-45gz5      1/2       CrashLoopBackOff        6          10m
kafka-zookeeper-0                   0/2       Init:CrashLoopBackOff   6          10m
```

**What you expected to happen**:
Work properly, with External IP

**How to reproduce it** (as minimally and precisely as possible):
Make these [changes](https://github.com/helm/charts/tree/master/incubator/kafka#example-valuesyml-for-external-service-type-nodeport) in values.yml and install the chart

@rfvermut Please have a look at this issue, Thanks!.

**Comment by rfvermut** [comment]
Strange to see them ALL crash. Can you post the logs of, say `kafka-0` and `kafka-zookeeper-0` ?

**Comment by ChethanUK** [comment]
Where are the logs? What's the location?

```
cd /opt/kafka
bash: cd: /opt/kafka: No such file or directory
```

**Comment by ChethanUK** [comment]
In kafka-exporter the error is: 
```
kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
at main.NewExporter (kafka_exporter.go:211)
at main.main (kafka_exporter.go:481)
```

**Comment by rfvermut** [comment]
I'm worried about `kafka-zookeeper-0` most. It's a prerequisite for Kafka to start the cluster and it's failing at init container. Can you get Zookeeper's init container logs?

**Comment by ChethanUK** [comment]
> Can you get Zookeeper's init container logs?

Yes, Whats the Location? Can you give commands?

**Comment by ChethanUK** [comment]
Hey, any update?

```
kafka-0                             2/3     CrashLoopBackOff        50         24h
kafka-1                             2/3     CrashLoopBackOff        48         24h
kafka-2                             2/3     CrashLoopBackOff        426        24h
kafka-3                             2/3     CrashLoopBackOff        50         24h
kafka-exporter-9d78768f7-vnkwk      1/2     CrashLoopBackOff        37         24h
kafka-zookeeper-0                   0/2     Init:CrashLoopBackOff   38         24h
```

**Comment by rfvermut** [comment]
You have Istio running, who injects it's Init containters into other pods. `istio-init` is crashing, that's why Zookeeper cannot start, that's why Kafka cannot start.

Not a Kafka issue.

**Comment by ChethanUK** [comment]
Do I need to do something like `--set sidecarInjectorWebhook.enabled=false`

https://preliminary.istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#disabling-or-updating-the-webhook

**Comment by aryakushal** [comment]
Same issue i'm getting. Here are the logs

$ kubectl logs zookeeper-0

```
+ zkGenConfig.sh
Validating environment
ZK_REPLICAS=3
MY_ID=1
ZK_LOG_LEVEL=INFO
ZK_DATA_DIR=/var/lib/zookeeper/data
ZK_DATA_LOG_DIR=/var/lib/zookeeper/log
ZK_LOG_DIR=/var/log/zookeeper
ZK_CLIENT_PORT=2181
ZK_SERVER_PORT=2888
ZK_ELECTION_PORT=3888
ZK_TICK_TIME=2000
ZK_INIT_LIMIT=5
ZK_SYNC_LIMIT=10
ZK_MAX_CLIENT_CNXNS=60
ZK_MIN_SESSION_TIMEOUT=4000
ZK_MAX_SESSION_TIMEOUT=40000
ZK_HEAP_SIZE=2G
ZK_SNAP_RETAIN_COUNT=3
ZK_PURGE_INTERVAL=0
ENSEMBLE
server.1=zalando-zookeeper-0.zalando-zookeeper-headless.default.svc.cluster.local:2888:3888
server.2=zalando-zookeeper-1.zalando-zookeeper-headless.default.svc.cluster.local:2888:3888
server.3=zalando-zookeeper-2.zalando-zookeeper-headless.default.svc.cluster.local:2888:3888
Environment validation successful
Creating ZooKeeper configuration
Wrote ZooKeeper configuration file to /opt/zookeeper/conf/zoo.cfg
Creating ZooKeeper log4j configuration
Wrote log4j configuration to /opt/zookeeper/conf/log4j.properties
Creating ZooKeeper data directories and setting permissions
/usr/bin/zkGenConfig.sh: line 130: /var/lib/zookeeper/data/myid: Permission denied
Created ZooKeeper data directories and set permissions in /var/lib/zookeeper/data
Creating JVM configuration file
Wrote JVM configuration to /opt/zookeeper/conf/java.env
+ exec zkServer.sh start-foreground
ZooKeeper JMX enabled by default
ZooKeeper remote JMX Port set to 1099
ZooKeeper remote JMX authenticate set to false
ZooKeeper remote JMX ssl set to false
ZooKeeper remote JMX log4j set to true
Using config: /usr/bin/../etc/zookeeper/zoo.cfg
2019-06-04 09:39:07,643 [myid:] - INFO  [main:QuorumPeerConfig@134] - Reading configuration from: /usr/bin/../etc/zookeeper/zoo.cfg
2019-06-04 09:39:11,660 [myid:] - WARN  [main:QuorumPeer$QuorumServer@173] - Failed to resolve address: zalando-zookeeper-2.zalando-zookeeper-headless.default.svc.cluster.local
java.net.UnknownHostException: zalando-zookeeper-2.zalando-zookeeper-headless.default.svc.cluster.local: Name or service not known
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at java.net.InetAddress.getByName(InetAddress.java:1076)
        at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:166)
        at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.<init>(QuorumPeer.java:151)
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:238)
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:150)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:101)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:78)
2019-06-04 09:39:15,665 [myid:] - WARN  [main:QuorumPeer$QuorumServer@173] - Failed to resolve address: zalando-zookeeper-1.zalando-zookeeper-headless.default.svc.cluster.local
java.net.UnknownHostException: zalando-zookeeper-1.zalando-zookeeper-headless.default.svc.cluster.local: Name or service not known
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at java.net.InetAddress.getByName(InetAddress.java:1076)
        at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:166)
        at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.<init>(QuorumPeer.java:151)
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:238)
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:150)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:101)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:78)
2019-06-04 09:39:15,669 [myid:] - INFO  [main:QuorumPeer$QuorumServer@167] - Resolved hostname: zalando-zookeeper-0.zalando-zookeeper-headless.default.svc.cluster.local to address: zalando-zookeeper-0.zalando-zookeeper-headless.default.svc.cluster.local/10.233.65.128
2019-06-04 09:39:15,669 [myid:] - INFO  [main:QuorumPeerConfig@396] - Defaulting to majority quorums
2019-06-04 09:39:15,670 [myid:] - ERROR [main:QuorumPeerMain@85] - Invalid config, exiting abnormally
org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /usr/bin/../etc/zookeeper/zoo.cfg
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:154)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:101)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:78)
Caused by: java.lang.IllegalArgumentException: /var/lib/zookeeper/data/myid file is missing
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:406)
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:150)
        ... 2 more
Invalid config, exiting abnormally
```
