### ISSUE TITLE
[stable/jenkins] Sidecar Container crashloopbackoff

### ISSUE THREAD

**Issue by ricardompcarvalho** [helm/charts#13367]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

```
Traceback (most recent call last):
  File "/app/sidecar.py", line 190, in <module>
    main()
  File "/app/sidecar.py", line 185, in main
    ssh_port)
  File "/app/sidecar.py", line 123, in watchForChanges
    jenkinsReloadConfig(admin_private_key, admin_user, ssh_port, logger)
  File "/app/sidecar.py", line 22, in jenkinsReloadConfig
    ssh_client.connect('127.0.0.1', port=ssh_port, username=admin_user, pkey=private_key)
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 437, in connect
    passphrase,
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 749, in _auth
    raise saved_exception
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 649, in _auth
    self._transport.auth_publickey(username, pkey)
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1507, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/local/lib/python3.6/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
JENKINS

**What happened**:
I try to work with Auto-reload with non-Jenkins identities and the sidecar gives me an error.

**What you expected to happen**:
Sidecar container reloads configuration

**How to reproduce it** (as minimally and precisely as possible):
```
Master:
  AdminUser: saJenkinst02
  JCasC:
    enabled: true
    PluginVersion: latest
    SupportPluginVersion: latest
    ConfigScripts:
      samlconfiguration: |
       jenkins:
        securityRealm:
            saml:
                idpMetadataConfiguration:....
                usernameAttributeName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn"
                emailAttributeName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
                binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                displayNameAttributeName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
                groupsAttributeName: "http://schemas.xmlsoap.org/claims/Group"
                maximumAuthenticationLifetime: 86400
                usernameCaseConversion: "none"
                encryptionData:
                    forceSignRedirectBindingAuthnRequest: false
                    keystorePassword: "${SAML_KEYSTORE_PASSWORD}"
                    keystorePath: "/var/jenkins_home/jenkins_keystore_idp.jks"
                    privateKeyAlias: "idp"
                    privateKeyPassword: "${SAML_PRIVATE_KEY}"
      authorization: |
        jenkins:
            authorizationStrategy:
                projectMatrix:
                    grantedPermissions:
                        - "Overall/Administer:JENKINS_ADMIN"
                        - "Overall/Read:JENKINS_ACCESS"
                        - "Overall/Administer:saJenkinst02"
  Sidecars:
    configAutoReload:
```

Using this code result in the following errors in the side-car:

```
019-04-29 13:40:49 INFO     Starting config map collector
2019-04-29 13:40:49 INFO     label is: jenkins-test-jenkins-config
2019-04-29 13:40:49 INFO     targetFolder is: /var/jenkins_home/casc_configs
2019-04-29 13:40:49 INFO     Config for cluster api loaded...
2019-04-29 13:40:49 INFO     namespace is: default
2019-04-29 13:40:49 INFO     ssh_port is: 1044
2019-04-29 13:40:49 INFO     admin_user is: saJenkinst02
2019-04-29 13:40:49 INFO     Jenkins is contactable, continuing.
2019-04-29 13:40:49 INFO     Working on configmap default/jenkins-test-jenkins-config-samlconfiguration
2019-04-29 13:40:49 INFO     Working on configmap default/jenkins-test-jenkins-config-samlconfiguration
2019-04-29 13:40:49 INFO     Configmap with label found
2019-04-29 13:40:49 INFO     File in configmap samlconfiguration.yaml ADDED
Traceback (most recent call last):
  File "/app/sidecar.py", line 190, in <module>
    main()
  File "/app/sidecar.py", line 185, in main
    ssh_port)
  File "/app/sidecar.py", line 123, in watchForChanges
    jenkinsReloadConfig(admin_private_key, admin_user, ssh_port, logger)
  File "/app/sidecar.py", line 22, in jenkinsReloadConfig
    ssh_client.connect('127.0.0.1', port=ssh_port, username=admin_user, pkey=private_key)
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 437, in connect
    passphrase,
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 749, in _auth
    raise saved_exception
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 649, in _auth
    self._transport.auth_publickey(username, pkey)
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1507, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/local/lib/python3.6/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```

**Anything else we need to know**:

As it says below, I already configured it by change the .master.adminUser to a valid username and granted him overall/administer rights in Jenkins. 
I will also have to specify the password corresponding to the name that I put on the admin User?

Auto-reload with non-Jenkins identities
When enabling LDAP or another non-Jenkins identity source, the built-in admin account will no longer exist. Since the admin account is used by the sidecar to reload config, in order to use auto-reload, you must change the .master.adminUser to a valid username on your LDAP (or other) server. If you use the matrix-auth plugin, this user must also be granted Overall\Administer rights in Jenkins. Failure to do this will cause the sidecar container to fail to authenticate via SSH and enter a restart loop. You can enable LDAP using the example above and add a Config as Code block for matrix security that includes:

```
configScripts:
  matrix-auth: |
    jenkins:
      authorizationStrategy:
        projectMatrix:
          grantedPermissions:
          - "Overall/Administer:<AdminUser_LDAP_username>"
```
You can instead grant this permission via the UI. When this is done, you can set master.sidecars.configAutoReload.enabled: true and upon the next Helm upgrade, auto-reload will be successfully enabled.

**Comment by ricardompcarvalho** [comment]
@tomerleib

**Comment by tomerleib** [comment]
Hi,
In my case with Active Directory I've done the following to troubleshoot:

1. Removed AuthorizationStrategy to avoid any additional restrictions
2. Disabled sidecar
3. Attempted to create the chart and log in with the admin account `master.admin`

At this point I've figured out that one parameter in my configuration is causing me issues, after I could successfully log in with my domain user, I've enabled the sidecar and it worked.
So the best course of action would be to start without the sidecar and see if you actually were able to configure the authentication correctly before letting the sidecar run.

Also, I cannot tell from your code, but make sure that in your `values.yaml`, under plugins you do list the saml plugin:
```yaml
  installPlugins:
    - kubernetes:1.14.0
    - workflow-job:2.31
    - workflow-aggregator:2.6
    - credentials-binding:1.17
    - git:3.9.1
    - saml:1.1.2
```

**Comment by ricardompcarvalho** [comment]
@tomerleib thank you for answering, I already had this configuration of saml plugin done but thank you, did you have to set admin.password and admin.privatekey?

**Comment by tomerleib** [comment]
Only the `admin.user`.
Another option that I advise if you haven't done it already, create a new deployment without the plugin.
Manually, configure everything related to the SAML and once approved working, you can export the config-as-a-code yaml and use it to compare with your existing configurations.
