### ISSUE TITLE
[stable/prisma] unable to load Prisma config

### ISSUE THREAD

**Issue by brandondoran** [helm/charts#13530]
**Describe the bug**
When the Prisma pod starts up it is looking for a file at `/app/config.yml`, which does not exist, causing pod to go into a crash loop. `/app/config.yml` is hard coded for the `PRISMA_CONFIG_PATH` env var in the [deployment.yaml](https://github.com/helm/charts/blob/master/stable/prisma/templates/deployment.yaml#L47). My assumption is that Prisma attempts to load config from `PRISMA_CONFIG_PATH` if the env var is set, which probably overrides the `PRISMA_CONFIG` that comes from the ConfigMap.

I have not been able to find any documentation on `PRISMA_CONFIG_PATH` other than [this PR](https://github.com/prisma/prisma/pull/2520) to update docs that seems to have been closed without merging:

> Notice: you can use `PRISMA_CONFIG_PATH` environment variable to set the path to Prisma configuration file, that is valid yaml file with the same shape as `PRISMA_CONFIG`.
>
> This can be helpfully when want to build your own Docker image. 

**Version of Helm and Kubernetes**:
Helm: 2.13.0
Kubernetes: 1.11.7

**Which chart**:
stable/prisma

**What happened**:
Pod crash loops with the error:
```
Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: java.io.FileNotFoundException: /app/config.yml (No such file or directory)
	at scala.sys.package$.error(package.scala:26)
	at com.prisma.config.ConfigLoader$.load(ConfigLoader.scala:40)
	at com.prisma.local.PrismaLocalDependencies.<init>(PrismaLocalDependencies.scala:48)
	at com.prisma.local.PrismaLocalMain$.delayedEndpoint$com$prisma$local$PrismaLocalMain$1(PrismaLocalMain.scala:13)
	at com.prisma.local.PrismaLocalMain$delayedInit$body.apply(PrismaLocalMain.scala:8)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.prisma.local.PrismaLocalMain$.main(PrismaLocalMain.scala:8)
	at com.prisma.local.PrismaLocalMain.main(PrismaLocalMain.scala)
```

**What you expected to happen**:
The pod to run without errors.

**How to reproduce it** (as minimally and precisely as possible):
Create a local values.yaml based off https://github.com/helm/charts/blob/fa35e13e395c8d0d748f64d949bef7b5a93e1a6e/stable/prisma/values.yaml that provides custom settings, such as:

```yaml
image:
  repository: prismagraphql/prisma
  tag: 1.32

database:
  connector: mysql
  host: xxx
  port: 3306
  user: root
  password: xxx
  migrations: false

postgresql:
  enabled: false
```
```
helm install stable/prisma -f ./values.yaml -n prisma-demo
```

**Anything else we need to know**:
I've tried multiple versions of the prisma image with no luck.

**Comment by langleyd** [comment]
@brandondoran I saw this also, if you stick to using tags with `-heroku` suffixed(as in default values.yaml file) I don't see this. Not sure why it is needed, @giacomoguiulfo or @kanolato Could you shed light on that?

**Comment by fenos** [comment]
I'm seeing this too! Very annoying

**Comment by haysclark** [comment]
@giacomoguiulfo These _Prisma_ issues likely should be addressed, possibly re-opened. I hit this issue and wasted a bunch of time on it.

**Comment by giacomoguiulfo** [comment]
@haysclark the Prisma chart only works with images with the `-heroku` suffix. This is because of the bundled `envsubst` script that makes proper secret handling possible.

**Comment by EhsanSarshar** [comment]
I have a single replia set mongodb running locally. it's fine with no replica set but when I use it with replica it throws error
