### ISSUE TITLE
stable/jenkins connection timeout behind proxy with flags set

### ISSUE THREAD

**Issue by s1113950** [helm/charts#13559]
**Describe the bug**
I ran this command:
```
../helm install --name jenkins \
--set master.initContainerEnv[0].name=http_proxy,master.initContainerEnv[0].value=PROXYHERE \
--set master.initContainerEnv[1].name=https_proxy,master.initContainerEnv[1].value=PROXYHERE \ 
--set master.initContainerEnv[2].name=HTTP_PROXY,master.initContainerEnv[2].value=PROXYHERE \   
 --set master.initContainerEnv[3].name=HTTPS_PROXY,master.initContainerEnv[3].value=PROXYHERE \     
--set master.ContainerEnv[0].name=http_proxy,master.ContainerEnv[0].value=PROXYHERE \
 --set master.ContainerEnv[1].name=https_proxy,master.ContainerEnv[1].value=PROXYHERE \
--set master.ContainerEnv[2].name=HTTP_PROXY,master.ContainerEnv[2].value=PROXYHERE \
--set master.ContainerEnv[3].name=HTTPS_PROXY,master.ContainerEnv[3].value=PROXYHERE \  
--set master.javaOpts="-Dhttp.proxyHost=PROXYHERE -Dhttp.proxyPort=PORT -Dhttps.proxyHost=PROXYHERE -Dhttps.proxyPort=PORT" \
--set persistence.existingClaim=jenkins-pvc stable/jenkins
```
and got through installing things from the init container, but after jenkins said `jenkins is fully up and running` I got this error:

```
vagrant@ubuntu-xenial:~/charts$ kubectl logs -f jenkins-5f65975c7b-x6gj4
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
May 06, 2019 11:21:58 PM org.eclipse.jetty.util.log.Log initialized
INFO: Logging initialized @267ms to org.eclipse.jetty.util.log.JavaUtilLog
May 06, 2019 11:21:58 PM winstone.Logger logInternal
INFO: Beginning extraction from war file
May 06, 2019 11:21:58 PM org.eclipse.jetty.server.handler.ContextHandler setContextPath
WARNING: Empty contextPath
May 06, 2019 11:21:58 PM org.eclipse.jetty.server.Server doStart
INFO: jetty-9.4.z-SNAPSHOT; built: 2018-08-30T13:59:14.071Z; git: 27208684755d94a92186989f695db2d7b21ebc51; jvm 1.8.0_212-8u212-b01-1~deb9u1-b01
May 06, 2019 11:21:58 PM org.eclipse.jetty.webapp.StandardDescriptorProcessor visitServlet
INFO: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
May 06, 2019 11:21:58 PM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
INFO: DefaultSessionIdManager workerName=node0
May 06, 2019 11:21:58 PM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
INFO: No SessionScavenger set, using defaults
May 06, 2019 11:21:58 PM org.eclipse.jetty.server.session.HouseKeeper startScavenging
INFO: node0 Scavenging every 660000ms
Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
May 06, 2019 11:21:59 PM org.eclipse.jetty.server.handler.ContextHandler doStart
INFO: Started w.@6e2aa843{Jenkins v2.164.2,/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
May 06, 2019 11:21:59 PM org.eclipse.jetty.server.AbstractConnector doStart
INFO: Started ServerConnector@79b14515{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
May 06, 2019 11:21:59 PM org.eclipse.jetty.server.Server doStart
INFO: Started @1056ms
May 06, 2019 11:21:59 PM winstone.Logger logInternal
INFO: Winstone Servlet Engine v4.0 running: controlPort=disabled
May 06, 2019 11:22:00 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
May 06, 2019 11:22:00 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
May 06, 2019 11:22:03 PM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
May 06, 2019 11:22:03 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
May 06, 2019 11:22:05 PM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
May 06, 2019 11:22:05 PM jenkins.model.Jenkins setBuildsAndWorkspacesDir
INFO: Using non default workspaces directories: ${JENKINS_HOME}/workspace/${ITEM_FULLNAME}.
May 06, 2019 11:22:05 PM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
May 06, 2019 11:22:05 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Started Download metadata
May 06, 2019 11:22:05 PM hudson.util.Retrier start
INFO: Attempt #1 to do the action check updates server
May 06, 2019 11:22:05 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@4e578c36: display name [Root WebApplicationContext]; startup date [Mon May 06 23
:22:05 UTC 2019]; root of context hierarchy
May 06, 2019 11:22:05 PM org.springframework.context.support.AbstractApplicationContext obtainFreshBeanFactory
INFO: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@4e578c36]: org.springframework.beans.factory.support.
DefaultListableBeanFactory@388210a8
May 06, 2019 11:22:05 PM org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons
INFO: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@388210a8: defining beans [filter,legacy]; root of factory
hierarchy
May 06, 2019 11:22:06 PM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization
May 06, 2019 11:22:06 PM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
May 06, 2019 11:22:25 PM hudson.util.Retrier start
INFO: The attempt #1 to do the action check updates server failed with an allowed exception:
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:200)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1175)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at hudson.model.DownloadService.loadJSON(DownloadService.java:167)
        at hudson.model.UpdateSite.updateDirectlyNow(UpdateSite.java:188)
        at hudson.PluginManager.checkUpdatesServer(PluginManager.java:1748)
        at hudson.util.Retrier.start(Retrier.java:62)
        at hudson.PluginManager.doCheckUpdatesServer(PluginManager.java:1719)
        at jenkins.model.DownloadSettings$DailyCheck.execute(DownloadSettings.java:130)
        at hudson.model.AsyncPeriodicWork$1.run(AsyncPeriodicWork.java:101)
        at java.lang.Thread.run(Thread.java:748)
May 06, 2019 11:22:25 PM hudson.util.Retrier start
INFO: Calling the listener of the allowed exception 'connect timed out' at the attempt #1 to do the action check updates server
May 06, 2019 11:22:25 PM hudson.util.Retrier start
INFO: Attempted the action check updates server for 1 time(s) with no success
May 06, 2019 11:22:25 PM hudson.PluginManager doCheckUpdatesServer
SEVERE: Error checking update sites for 1 attempt(s). Last exception was: SocketTimeoutException: connect timed out
May 06, 2019 11:22:25 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished Download metadata. 20,562 ms
```

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/jenkins

**What happened**:
socket timeout error despite proxies set

**What you expected to happen**:
jenkins fully up and running

**How to reproduce it** (as minimally and precisely as possible):
Run the command above behind a corp proxy

**Anything else we need to know**:
I'm running this on a vagrant VM on my mac, on a corp VPN

**Comment by s1113950** [comment]
🤦‍♂ I left the protocol on the `javaOpts` host values. Everything works now
