### ISSUE TITLE
stable/mongodb authentication issue with replicaset set true

### ISSUE THREAD

**Issue by polganesh** [helm/charts#13567]
Hi,
**Is it a request for help ?**
Yes

**what I am trying to do?**
I am trying to use stable/mongodb as _sub chart_ in my main chart with replica set enabled

**steps performed**   

- added mongodb as a sub chart in chart folder
-  mention dependency of this chart in requirements.yaml

```
dependencies:
- name: mongodb
  version: "5.17.0"
  repository: "file://charts/mongodb"
```

- override sub chart values in main chart

```
mongodb:
 usePassword: true
 existingSecret: skeleton
  mongodbUsername: skeleton
  mongodbDatabase: skeleton
  replicaSet:
    ## Whether to create a MongoDB replica set for high availability or not
    enabled: true
    useHostnames: true
    name: rs0
    replicas:
      secondary: 1
      arbiter: 1
```
**- define secret for this**
in secret for skeleton
```
apiVersion: v1
kind: Secret
metadata:
  name: skeleton
type: Opaque
data:
  # mongo ha---
  mongodb-root-password: <64-bit-encoded-root-password> 
  mongodb-replica-set-key: <64-bit-encoded-Key> 
  mongodb-password: <64-bit-encoded-password>
```
**- in deployment.yaml provided headless service url  mongodb url to connect to this**

from application hosted inside same k8s cluster

`mongodb://<mongodbUsername-value-define-in-value.yaml>:<mongodb-password-value-present-in-secret>@skeleton-mongodb-headless:27017/skeleton?authSource=admin&replicaSet=rs0
`

- **error i am getting**

```
[1;30m2019-05-07 05:06:16,085[0;39m => [34mINFO [0;39m [[32mmain[0;39m] [33mcom.mongodb.diagnostics.logging.SLF4JLogger[0;39m: Cluster created with settings {hosts=[skeleton-mongodb-headless:27017], mode=MULTIPLE, requiredClusterType=REPLICA_SET, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500, requiredReplicaSetName='rs0'}
[1;30m2019-05-07 05:06:16,085[0;39m => [34mINFO [0;39m [[32mmain[0;39m] [33mcom.mongodb.diagnostics.logging.SLF4JLogger[0;39m: Adding discovered server skeleton-mongodb-headless:27017 to client view of cluster
[1;30m2019-05-07 05:06:16,175[0;39m => [34mINFO [0;39m [[32mmain[0;39m] [33mcom.mongodb.diagnostics.logging.SLF4JLogger[0;39m: No server chosen by com.mongodb.Mongo$4@359ff4d9 from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=skeleton-mongodb-headless:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
[1;30m2019-05-07 05:06:16,182[0;39m => [34mINFO [0;39m [[32mcluster-ClusterId{value='5cd11248b2cfc400017b5805', description='null'}-skeleton-mongodb-headless:27017[0;39m] [33mcom.mongodb.diagnostics.logging.SLF4JLogger[0;39m: Exception in monitor thread while connecting to server skeleton-mongodb-headless:27017
com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=null, userName='skeleton', source='admin', password=<hidden>, mechanismProperties={}}
	at com.mongodb.connection.SaslAuthenticator.wrapException(SaslAuthenticator.java:162)
	at com.mongodb.connection.SaslAuthenticator.access$200(SaslAuthenticator.java:39)
	at com.mongodb.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:68)
	at com.mongodb.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:46)
	at com.mongodb.connection.SaslAuthenticator.doAsSubject(SaslAuthenticator.java:168)
	at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:46)




```

**Comment by juan131** [comment]
Hi @polganesh 

Sorry for the late response. I was able to reproduce the issue using the lates version:

- My 'values.yaml':

```yaml
usePassword: true
existingSecret: skeleton
mongodbUsername: skeleton
mongodbDatabase: skeleton
replicaSet:
  enabled: true
  useHostnames: true
  name: rs0
  replicas:
    secondary: 1
    arbitrer: 1
```

- My `secrets.yaml`:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: skeleton
type: Opaque
data:
  ## echo -n "my-root-password" | base64
  mongodb-root-password: bXktcm9vdC1wYXNzd29yZA==
  ## echo -n "my-replica-set-key" | base64
  mongodb-replica-set-key: bXktcmVwbGljYS1zZXQta2V5
  ## echo -n "my-mongo-pass" | base64
  mongodb-password: bXktbW9uZ28tcGFzcw==
```

- Commands used:

``` bash
$ k create -f secrets.yaml
$ helm install --name mongodb stable/mongodb -f values.yaml
$ k logs mongodb-primary-0
mongodb INFO  ==> Writing keyfile for replica set authentication
mongodb TRACE [configurePermissions] File to chmod: /opt/bitnami/mongodb/conf/keyfile
mongodb INFO  ==> Configuring MongoDB replica set
mongodb INFO  ==> Enabling MongoDB replica set name
mongodb TRACE [runProgram] Executing: null /opt/bitnami/mongodb/bin/mongod --config /opt/bitnami/mongodb/conf/mongodb.conf
```

It get stucks there. I'll share this bug with the team so we can investigate what's going on. Thanks for reporting it
