### ISSUE TITLE
redis-ha chart

### ISSUE THREAD

**Issue by hitesh1907nayyar** [helm/charts#14133]
**Describe the bug**
Bug
**Version of Helm and Kubernetes**:
v2.14

**Which chart**:
redis-ha

**What happened**:
I have installed redis-ha helm chart and pointed the service to my application. But when i click on the button of the application which calls the post request to redis to insert data i get the below a redis exception in the last line:
29.169 Safari/537.36" "27.56.137.1"
[2019-05-25 14:21:31,068] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./main.py", line 66, in index
    r.incr(vote,1)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1011, in incr
    return self.execute_command('INCRBY', name, amount)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 629, in read_response
    raise response
**redis.exceptions.ReadOnlyError: You can't write against a read only replica.**

I checked on various blogs and found that this can be connected to haproxy. But in that also i am getting the error.

helm install --name proxy incubator/haproxy-redis --set redis.releaseName=redis --set redis.serviceName=redis-redis-ha --set redis.replicaCount=3 --setredis.namespace=default
**Error: failed to download "incubator/haproxy-redis" (hint: running `helm repo update` may help)**

Is this the right approch to solve the redis error ? And what can i do to resolve this since haproxy i dont think is a vaiable option. I have deployed kubernetes cluster on azure.

**What you expected to happen**:
Installed redis with ha

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by DandyDeveloper** [comment]
@hitesh1907nayyar You're going about your Python side incorrectly.

Youre client needs to ask the sentinel who is the master, and from that connect to the Redis server. This is behaving as I'd expect, as the service is just load balancing between the 3 redis servers. 

Regarding the HA / Proxy. I'm investigating, but the problem is that they clearly did not make Sentinel with a containerized solution in mind.
