### ISSUE TITLE
Redis Chart

### ISSUE THREAD

**Issue by hitesh1907nayyar** [helm/charts#14135]
**Describe the bug**
Bug
**Version of Helm and Kubernetes**:
v2.11

**Which chart**:
Redis Chart

**What happened**:
I have installed redis chart on kubernetes cluster using the below command:

helm install --name redis stable/redis --set password=Redis@12345  --set cluster.enabled=true --set sentinel.enabled=true 

I have connected this to a voting app where a person selects a vote. It captures voting count details for sometime and then sometimes i start to get Redis exceptionwhen person click on giving the vote. Basically a POST call is given which updates the entry . Sometimes i am getting the below error. My application service is pointing to redis-headless service 

2019-05-26 02:27:13,575] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./main.py", line 66, in index
    r.incr(vote,1)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1011, in incr
    return self.execute_command('INCRBY', name, amount)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 629, in read_response
    raise response
**redis.exceptions.ReadOnlyError: You can't write against a read only replica.**

**What you expected to happen**:
Ideally redis should have run flawlessly

**How to reproduce it** (as minimally and precisely as possible):
Installing a cluster enabled redis 

**Anything else we need to know**:

**Comment by avirtual** [comment]
You are likely connecting to the default redis port and you need to connect to the sentinel port:

> Redis service: Exposes port 6379 for Redis read-only operations and port 26379 for accesing Redis Sentinel.
> 
> For read-only operations, access the service using port 6379. For write operations, it's necessary to access the Redis Sentinel cluster and query the current master using the command below (using redis-cli or similar:
