### ISSUE TITLE
[incubator/kafka] Failed to acquire lock on file .lock in /opt/kafka/data/logs

### ISSUE THREAD

**Issue by krichter722** [helm/charts#14132]
**Describe the bug**
Pods created by the chart seem to store their running state on the persistent volume. If the shutdown routine clearing this state fails a lock file remains which prevents the following pods to start due to

```
[2019-05-25 09:11:33,980] ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: Failed to acquire lock on file .lock in /opt/kafka/data/logs. A Kafka instance in another process or thread is using this directory.
    at kafka.log.LogManager$$anonfun$lockLogDirs$1.apply(LogManager.scala:240)
    at kafka.log.LogManager$$anonfun$lockLogDirs$1.apply(LogManager.scala:236)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
    at kafka.log.LogManager.lockLogDirs(LogManager.scala:236)
    at kafka.log.LogManager.&lt;init&gt;(LogManager.scala:97)
    at kafka.log.LogManager$.apply(LogManager.scala:953)
    at kafka.server.KafkaServer.startup(KafkaServer.scala:237)
    at io.confluent.support.metrics.SupportedServerStartable.startup(SupportedServerStartable.java:114)
    at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:66)
```

Kubernetes pods are expected to be deleted or evicted often and it's likely that a failure to remove the lock file from the pv occurs.

I don't see a reason why the state should be stored in the first place since Kubernetes is aware of the running state.

**Version of Helm and Kubernetes**:
```
> linux-amd64/helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

together with microk8s 1.14.2 (608) on Ubuntu 19.10.

**Which chart**:
`incubator/kafka`

**What happened**:
After working well for one week, one of three Kafka pods fails to start 100% of times due to the above error.

**What you expected to happen**:
The pod should start under all circumstances in order to fulfill its task as Kubernetes pod.

**How to reproduce it** (as minimally and precisely as possible):
A reproducer is not easy to create, however the problem might be approached from a theoretical perspective without reproducing it.

**Anything else we need to know**:
I checked whether this is a bug or user error in https://stackoverflow.com/questions/56303672/how-to-handle-a-persisted-state-dependent-pod-start-failure-in-kubernetes/56311142#56311142. At least one answer there already contains a suggest for solution.

**Comment by antonvlassov** [comment]
krichter722, I got extactly the same problem here (microk8s).
Has the solution proposed in https://stackoverflow.com/questions/56303672/how-to-handle-a-persisted-state-dependent-pod-start-failure-in-kubernetes/56311142#56311142 worked for you?
Thanks

**Comment by krichter722** [comment]
@antonvlassov I didn't have the time to try it yet. Please try it and open a PR with this change.
