### ISSUE TITLE
stable/airflow airflow webserver generates python error with libpq.so.5

### ISSUE THREAD

**Issue by ybannay** [helm/charts#14847]
**Describe the bug**
webserver generates python error with libpq.so.5

**Version of Helm and Kubernetes**:
helm: v2.9.1
kubernetes server: v1.10.13
kubernetes cliente: v1.14.1

**Which chart**:
airflow stable chart

**What happened**:
Trying to install the helm chart with the following command: helm install --namespace "airflow" --name "airflow" stable/airflow

I got the following error on webserver

```
executing webserver...
[2019-06-16 20:47:03,664] {settings.py:174} INFO - settings.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800, pid=1
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 21, in <module>
    from airflow import configuration
  File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 36, in <module>
    from airflow import settings, configuration as conf
  File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 266, in <module>
    configure_orm()
  File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 188, in configure_orm
    engine = create_engine(SQL_ALCHEMY_CONN, **engine_args)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 443, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 599, in dbapi
    import psycopg2
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: libpq.so.5: cannot open shared object file: No such file or directory
```

**What you expected to happen**:
To be able to access the webserver 

**How to reproduce it** (as minimally and precisely as possible):
Just execute the command to install the chart: helm install --namespace "airflow" --name "airflow" stable/airflow and go to the logs of webserver pod.

**Comment by stevenmanton** [comment]
This is a [known issue](https://github.com/puckel/docker-airflow/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+libpq) with the puckel image. I solved it by installing `psycopg2-binary` with `pip`. For example, I use `docker build ... PYTHON_DEPS="psycopg2-binary redis>=3.2.0"`

**Comment by burakince** [comment]
I changed puckel/docker-airflow image tag to 1.10.3 and it started to work fine for me.

**Comment by sryabkov** [comment]
The `pucker/docker-airflow:1.10.2` image was rebuilt around June 6th, which caused `pip install` to pull newer versions of some packages, which are not compatible with airflow 1.10.2

If you are not ready to upgrade to airflow 1.10.3 yet, one solution for this problem is to reference the original  `pucker/docker-airflow:1.10.2`  image, the one built in January 2019, by referencing sha256 of that image:

```
FROM puckel/docker-airflow@sha256:82654d8b384be9fe79cca5d41a599cf1d2504c7e57b3d97cb577b978dcf84779
```

See puckel/docker-airflow#379 for more info
