### ISSUE TITLE
[stable/sentry] Fresh install results in an Index error

### ISSUE THREAD

**Issue by iluuu1994** [helm/charts#15296]
**Describe the bug**

This is how I installed Sentry:

```bash
helm install securityContext.enabled=true,securityContext.runAsUser=0,securityContext.fsGroup=2000 --timeout=3600 stable/sentry
```

There are various issues. Without the `securityContext` params the Redis pods would keep failing. With these params the Redis pods work.

Second issue is that the `db-init` job keeps running into timeout issues. It's recreated automatically and keeps going from where it left off. So I guess that's ok.

Third issue is that when I open the website I get the following error:

<img width="840" alt="image" src="https://user-images.githubusercontent.com/1752683/60769270-e14a6600-a0cd-11e9-834b-79db745b5de2.png">

```bash
kubectl logs ...-sentry-worker-...
```

```log
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 225, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 193, in handle
    return super(AuthLoginView, self).handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 238, in handle
    return super(BaseView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 211, in get
    org = Organization.get_default()
  File "/usr/local/lib/python2.7/site-packages/sentry/models/organization.py", line 164, in get_default
    )[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
13:36:56 [ERROR] django.request: Internal Server Error: /auth/login/ (request_id=u'...' status_code=500 request=<WSGIRequest: GET u'/auth/login/'>)
```

This issue was already reported on https://github.com/getsentry/onpremise/issues/200 but they told me to report it here. 

**Version of Helm and Kubernetes**:

```bash
kubectl version
```

```bash
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

```bash
helm version
```

```bash
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

Thanks!

**Comment by Timost** [comment]
Hi @iluuu1994,
I've come accross the same issue as you. For me this happened because something went wrong in the post-install hook that runs `sentry upgrade --noinput`, and the database ended up being corrupted.

I use an external postgres database and the db user did not have enough rights to install the `citext` postgres extension. After installing the extension manually in the db, wiping the database and rerunning `sentry upgrade --noinput` the problem was resolved for me an I was able to proceed.

**Comment by iluuu1994** [comment]
Hi @Timost!

Thanks for your response! It seems the `citext` was already created in my case but I think it's very likely the database is corrupt in some other way. Running `sentry upgrade --noinput` lreads to the following output:

> 10:18:18 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
> 10:18:27 [INFO] sentry.plugins.github: apps-not-configured
> Syncing...
> Creating tables ...
> Installing custom SQL ...
> Installing indexes ...
> Installed 0 object(s) from 0 fixture(s)
> Migrating...
> Killed

That's probably not normal, right?

**Comment by Timost** [comment]
Indeed that doesn't look normal. I've lost the output of the command when my the db was corrupted, but what you pasted does ring a bell. in my case deleting all the tables in the db and rerunning the `sentry upgrade --noinput` solved the issue.

**Comment by iluuu1994** [comment]
Tried your suggestion and recreated the entire database. Unfortunately, the output is almost the same:

> 11:11:34 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
> 11:11:43 [INFO] sentry.plugins.github: apps-not-configured
> Syncing...
> Creating tables ...
> Creating table django_admin_log
> Creating table auth_permission
> Creating table auth_group_permissions
> Creating table auth_group
> Creating table django_content_type
> Creating table django_session
> Creating table django_site
> Creating table south_migrationhistory
> Installing custom SQL ...
> Installing indexes ...
> Installed 0 object(s) from 0 fixture(s)
> Migrating...
> Killed

**Comment by Timost** [comment]
Hum and you don't get any stacktrace or anything ? On which pod do you run the `upgrade command` ?

**Comment by iluuu1994** [comment]
[This was the solution](https://github.com/getsentry/sentry/issues/8862#issuecomment-400807159). This is most likely a Sentry issue and not something in the chart. Anyways, thanks @Timost!

**Comment by BYK** [comment]
I'd guess this is most likely an OOM-kill of the migration process as it needs ~3GB of RAM. @okgolove any way tho check the RAM available for that process during setup to avoid this?

**Comment by okgolove** [comment]
@BYK 
We can create an environment variable which references to limit memory spec.

**Comment by BYK** [comment]
@okgolove sounds good to me. I use this script: https://github.com/getsentry/onpremise/blob/master/install.sh#L6 which has the minimum RAM as a variable.

I think, for now, we can set it independently but in the future, it'd be great if there was a way to keep these in sync.

**Comment by okgolove** [comment]
@BYK you want me to add something like this to the entrypoint?
https://github.com/getsentry/onpremise/blob/master/install.sh#L40-L43

**Comment by BYK** [comment]
@okgolove - if there's an elegant way, that would be nice (at least a warning). I don't really know how Helm works tho so I trust whatever you think is best.

**Comment by okgolove** [comment]
@BYK I'd suggest do the next two things:
- add a default request/limit 3gb for sentry-web
- add to [helm notes] https://github.com/helm/helm/blob/master/docs/chart_template_guide/notes_files.md) the warning if request/limit is lower than 3gb (was setup up manually, for example).

**Comment by iluuu1994** [comment]
I've tried installing Sentry with the following values:

```yaml
web:
  resources:
    limits:
      memory: 3000Mi
cron:
  resources:
    limits:
      memory: 3000Mi
worker:
  resources:
    limits:
      memory: 3000Mi
securityContext:
  enabled: true
  runAsUser: 0
  fsGroup: 2000
```

This was likely overkill but I just wanted to make sure it doesn't crash for the same reason again. Unfortunately, the db-init still kept crashing but for a different reason:

First one:

```
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 35, in inner
    configure()
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 125, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 156, in configure
    skip_service_validation=skip_service_validation
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 329, in initialize_app
    setup_services(validate=not skip_service_validation)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 352, in setup_services
    service.validate()
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/services.py", line 91, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python2.7/site-packages/sentry/buffer/redis.py", line 73, in validate
    raise InvalidConfiguration(six.text_type(e))
sentry.exceptions.InvalidConfiguration: Error 110 connecting to sentry-redis-master:6379. Connection timed out.
```

Second one:

```
 > sentry:0421_auto__del_field_identityprovider_organization_id__del_unique_identityp
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/metrics.py", line 67, in worker
    tsdb.incr(tsdb.models.internal, full_key, count=amount)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/services.py", line 91, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 214, in incr
    self.incr_multi([(model, key)], timestamp, count, environment_id)
  File "/usr/local/lib/python2.7/site-packages/sentry/tsdb/redis.py", line 242, in incr_multi
    self.calculate_expiry(rollup, max_values, timestamp),
  File "/usr/local/lib/python2.7/site-packages/rb/clients.py", line 625, in __exit__
    self.mapping_client.join(timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/rb/clients.py", line 413, in join
    command_buffer.wait_for_responses(self)
  File "/usr/local/lib/python2.7/site-packages/rb/clients.py", line 226, in wait_for_responses
    self.connection, command_name, **options)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 357, in read_response
    (e.args,))
ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
02:31:33 [ERROR] sentry.errors: Unable to incr internal metric
```

Third one:

```
 > sentry:0337_fix_out_of_order_migrations
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 75, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 30, in _upgrade
    ignore_ghost_migrations=True,
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 125, in handle_noargs
    management.call_command('south_migrate', **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/south/management/commands/south_migrate.py", line 105, in handle
    ignore_ghosts=ignore_ghosts,
  File "/usr/local/lib/python2.7/site-packages/south/migration/__init__.py", line 231, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 291, in migrate_many
    result = self.migrate(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 132, in migrate
    result = self.run(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 241, in run
    return super(Forwards, self).run(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 83, in run_migration
    south.db.db.start_transaction()
  File "/usr/local/lib/python2.7/site-packages/south/db/generic.py", line 1023, in start_transaction
    transaction.enter_transaction_management(using=self.db_alias)
  File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 70, in enter_transaction_management
    get_connection(using).enter_transaction_management(managed, forced)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 296, in enter_transaction_management
    self.set_autocommit(not managed)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 340, in set_autocommit
    self._set_autocommit(autocommit)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 158, in _set_autocommit
    self.connection.set_isolation_level(level)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 152, in _set_autocommit
    self.connection.autocommit = autocommit
django.db.utils.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

It does eventually complete but Sentry still displays it as `PENDING_INSTALL`. The projects have not been created so [this workaround](https://github.com/getsentry/sentry/issues/8862#issuecomment-400807159) is still necessary.

**Comment by okgolove** [comment]
@iluuu1994 I'm pretty sure you should've set up a resource section for a hook job.
https://github.com/helm/charts/blob/master/stable/sentry/templates/hooks/db-init.job.yaml

**Comment by iluuu1994** [comment]
@okgolove Ok I see. I can try that. But the errors don't seem to be related to the memory limit.

**Comment by BYK** [comment]
@iluuu1994 - the first two ones look like Redis connection/availability issues. The last one seems like a DB crash so maybe the system was starved of I/O or CPU?

**Comment by iluuu1994** [comment]
@BYK It's a completely new Kubernetes cluster hosted on DigitalOcean with two nodes, 4GB of RAM and 2 vCPUs per node. The only things installed are Helm and Ingress. It's not a lot but it should definitely be enough to run one application.

**Comment by BYK** [comment]
@iluuu1994 yeah, that looks like more than enough. That said the initial migration can be intense (we're working on making it better). Anyway, just wanted to point out the Redis issue, not sure about the root cause.
