### ISSUE TITLE
[stable/spinnaker] Halyard's tomcat java server won't use internal root CA

### ISSUE THREAD

**Issue by rumstead** [helm/charts#15404]
**Describe the bug**

I am sitting behind a corporate proxy and we use an internal root CA. 

I was able to get the proxy working and hitting our internal docker registries fairly easily. 

I have read all the github issues on spinnaker and spinnaker's chart. Ones regarding installing without internet, behind proxies, etc. None of which were able to help. 

Halyard pod that runs the tomcat java server fails to use an internal root CA. I am not sure if I am testing against the correct URLs but pretty sure I am. I can update the certs in the image and curl will work fine. However, the tomcat server is still failing to get the BOMs and profiles.

**Version of Helm and Kubernetes**:
Docker desktop for macOS.
```
$ helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/spinnaker

**What happened**:
halyard install pod log:
```
+ Get current deployment
  Success
+ Get features
  Success
+ Edit features
  Success
+ Successfully updated features.
+ hal --daemon-endpoint http://spin-spinnaker-halyard:8064 deploy apply --no-validate
+ Get current deployment
  Success
- Prep deployment
  Failure
Problems in Global:
! ERROR Unable to retrieve the Spinnaker bill of materials for
  version "1.12.5": sun.security.validator.ValidatorException: PKIX path building
  failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to
  find valid certification path to requested target
```
halyard tomcat log:
```
com.netflix.spinnaker.halyard.core.error.v1.HalException: Unable to retrieve the Spinnaker bill of materials for version "1.12.5": sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.netflix.spinnaker.halyard.config.services.v1.VersionsService.getBillOfMaterials(VersionsService.java:77) ~[halyard-config-1.20.2-20190520111848.jar:1.20.2-20190520111848]
	at com.netflix.spinnaker.halyard.deploy.services.v1.ArtifactService.getBillOfMaterials(ArtifactService.java:71) ~[halyard-deploy-1.20.2-20190520111848.jar:1.20.2-20190520111848]
	at com.netflix.spinnaker.halyard.deploy.services.v1.DeployService.getDeploymentDetails(DeployService.java:338) ~[halyard-deploy-1.20.2-20190520111848.jar:1.20.2-20190520111848]
	at com.netflix.spinnaker.halyard.deploy.services.v1.DeployService.prep(DeployService.java:207) ~[halyard-deploy-1.20.2-20190520111848.jar:1.20.2-20190520111848]
	at com.netflix.spinnaker.halyard.controllers.v1.DeploymentController.lambda$prep$12(DeploymentController.java:187) ~[halyard-web-1.20.2-20190520111848.jar:1.20.2-20190520111848]
	at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:127) ~[halyard-core-1.20.2-20190520111848.jar:1.20.2-20190520111848]
	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48) ~[halyard-core-1.20.2-20190520111848.jar:1.20.2-20190520111848]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
```

The ```hal deploy apply --debug``` logs aren't helpful.

**What you expected to happen**:
BOMs and profiles get downloaded and "installed" normally. 

**How to reproduce it** (as minimally and precisely as possible):
Not sure.

**Anything else we need to know**:
Curl works fine. Tried wrapping the halyward image that manually adds the certs.

```
FROM gcr.io/spinnaker-marketplace/halyard:1.20.2

ARG CERT_DIR=/usr/local/share/ca-certificates/
COPY ./my_certs/ $CERT_DIR

USER root
RUN update-ca-certificates --fresh
```
I know that update-ca-certificates has the java plugin that updates the java certs as well but as a sanity check...

```
FROM gcr.io/spinnaker-marketplace/halyard:1.20.2

ARG CERT_DIR=/usr/local/share/ca-certificates/
COPY ./my_certs/ $CERT_DIR

USER root
RUN update-ca-certificates --fresh
RUN openssl x509 -in $CERT_DIR/test_ca.pem -outform der -out /tmp/test_ca.der && openssl x509 -in $CERT_DIR/test_ca2.pem -outform der -out /tmp/test_ca2.der
RUN keytool -importcert -noprompt -alias test -keystore $JAVA_HOME/jre/lib/security/cacerts -file /tmp/test_ca.der  -storepass changeit && keytool -importcert -noprompt -alias test2 -keystore $JAVA_HOME/jre/lib/security/cacerts -file /tmp/test_ca2.der -storepass changeit
```

Curl works fine...
```
workdir# curl https://storage.googleapis.com/halconfig | grep -o "bom/1.12.5"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  251k  100  251k    0     0  15822      0  0:00:16  0:00:16 --:--:-- 54302
bom/1.12.5

workdir# curl https://storage.googleapis.com/halconfig/bom/1.12.5.yml | head -n 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1600  100  1600    0     0     98      0  0:00:16  0:00:16 --:--:--   344
artifactSources:
  debianRepository: https://dl.bintray.com/spinnaker-releases/debians
```

If I wanted to install everything manually. Ie, I could run a set of curl commands to install the bom, profiles, etc the documentation for it is sparse. Are any resources that can help me get spinnaker "spin up" for doing some POCs? 

https://www.spinnaker.io/guides/operator/custom-boms/  I guess is my best bet?

**Comment by rumstead** [comment]
I was able to write a python script that takes a bom and curls all the needed resources down. I was able to get the install pod to complete. Doesn't really solve the problem but... it worked.
