### ISSUE TITLE
On NFS Share /gitlab-data/ permissions seem to be wrong...

### ISSUE THREAD

**Issue by kratan** [helm/charts#1608]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
2.5.1

**Which chart**:
latest, version 9.4.3 of gitlab, tried 9.4.1, but does not work either...

**What happened**:

nfs pvc of registry, etc working well, but data gives me:
 ```
Preparing services...
Starting services...
Configuring GitLab package...
/opt/gitlab/embedded/bin/runsvdir-start: line 37: /proc/sys/fs/file-max: Read-only file system
Configuring GitLab...
================================================================================
Error executing action `run` on resource 'ruby_block[directory resource: /gitlab-data/ssh]'
================================================================================
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of stat --printf='%U' $(readlink -f /gitlab-data/ssh) ----
STDOUT: 
STDERR: stat: missing operand
Try 'stat --help' for more information.
---- End output of stat --printf='%U' $(readlink -f /gitlab-data/ssh) ----
Ran stat --printf='%U' $(readlink -f /gitlab-data/ssh) returned 1
Cookbook Trace:
---------------
/opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/storage_directory_helper.rb:35:in `run_command'
/opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/storage_directory_helper.rb:67:in `get_owner'
/opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/storage_directory_helper.rb:48:in `ensure_permissions_set'
/opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/definitions/storage_directory.rb:32:in `block (3 levels) in from_file'
Resource Declaration:
---------------------
# In /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/definitions/storage_directory.rb
 26:   ruby_block "directory resource: #{params[:path]}" do
 27:     block do
 28:       # Ensure the directory exists
 29:       storage_helper.ensure_directory_exists(params[:path])
 30: 
 31:       # Ensure the permissions are set
 32:       storage_helper.ensure_permissions_set(params[:path])
 33: 
 34:       # Error out if we have not achieved the target permissions
 35:       storage_helper.validate!(params[:path])
 36:     end
 37:     not_if { storage_helper.validate(params[:path]) }
 38:   end
 39: end
Compiled Resource:
------------------
# Declared in /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/definitions/storage_directory.rb:26:in `block in from_file' 
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
start gitlab on a nfs pvc. Permission settings seem to be wrong. if i set gitlab-data to persistence to false, all is fine....but i want to have the persistence feature of my gitlab-data. as said, with registry, etc all is fine...

**Anything else we need to know**:

**Comment by natebc** [comment]
I'm running into the same issue with this and the included other pods. All fail on NFS with permission errors  while both an internal registry and cockroachdb pods using PVCs backed by NFS PVs are fine.

**Comment by mattfarina** [comment]
The gitlab charts here are deprecated. gitlab now maintains their own charts.
