### ISSUE TITLE
[stable/jenkins] unable to build jobs with default values

### ISSUE THREAD

**Issue by wrlyonsjr** [helm/charts#16731]
**Description**
I am attempting to install stable/jenkins using default values.  It installs just fine but it is unable to build any jobs.  The master image points at jenkins/jenkins:lts which enables JNLP4 and the agent/slave image points at jenkins/jnlp-slave:3.27-1 which seems to use JNLP3?

**helm version**:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

**kubectl version**:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**chart**: stable/jenkins

**What happened**:
Unable to build any jobs after helm install using default values.yaml
Caused by master & agents being unable to connect

**What I expected to happen**:
I expected to be able to build basic jobs with the default chart values.

**How to reproduce it**:
- Install the chart with the default values.
- Create a new Mulitbranch Pipeline job named `test`
- Add a git branch source pointed at https://github.com/jenkins-docs/simple-java-maven-app.git
- Change *Build Configuration* -> *Mode* -> *Script Path* to `jenkins/Jenkinsfile`
- Save
- After less than a minute two builds have been enqueued and cannot proceed due to having no build agents.

**Observations**:

Potentially relevant log snippet from jenkins master pod:
```
WARNING: Error in provisioning; agent=KubernetesSlave name: default-nvpnl, template=PodTemplate{inheritFrom='', name='default', namespace='', label='provided-jenkins-1-jenkins-slave ', serviceAccount='default', nodeSelector='', nodeUsageMode=NORMAL, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], containers=[ContainerTemplate{name='jnlp', image='jenkins/jnlp-slave:3.27-1', workingDir='/home/jenkins', command='', args='${computer.jnlpmac} ${computer.name}', resourceRequestCpu='200m', resourceRequestMemory='256Mi', resourceLimitCpu='200m', resourceLimitMemory='256Mi', envVars=[ContainerEnvVar [getValue()=http://provided-jenkins-1.provided-jenkins-test.svc.cluster.local:8080, getKey()=JENKINS_URL]], livenessProbe=org.csanchez.jenkins.plugins.kubernetes.ContainerLivenessProbe@7f72c7a2}]}
io.fabric8.kubernetes.client.KubernetesClientException: 
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:198)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

After changing the agent retention policy I was able to get to the agent log.
Potentially relevant log snippet from jeknkins agent pod:
```
Aug 30, 2019 4:59:27 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to provided-jenkins-1-agent:50000
Aug 30, 2019 4:59:27 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server reports protocol JNLP4-plaintext not supported, skipping
Aug 30, 2019 4:59:27 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP3-connect is not enabled, skipping
Aug 30, 2019 4:59:27 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server reports protocol JNLP2-connect not supported, skipping
Aug 30, 2019 4:59:27 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server reports protocol JNLP-connect not supported, skipping
Aug 30, 2019 4:59:27 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
	at hudson.remoting.Engine.onConnectionRejected(Engine.java:675)
	at hudson.remoting.Engine.innerRun(Engine.java:639)
	at hudson.remoting.Engine.run(Engine.java:474)
```

**Comment by rohannayakwadi** [comment]
I ran into a similar issue with the latest Jenkins version. Then, after rolling to jenkins-1.2.2 it worked without any issue.

**Comment by torstenwalter** [comment]
@wrlyonsjr Have you tried if using `3.29-1` as `agent.tag` makes a difference? If that does then we should use that as default.

**Comment by wrlyonsjr** [comment]
> @wrlyonsjr Have you tried if using `3.29-1` as `agent.tag` makes a difference? If that does then we should use that as default.

Small difference. Now instead of being unable to speak the expected protocol the agents seem unable to find themselves:
```
Sep 09, 2019 2:53:49 PM org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer onRecv
INFO: [JNLP4-connect connection to provided-jenkins-1-agent/10.100.51.20:50000] Local headers refused by remote: Unknown client name: default-dpk12
Sep 09, 2019 2:53:49 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP4-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Unknown client name: default-dpk12
	at org.jenkinsci.remoting.util.SettableFuture.get(SettableFuture.java:223)
	at hudson.remoting.Engine.innerRun(Engine.java:614)
	at hudson.remoting.Engine.run(Engine.java:474)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Unknown client name: default-dpk12
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.newAbortCause(ConnectionHeadersFilterLayer.java:378)
	at org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer.onRecvClosed(ConnectionHeadersFilterLayer.java:433)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:172)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816)
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$1500(BIONetworkLayer.java:48)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:247)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.nio.channels.ClosedChannelException
		... 7 more
```

The master seems to be unable to find them too:
```
INFO: Kubernetes Pod Template provisioning successfully completed. We have now 2 computer(s)
Sep 09, 2019 2:49:40 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Excess workload after pending Kubernetes agents: 1
Sep 09, 2019 2:49:40 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
INFO: Template for label null: Kubernetes Pod Template
Sep 09, 2019 2:49:40 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Kubernetes Pod Template from kubernetes with 1 executors. Remaining excess workload: 0.492
Sep 09, 2019 2:49:40 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
INFO: Created Pod: provided-jenkins-test/default-3g0hg
Sep 09, 2019 2:49:40 PM okhttp3.internal.platform.Platform log
INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Sep 09, 2019 2:49:40 PM io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1 onFailure
WARNING: Exec Failure: HTTP 403, Status: 403 - 
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Sep 09, 2019 2:49:40 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
WARNING: Error in provisioning; agent=KubernetesSlave name: default-3g0hg, template=PodTemplate{inheritFrom='', name='default', slaveConnectTimeout=0, label='provided-jenkins-1-jenkins-slave ', serviceAccount='default', nodeSelector='', nodeUsageMode=NORMAL, containers=[ContainerTemplate{name='jnlp', image='jenkins/jnlp-slave:3.27-1', workingDir='/home/jenkins', command='', args='${computer.jnlpmac} ${computer.name}', resourceRequestCpu='200m', resourceRequestMemory='256Mi', resourceLimitCpu='200m', resourceLimitMemory='256Mi', envVars=[ContainerEnvVar [getValue()=http://provided-jenkins-1.provided-jenkins-test.svc.cluster.local:8080, getKey()=JENKINS_URL]]}]}
io.fabric8.kubernetes.client.KubernetesClientException: 
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:198)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Sep 09, 2019 2:49:40 PM org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
INFO: Terminating Kubernetes instance for agent default-3g0hg
```

**Comment by wrlyonsjr** [comment]
@rohannayakwadi 
> jenkins-1.2.2

Does this mean `agent.tag: '1.2.2'`?  Or is there another image you're using?

**Comment by wrlyonsjr** [comment]
After running with `agent.tag: "latest"` I ran into this issue:
https://issues.jenkins-ci.org/browse/JENKINS-54683

**Comment by redprasa** [comment]
I am able to run the jobs, but in workspace it is showing no data how can i keep the cloned
 files in workspace.
