### ISSUE TITLE
[stable/airflow] Airflow Web will not start

### ISSUE THREAD

**Issue by benrifkind** [helm/charts#16816]
**Describe the bug**
The Airflow Web Server will not start

**Version of Helm and Kubernetes**: 
Helm: v2.14.3
Kubernetes: Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**: stable/airflow

**What happened**: 
All Airflow pods are running except for the airflow-web pod

**What you expected to happen**:
Airflow web server should start

**How to reproduce it** (as minimally and precisely as possible):
Run
```
helm install --namespace "airflow" --name "airflow" stable/airflow
```
```
➜  ~ kubectl get pods --namespace airflow
NAME                                 READY   STATUS    RESTARTS   AGE
airflow-flower-5786454686-6fd2q      1/1     Running   0          13m
airflow-postgresql-bdcb64f8d-pdl74   1/1     Running   0          13m
airflow-redis-master-0               1/1     Running   0          13m
airflow-scheduler-dcf7cd798-h2xsx    1/1     Running   0          13m
airflow-web-76f4f49c56-65hqm         0/1     Error     2          13m
airflow-worker-0                     1/1     Running   0          13m
```

**Anything else we need to know**:
Logs for Airflow web server
```
[2019-09-03 19:38:26,758] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags
Running the Gunicorn Server with:
Workers: 4 sync
Host: 0.0.0.0:8080
Timeout: 120
Logfiles: - -
=================================================================
[2019-09-03 19:38:27,845] {{settings.py:213}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=16
/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
[2019-09-03 19:38:27 +0000] [16] [INFO] Starting gunicorn 19.9.0
[2019-09-03 19:38:27 +0000] [16] [INFO] Listening at: http://0.0.0.0:8080 (16)
[2019-09-03 19:38:27 +0000] [16] [INFO] Using worker: sync
[2019-09-03 19:38:27 +0000] [20] [INFO] Booting worker with pid: 20
[2019-09-03 19:38:27 +0000] [21] [INFO] Booting worker with pid: 21
[2019-09-03 19:38:27 +0000] [22] [INFO] Booting worker with pid: 22
[2019-09-03 19:38:28 +0000] [23] [INFO] Booting worker with pid: 23
[2019-09-03 19:38:28,585] {{__init__.py:51}} INFO - Using executor CeleryExecutor
[2019-09-03 19:38:28,604] {{__init__.py:51}} INFO - Using executor CeleryExecutor
[2019-09-03 19:38:28,627] {{__init__.py:51}} INFO - Using executor CeleryExecutor
[2019-09-03 19:38:28,735] {{__init__.py:51}} INFO - Using executor CeleryExecutor
[2019-09-03 19:38:30,117] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags
[2019-09-03 19:38:30,119] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags
[2019-09-03 19:38:30,120] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags
[2019-09-03 19:38:30,801] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags
[2019-09-03 19:39:15 +0000] [16] [INFO] Handling signal: ttin
[2019-09-03 19:39:15 +0000] [28] [INFO] Booting worker with pid: 28
[2019-09-03 19:39:16,474] {{__init__.py:51}} INFO - Using executor CeleryExecutor
[2019-09-03 19:39:17,235] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags
[2019-09-03 19:39:17 +0000] [28] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2265, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "airflow-postgresql" to address: Temporary failure in name resolution
```

**Comment by mohannadbanayosi** [comment]
@benrifkind 

Can you please check that the service was created successfully? `kubectl get services`

Also, what version of the the chart are you using?

**Comment by efulet** [comment]
I'm getting same issue. Any news about why this is happing?

**Comment by mohannadbanayosi** [comment]
Which version of the chart are you using? @efulet

**Comment by efulet** [comment]
@mohannadbanayosi I'm using:
```
appVersion: 1.10.4
version: 4.0.7
```

I've checkout the stable version yesterday. The logs show the following error:
```
[2019-09-23 22:07:12 +0000] [33] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2265, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "airflow-postgresql" to address: Temporary failure in name resolution
```

Do I missing an extra env var? I'm using the default configuration right now.

**Comment by mohannadbanayosi** [comment]
@efulet 

Can you please check that the service was created successfully?
`kubectl get services`

Also, is it only the web pod that is failing? Or the workers too?

**Comment by efulet** [comment]
@mohannadbanayosi 
```
$ kubectl get services
NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
airflow-flower           ClusterIP   10.108.133.23   <none>        5555/TCP   9m8s
airflow-postgresql       ClusterIP   10.103.192.29   <none>        5432/TCP   9m8s
airflow-redis-headless   ClusterIP   None            <none>        6379/TCP   9m8s
airflow-redis-master     ClusterIP   10.111.222.0    <none>        6379/TCP   9m8s
airflow-web              ClusterIP   10.103.15.171   <none>        8080/TCP   9m8s
airflow-worker           ClusterIP   None            <none>        8793/TCP   9m8s
```

Logs from worker pod also have same error:
```
$ kubectl logs airflow-worker-0
Tue Sep 24 14:29:28 UTC 2019 - waiting for Postgres... 1/20
Tue Sep 24 14:29:34 UTC 2019 - waiting for Redis... 1/20
waiting 60s...
executing worker...
[snippet]
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "airflow-postgresql" to address: Temporary failure in name resolution
```

**Comment by benrifkind** [comment]
@efulet This was only an issue in minikube for me. I was able to deploy it in AWS EKS for example.

But if your issue is also minikube you may want to check out this thread
https://github.com/helm/charts/issues/17077
I didn't try the solution yet but it may help you

**Comment by chris-aeviator** [comment]
for me airflow web started whenever I did **not** mount a volume to it, might help might not :)

**Comment by gsemet** [comment]
If you have a fix to the minikube example feel free to submit a pull request !

**Comment by slotbite** [comment]
This error apperas

[2020-12-16 10:53:38,102] {base_job.py:202} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 239, in _do_get
    return self._create_connection()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgresql" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 190, in heartbeat
    session.merge(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2155, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2228, in _merge
    merged = self.query(mapper.class_).get(key[1])
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1021, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1138, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 287, in load_on_pk_identity
    return q.one()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3458, in one
    ret = self.one_or_none()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3427, in one_or_none
    ret = list(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3525, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3540, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3518, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
    execution_options=execution_options,
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2305, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2343, in _wrap_pool_connect
    e, dialect, self
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1585, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 239, in _do_get
    return self._create_connection()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgresql" to address: Temporary failure in name resolution
