### ISSUE TITLE
Slave pods don't spawn in Jenkins installed with helm stable chart

### ISSUE THREAD

**Issue by dipeshm01** [helm/charts#16928]
Output of `helm version`: 2.14.3

Output of `kubectl version`: All verisons of kubectl - 1.12, 1.13 and 1.14 has this issue

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

Error description - 
Using helm when i try to deploy kubernetes with command - 
helm install --namespace ci  --name my-release stable/jenkins

i get the installation working fine. However when I create a job whith an executable shell and build the job... the slave pods don't spawn. Actually the slave pods get terminated almost instanenously wiht error message below. What is it that I am missing

Exact error message - 
Sep 06, 2019 9:42:43 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
WARNING: Error in provisioning; agent=KubernetesSlave name: default-rvpzd, template=PodTemplate{inheritFrom='', name='default', slaveConnectTimeout=0, label='my-release-jenkins-slave ', serviceAccount='default', nodeSelector='', nodeUsageMode=NORMAL, containers=[ContainerTemplate{name='jnlp', image='jenkins/jnlp-slave:3.27-1', workingDir='/home/jenkins', command='', args='${computer.jnlpmac} ${computer.name}', resourceRequestCpu='200m', resourceRequestMemory='256Mi', resourceLimitCpu='200m', resourceLimitMemory='256Mi', envVars=[ContainerEnvVar [getValue()=http://my-release-jenkins.ci.svc.cluster.local:8080, getKey()=JENKINS_URL]]}]}
io.fabric8.kubernetes.client.KubernetesClientException: 
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:198)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by bacongobbler** [comment]
Transferring to helm/charts as this appears to be a chart-specific issue, not that of helm. I'd suggest reaching out to the Jenkins folks and ask them directly; this appears to be an application level problem and they'd know best.

**Comment by vishnuhd** [comment]
👍 This is not working for me as well.

**Comment by abdennour** [comment]
This is not working for me as well 👍

Go also to http://localhost:8080/log/all,  I saw : 

```
Error in provisioning; agent=KubernetesSlave name: backendrepo-master-7-jzncd-h0cvp-hkkw0, template=PodTemplate{, name='backendrepo_master_7-jzncd-h0cvp', namespace='cicd', label='backendrepo_master_7-jzncd', nodeUsageMode=EXCLUSIVE, annotations=[org.csanchez.jenkins.plugins.kubernetes.PodAnnotation@aab9c821]}
io.fabric8.kubernetes.client.KubernetesClientException: 
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:198)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by dipeshm01** [comment]
i managed to search for the solution. in short - 
configure the jenkins applications (from browser) by changing kubernetes url from  "https://kubernetes.default" to "https://kubernetes.default:443" and that should solve it...

**Comment by torstenwalter** [comment]
@dipeshm01 Thanks for pointing out the correct answer. I had the same issue after updating our Kubernetes cluster.

**Comment by abdennour** [comment]
@dipeshm01  I searched on it as well, and I resolved it with the same solution.
I am pretty sure you mean this reference : [JENKINS-59000](https://issues.jenkins-ci.org/browse/JENKINS-59000?focusedCommentId=373888&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-373888)

Anyway, you are a good guy 🌹 as you reported the solution immediately, however I am a lazy guy I just reported now 😔
