### ISSUE TITLE
[stable/sematext-agent] Current version is broken

### ISSUE THREAD

**Issue by fabn** [helm/charts#17003]
**Describe the bug**

Current version of chart cannot be deployed because of [this line](https://github.com/helm/charts/blob/master/stable/sematext-agent/templates/daemonset.yaml#L27), it references a file deleted in #15937

**Version of Helm and Kubernetes**:

```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

**What happened**:

When I try to install chart I get this error

```
Error: render error in "sematext-agent/templates/daemonset.yaml": template: sematext-agent/templates/daemonset.yaml:27:44: executing "sematext-agent/templates/daemonset.yaml" at <include (print $.Tem...>: error calling include: template: no template "sematext-agent/templates/configmap-agent-autodisco.yaml" associated with template "gotpl"
```

**Comment by Uter1007** [comment]
I was able to install newest version but I have the following error: 

setting LOGSENE_ENABLED=true
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: Cannot read property 'REMOVE_FIELDS' of undefined
      at removeFields (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:58:33)
      at processAnnotations (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:129:5)
      at /usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:189:9
      at getPodSpec (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:47:5)
      at process._tickCallback (internal/process/next_tick.js:68:7) } reason:  TypeError: Cannot read property 'REMOVE_FIELDS' of undefined
    at removeFields (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:58:33)
    at processAnnotations (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:129:5)
    at /usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:189:9
    at getPodSpec (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:47:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Uter1007** [comment]
Maybe new version could fix that: https://github.com/sematext/logagent-js/releases/tag/3.0.2

**Comment by Uter1007** [comment]
Switched back to 2.0.184. Is it possible to bind chart with fix versions instead of using the latest tag ?
