### ISSUE TITLE
[stable/airflow] Disable SSL when using LDAP for Web authentication

### ISSUE THREAD

**Issue by ramkrishnan8994** [helm/charts#17395]
I'm using the latest version of airflow stable chart.
I've set configuration to connect to OpenLDAP server which was also deployed using the stable/openldap chart.
TLS is not enabled on LDAP server. So I gave **AIRFLOW__LDAP__CACERT** empty as I don't require it.
I'm getting the following error :

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/www/views.py", line 751, in login
    return airflow.login.login(self, request)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/auth/backends/ldap_auth.py", line 308, in login
    LdapUser.try_login(username, password)
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/auth/backends/ldap_auth.py", line 196, in try_login
    configuration.conf.get("ldap", "bind_password"))
  File "/usr/local/lib/python3.7/site-packages/airflow/contrib/auth/backends/ldap_auth.py", line 72, in get_ldap_connection
    ca_certs_file=cacert)
  File "/usr/local/lib/python3.7/site-packages/ldap3/core/tls.py", line 93, in __init__
    raise LDAPSSLConfigurationError('invalid CA public key file')
ldap3.core.exceptions.LDAPSSLConfigurationError: invalid CA public key file
```

Any way I can set any configuration so as to ignore SSL cert.

@stevenmanton @gsemet @mohannadbanayosi

**Comment by Ismail-Ham** [comment]
is there any news ? I am facing the same problem with no rbac (no FAB).

**Comment by Karthik-13** [comment]
Facing the same issue in our project as well. Any news on this?

**Comment by KIRY4** [comment]
Hello any updates? Facing same problem...

**Comment by mattrua** [comment]
Hello. I have the same problem
