### ISSUE TITLE
[stable/sonarqube] sonarqube does not start (java.lang.RuntimeException: can not run elasticsearch as root)

### ISSUE THREAD

**Issue by olivierboudet** [helm/charts#17750]
**Describe the bug**
When installing sonarqube for the first time (not an upgrade), it does not start. Elasticsearch failed with error : java.lang.RuntimeException: can not run elasticsearch as root

**Version of Helm and Kubernetes**:
I am using helmfile with helm-tiller plugin, so no tiller is installed server side.
```
$ helm version
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Error: could not find tiller
```
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.24", GitCommit:"2ce02ef1754a457ba464ab87dba9090d90cf0468", GitTreeState:"clean", BuildDate:"2019-08-12T22:05:28Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart**:
stable/sonarqube
Tried with versions 2.0.1 and 2.3.0

**What happened**:
```
$ kubectl logs sonarqube-sonarqube-5468f6cbc-t7tqj
2019.10.07 15:37:59 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2019.10.07 15:37:59 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2019.10.07 15:37:59 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch
2019.10.07 15:37:59 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2019.10.07 15:38:00 INFO  app[][o.e.p.PluginsService] no modules loaded
2019.10.07 15:38:00 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2019.10.07 15:38:03 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 1
2019.10.07 15:38:03 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2019.10.07 15:38:03 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

```
$ cat es.log
2019.10.07 15:43:12 ERROR es[][o.e.b.Bootstrap] Exception
java.lang.RuntimeException: can not run elasticsearch as root
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:103) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.6.2.jar:6.6.2]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.6.2.jar:6.6.2]
2019.10.07 15:43:12 WARN  es[][o.e.b.ElasticsearchUncaughtExceptionHandler] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: can not run elasticsearch as root
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.6.2.jar:6.6.2]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.6.2.jar:6.6.2]
Caused by: java.lang.RuntimeException: can not run elasticsearch as root
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:103) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.6.2.jar:6.6.2]
	... 6 more

```

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/sonarqube --name sonarqube

Using this values : 
```
securityContext:
  fsGroup: 999

service:
  name: sonarqube
  type: ClusterIP
  
ingress:
  enabled: true
  hosts:
    - name: sonar.mydomain.com
      path: /
  annotations:
    kubernetes.io/ingress.class: nginx
  hostName: sonar.mydomain.com
  tls:
  - hosts:
      - sonar.mydomain.com

resources:
  limits:
    cpu: 6
    memory: 6Gi
  requests:
    cpu: 100m
    memory: 1Gi
persistence:
  enabled: true
  storageClass: "ssd"
  accessMode: ReadWriteOnce
  size: 20Gi

plugins:
  install:
    - "https://github.com/galexandre/sonar-cobertura/releases/download/2.0/sonar-cobertura-plugin-2.0.jar"
    - "https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.0.2/sonarqube-community-branch-plugin-1.0.2.jar"
    - "https://binaries.sonarsource.com/Distribution/sonar-auth-saml-plugin/sonar-auth-saml-plugin-1.1.0.181.jar"
    - "https://binaries.sonarsource.com/Distribution/sonar-scm-git-plugin/sonar-scm-git-plugin-1.9.1.1834.jar"
    - "https://github.com/gabrie-allaigre/sonar-gitlab-plugin/releases/download/4.1.0-SNAPSHOT/sonar-gitlab-plugin-4.1.0-SNAPSHOT.jar"
    - "https://binaries.sonarsource.com/Distribution/sonar-css-plugin/sonar-css-plugin-1.1.1.1010.jar"
    - "https://binaries.sonarsource.com/Distribution/sonar-html-plugin/sonar-html-plugin-3.2.0.2082.jar"
    - "https://binaries.sonarsource.com/Distribution/sonar-java-plugin/sonar-java-plugin-5.14.0.18788.jar"
    - "https://binaries.sonarsource.com/Distribution/sonar-typescript-plugin/sonar-typescript-plugin-1.9.0.3766.jar"

sonarProperties:
  sonar.search.javaOpts: -Xms512m -Xmx1500m

postgresql:
  enabled: true
  persistence:
    storageClass: ssd
  postgresUser: "sonar"
  postgresPassword: "sonar"
  postgresDatabase: "sonar"
  # Specify the TCP port that PostgreSQL should use
  service:
    port: 5432

```

**Anything else we need to know**:

**Comment by olivierboudet** [comment]
When I add this : 
```
securityContext:
  runAsUser: 999
```

the es directory is correctly initialized but the systl call (sysctl --w - vm.max_map_count=262144) is not executed as the container is not privileged anymore. So elasticsearch fails on
```
ERROR: [1] bootstrap checks failed
[1]: initial heap size [536870912] not equal to maximum heap size [1572864000]; this can cause resize pauses and prevents mlockall from locking the entire heap
```

**Comment by olivierboudet** [comment]
it is OK when I add this : 
```
securityContext:
  runAsUser: 999
```
