### ISSUE TITLE
[stable/jenkins] Agent PodLabels doesn't work

### ISSUE THREAD

**Issue by Jdavid7x** [helm/charts#18339]
**Describe the bug**
I'm trying to add a pod label into the jenkins agent via values.yaml but this create some wrong config inside the config.xml of jenkins master

**Version of Helm and Kubernetes**:
Helm version: 2.12.3
Kubernetes version: 1.13

**Which chart**:
stable/jenkins

**What happened**:
The agent is not started in kubernetes. This is the error message:

```error
2019-10-25 10:11:18.263+0000 [id=49]    WARNING o.c.j.p.k.KubernetesLauncher#launch: Error in provisioning; agent=KubernetesSlave name: jenkins-agent-3qh3n, template=PodTemplate{inheritFrom='', name='jenkins-agent', slaveConnectTimeout=0, idleMinutes=60, label='alm-k8s-tst-jenkins-slave map[logging.elk.stack:platform]', serviceAccount='default', nodeSelector='', nodeUsageMode=NORMAL, volumes=[EmptyDirVolume [mountPath=/var/lib/containers, memory=false], SecretVolume [mountPath=/opt/init, secretName=jenkins-permanentagent-init-secret, defaultMode=384], SecretVolume [mountPath=/etc/ssl/sspmutualtls/tmp, secretName=jenkins-permanentagent-sspmutualtls-secret, defaultMode=384]], containers=[ContainerTemplate{name='jnlp', image='sandbox-registry.pro.caas.caixabank.com/wip/docker-jenkins-slave-jnlp:dev-10371', privileged=true, alwaysPullImage=true, workingDir='/home/jenkins', command='sh', args='/opt/init/init_slave.sh ${computer.jnlpmac} ${computer.name}', resourceRequestCpu='500m', resourceRequestMemory='1024Mi', resourceLimitCpu='1000m', resourceLimitMemory='2048Mi'}], envVars=[PodEnvVar [getValue()=-Xms1024m -Xmx2048m, getKey()=JavaOpts], PodEnvVar [getValue()=/etc/ssl/sspmutualtls, getKey()=SSL_DIR]]}                                                io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default/api/v1/namespaces/cxb-cldalm-tst/pods. Message: Pod "jenkins-agent-3qh3n" is invalid: metadata.labels: Invalid value: "jenkins/map[logging.elk.stack:platform]": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'). Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels, message=Invalid value: "jenkins/map[logging.elk.stack:platform]": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Pod, name=jenkins-agent-3qh3n, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod "jenkins-agent-3qh3n" is invalid: metadata.labels: Invalid value: "jenkins/map[logging.elk.stack:platform]": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).                                                                     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:503)                                                                                                                at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:442)                                                                                                            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:406)                                                                                                                at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:365)                                                                                                                at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:234)                                                                                                                  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:735)                                                                                                                        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:325)                                                                                                                              at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:321)                                                                                                                              at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:124)                                                                                                                  at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:297)                                                                                                                                                      at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)                                                                                                                    at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)                                                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                                                                 at java.lang.Thread.run(Thread.java:748)
```

**What you expected to happen**:
Start the agent with the corresponding label

**How to reproduce it** (as minimally and precisely as possible):
Try to deploy a jenkins with this values.yaml 

```values.yaml
agent:
  customJenkinsLabels:
    logging.elk.stack: platform
```

**Anything else we need to know**:

**Comment by Jdavid7x** [comment]
Changed to value yamltemplate and works fine
```
yamlTemplate: |-
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        logging.elk.stack: platform
```
