### ISSUE TITLE
[stable/docker-registry] S3 driver supporting ceph released  but still encountering issue in stable.

### ISSUE THREAD

**Issue by damntourists** [helm/charts#18756]
**Describe the bug**
When using DigitalOcean Spaces as the storage medium for a k8s based docker-registry, docker-registry pods will periodically segfault when performing routine PurgeUploads
Example error:
```
10.244.0.239 - - [10/Nov/2019:20:58:36 +0000] "GET / HTTP/1.1" 200 0 "" "kube-probe/1.16"
time="2019-11-10T20:58:41.874007881Z" level=info msg="PurgeUploads starting: olderThan=2019-11-03 20:58:41.873940008 +0000 UTC m=-603359.966589488, actuallyDelete=true" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc4e6bd]

goroutine 14 [running]:
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk.func1(0xc0000a9000, 0xc000413e01, 0xc000092998)
        /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:973 +0x9d
github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsV2PagesWithContext(0xc00000cb78, 0x7f0babf6a848, 0xc000261500, 0xc00008b400, 0xc000483a98, 0x0, 0x0, 0x0, 0x1, 0x2)
        /go/src/github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:4198 +0x111
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk(0xc000448700, 0xff1ae0, 0xc000261490, 0xc000092b58, 0xc00082d6b1, 0x20, 0xea6655, 0x1, 0xc0003cdf20, 0x0, ...)
        /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:971 +0x3a1
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).Walk(0xc000448700, 0xff1ae0, 0xc000261490, 0xc000289c60, 0x20, 0xc0003cdf20, 0x2, 0x0)
        /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:919 +0x160
github.com/docker/distribution/registry/storage/driver/base.(*Base).Walk(0xc0003ef6b0, 0xff1ae0, 0xc000261490, 0xc000289c60, 0x20, 0xc0003cdf20, 0x0, 0x0)
        /go/src/github.com/docker/distribution/registry/storage/driver/base/base.go:239 +0x234
github.com/docker/distribution/registry/storage.getOutstandingUploads(0xff1c20, 0xc0003d9180, 0xffd980, 0xc0003ef6b0, 0x2, 0xc000092d40, 0xc000092e10, 0x80ac7e)
        /go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:70 +0x236
github.com/docker/distribution/registry/storage.PurgeUploads(0xff1c20, 0xc0003d9180, 0xffd980, 0xc0003ef6b0, 0xbf67edc074174428, 0xfffddb3f4f850dd0, 0x17297c0, 0x1, 0x1, 0x7, ...)
        /go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:34 +0x163
github.com/docker/distribution/registry/handlers.startUploadPurger.func1(0x10015c0, 0xc000263630, 0xff1c20, 0xc0003d9180, 0xffd980, 0xc0003ef6b0, 0x2260ff9290000, 0x0, 0x4e94914f0000)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:1071 +0x221
created by github.com/docker/distribution/registry/handlers.startUploadPurger
        /go/src/github.com/docker/distribution/registry/handlers/app.go:1064 +0x2e9
```

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/docker-registry

**What happened**:
Pod will panic and restart

**What you expected to happen**:
Continue as normal

**How to reproduce it** (as minimally and precisely as possible):
Run Kubernetes through DigitalOcean, install docker-registry on the cluster and use DigitalOcean's Spaces storage for the registry. 

**Anything else we need to know**:
I used this tutorial for setting up a private docker registry on DO:
https://www.digitalocean.com/community/tutorials/how-to-set-up-a-private-docker-registry-on-top-of-digitalocean-spaces-and-use-it-with-digitalocean-kubernetes

The tutorial uses stable/docker-registry which seems to have these issues. 

It appears this was fixed in this PR https://github.com/docker/distribution/pull/2879

I'm curious if we could get stable updated to include this fix? Otherwise, is there anything I can do to circumvent this error? 

It looks like other users in similar situations have found ways around this in https://github.com/docker/distribution/issues/2553 by using a fork of the registry.

**Comment by jansmets** [comment]
Despite being fixed, there unfortunately haven't been any release of the registry software in almost a year.
