### ISSUE TITLE
[stable/airflow] Airflow Web will not start with ingress nginx

### ISSUE THREAD

**Issue by wiltonfelix** [helm/charts#19170]
Describe the bug
The Airflow Web Server will not start

Version of Helm and Kubernetes:
Helm: v2.14.3

Kubernetes: Server Version: gke 14.7

Which chart: stable/airflow

What happened:
All Airflow pods are running except for the airflow-web pod

What you expected to happen:
Airflow web server should start

How to reproduce it (as minimally and precisely as possible):
Run:

helm install --namespace "airflow" --name "prod-airflow" stable/airflow --set airflow.image.repository=gcr.io --set airflow.image.tag=v1.0.7

```
kubectl get pods -n airflow
NAME                                      READY   STATUS    RESTARTS   AGE
prod-airflow-flower-77f7bcd9cc-cw95k      1/1     Running   0          47m
prod-airflow-scheduler-77c5cf747d-8vlzl   1/1     Running   0          47m
prod-airflow-web-64fb8bbfcd-9jj6k         0/1     Running   4          47m
prod-airflow-web-69896bd86b-9sg7b         0/1     Running   0          3m41s
prod-airflow-worker-0                     1/1     Running   0          46m
prod-airflow-worker-1                     1/1     Running   0          46m
prod-airflow-worker-2                     1/1     Running   0          47m
prod-redis-master-0                       1/1     Running   0          29h
```

Logs airflow web:
```[2019-11-27 00:47:14,107] {{__init__.py:51}} INFO - Using executor CeleryExecutor
[2019-11-27 00:47:14,721] {{logging_config.py:50}} INFO - Successfully imported user-defined logging config from log_config.DEFAULT_LOGGING_CONFIG
[2019-11-27 00:47:20,586] {{models.py:258}} INFO - Filling up the DagBag from /usr/local/airflow/dags
[2019-11-27 00:47:38 +0000] [15] [INFO] Handling signal: ttou
[2019-11-27 00:47:38 +0000] [21] [INFO] Worker exiting (pid: 21)
[2019-11-27 00:47:44 +0000] [23] [ERROR] Error handling request /health
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/wsgi.py", line 826, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/airflow/www/app.py", line 173, in root_app
    resp(b'404 Not Found', [(b'Content-Type', b'text/plain')])
  File "/usr/local/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 253, in start_response
    self.process_headers(headers)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 260, in process_headers
    raise TypeError('%r is not a string' % name)
TypeError: b'Content-Type' is not a string
10.28.9.1 - - [27/Nov/2019:00:47:44 +0000] "GET /health HTTP/1.1" 500 0 "-" "-"
[2019-11-27 00:48:09 +0000] [15] [INFO] Handling signal: ttin
[2019-11-27 00:48:09 +0000] [32] [INFO] Booting worker with pid: 32
[2019-11-27 00:48:10 +0000] [23] [ERROR] Error handling request /health
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/wsgi.py", line 826, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/airflow/www/app.py", line 173, in root_app
    resp(b'404 Not Found', [(b'Content-Type', b'text/plain')])
  File "/usr/local/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 253, in start_response
    self.process_headers(headers)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 260, in process_headers
    raise TypeError('%r is not a string' % name)
TypeError: b'Content-Type' is not a string
10.28.9.1 - - [27/Nov/2019:00:48:10 +0000] "GET /health HTTP/1.1" 500 0 "-" "-"
```

Thanks all for help.

**Comment by wiltonfelix** [comment]
I close this issue, but my solution was not use ingress in values.yaml, I create a ingress with another yaml and ajust limits and request limits.
