### ISSUE TITLE
stable/rocket.chat future.js:280  throw(ex);

### ISSUE THREAD

**Issue by golgotow** [helm/charts#19272]
**Describe the bug**
during deploy via helm to Kubernetes cluster 

kubectl logs rocketchat-rocketchat-79d88bdb99-tg8x6
/app/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^
MongoParseError: Unescaped slash in userinfo section
    at parseConnectionString (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/uri_parser.js:445:21)
    at connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_ops.js:188:3)
    at connectOp (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_ops.js:292:3)
    at executeOperation (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:420:24)
    at MongoClient.connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:168:10)
    at Function.MongoClient.connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:372:22)
    at new MongoConnection (packages/mongo/mongo_driver.js:177:11)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Collection (packages/mongo/collection.js:97:40)
    at new AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:23:5)
    at server_main.js (packages/accounts-base/server_main.js:7:12)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)

**Version of Helm and Kubernetes**:
helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Kubernetes version v1.15.5

**Which chart**:
stable/rocket.chat

**What happened**:
during deploy we getting an error with future.js on rocketchat-rocketchat pod

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
helm install rocketchat stable/rocketchat --set mongodb.mongodbPassword=$(echo -n $(openssl rand -base64 32)),mongodb.mongodbRootPassword=$(echo -n $(openssl rand -base64 32)),host=rocketchat.example,persistence.enabled=true,ingress.enabled=true

**Anything else we need to know**:

**Comment by keatz55** [comment]
@golgotow I'm experiencing the same. Did you find a work around?

**Comment by golgotow** [comment]
@keatz55 no i tried standalone install once, and this ends pretty same, so i drop rocketchat project for our usage for now.

**Comment by keatz55** [comment]
@golgotow Thanks for the response. I forgot to come back here and mention my work around. I ended up deploying with out the ingress-specific flags. Then I added my own ingress rule manually and everything works great.

**Comment by golgotow** [comment]
@keatz55 Thank you for tip, i will try it when get possiblity.

**Comment by golgotow** [comment]
@keatz55  Hi,

I did try without ingress, but this end's same 

kubectl logs rocketchat-rocketchat-6784dddd79-5js4w
/app/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^
MongoParseError: Unescaped slash in userinfo section
    at parseConnectionString (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/uri_parser.js:445:21)
    at connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_ops.js:188:3)
    at connectOp (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_ops.js:292:3)
    at executeOperation (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:420:24)
    at MongoClient.connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:168:10)
    at Function.MongoClient.connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:372:22)
    at new MongoConnection (packages/mongo/mongo_driver.js:177:11)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Collection (packages/mongo/collection.js:97:40)
    at new AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:23:5)
    at server_main.js (packages/accounts-base/server_main.js:7:12)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)



I tried via 

helm install rocketchat stable/rocketchat --set mongodb.mongodbPassword=$(echo -n $(openssl rand -base64 32)),mongodb.mongodbRootPassword=$(echo -n $(openssl rand -base64 32)),persistence.enabled=true

Br,

**Comment by golgotow** [comment]
Hi,

i did tried to install rocket-chat on openshift 3.11 OKD in our test lab, and this end's pretty same.



﻿/app/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^
Error: Error: Unable to find Mongodb Oplog. You must run the server with oplog enabled. Try the following:
				1. Start your mongodb in a replicaset mode: mongod --smallfiles --oplogSize 128 --replSet rs0
				2. Start the replicaset via mongodb shell: mongo mongo/meteor --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"
				3. Start your instance with OPLOG configuration: export MONGO_OPLOG_URL=mongodb://localhost:27017/local MONGO_URL=mongodb://localhost:27017/meteor node main.js
				
    at BaseDb.handleListener (app/models/server/models/_BaseDb.js:51:11)
    at emitTwo (events.js:126:13)
    at BaseDb.emit (events.js:214:7)
    at _addListener (events.js:249:14)
    at BaseDb.addListener (events.js:297:10)
    at new Base (app/models/server/models/_Base.js:21:12)
    at new Settings (app/models/server/models/Settings.js:5:3)
    at Settings.js (app/models/server/models/Settings.js:243:16)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at settings.js (app/settings/server/functions/settings.js:1:251)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (app/settings/server/index.js:1:60)







Best Regards

**Comment by zdelanofw** [comment]
```helm install rocketchat stable/rocketchat --set mongodb.mongodbPassword=$(echo -n $(openssl rand -base64 32)),mongodb.mongodbRootPassword=$(echo -n $(openssl rand -base64 32)),host=rocketchat.example,persistence.enabled=true,ingress.enabled=true
```
The issue, I believe, is with the generation of the passwords. Try a simple password like `qwerty123` and I think it should work. I was running into a similar issue today but when I passed non-random passwords, I was able to get it to deploy just fine.

**Comment by golgotow** [comment]
@zdelanofw yes that is true, with easier password this works,
