### ISSUE TITLE
[stable/mongodb] fail to connect to mongodb replicaset

### ISSUE THREAD

**Issue by cow5566bad** [helm/charts#19296]
**Problem**
`
[stable/mongodb] connection string problem
`

**Version of Helm and Kubernetes**:
- version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

- Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}

- Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
`
[stable/mongodb]
`

**What happened**:
`
can't connect to mongodb replicaset
`

**How to reproduce it** (as minimally and precisely as possible):
-  helm install replicaset --set mongodbRootPassword=rootpassword,mongodbUsername=user,mongodbPassword=password,mongodbDatabase=Demographic,replicaSet.enabled=true stable/mongodb

- kubectl port-forward --namespace default svc/replicaset-mongodb 27017:27017 & mongo --host 127.0.0.1 --authenticationDatabase admin -p rootpassword

- (C# client) MongoClient dbClient = new MongoClient("mongodb://root:rootpassword@localhost:27017?replicaSet=rs0&authSource=admin");

**Anything else we need to know**:

Hi All,
I am new to kubernetes and mongodb, and now I want to run a mongodb replicaset on azure vm.
I have already set up the replicaset and checked it by

- kubectl exec -it  replicaset-mongodb-primary-0 -- /bin/bash

- mongo --username root --password rootpassword

- rs.status()

It returned
```json
rs0:PRIMARY> rs.status()
{
        "set" : "rs0",
        "date" : ISODate("2019-12-02T09:12:05.255Z"),
        "myState" : 1,
        "term" : NumberLong(3),
        "syncingTo" : "",
        "syncSourceHost" : "",
        "syncSourceId" : -1,
        "heartbeatIntervalMillis" : NumberLong(2000),
        "optimes" : {
                "lastCommittedOpTime" : {
                        "ts" : Timestamp(1575277917, 1),
                        "t" : NumberLong(3)
                },
                "readConcernMajorityOpTime" : {
                        "ts" : Timestamp(1575277917, 1),
                        "t" : NumberLong(3)
                },
                "appliedOpTime" : {
                        "ts" : Timestamp(1575277917, 1),
                        "t" : NumberLong(3)
                },
                "durableOpTime" : {
                        "ts" : Timestamp(1575277917, 1),
                        "t" : NumberLong(3)
                }
        },
        "lastStableCheckpointTimestamp" : Timestamp(1575277917, 1),
        "members" : [
                {
                        "_id" : 0,
                        "name" : "replicaset-mongodb-primary-0.replicaset-mongodb-headless.default.svc.cluster.local:27017",
                        "health" : 1,
                        "state" : 1,
                        "stateStr" : "PRIMARY",
                        "uptime" : 184,
                        "optime" : {
                                "ts" : Timestamp(1575277917, 1),
                                "t" : NumberLong(3)
                        },
                        "optimeDate" : ISODate("2019-12-02T09:11:57Z"),
                        "syncingTo" : "",
                        "syncSourceHost" : "",
                        "syncSourceId" : -1,
                        "infoMessage" : "",
                        "electionTime" : Timestamp(1575277755, 1),
                        "electionDate" : ISODate("2019-12-02T09:09:15Z"),
                        "configVersion" : 3,
                        "self" : true,
                        "lastHeartbeatMessage" : ""
                },
                {
                        "_id" : 1,
                        "name" : "replicaset-mongodb-arbiter-0.replicaset-mongodb-headless.default.svc.cluster.local:27017",
                        "health" : 1,
                        "state" : 7,
                        "stateStr" : "ARBITER",
                        "uptime" : 161,
                        "lastHeartbeat" : ISODate("2019-12-02T09:12:03.490Z"),
                        "lastHeartbeatRecv" : ISODate("2019-12-02T09:12:03.725Z"),
                        "pingMs" : NumberLong(0),
                        "lastHeartbeatMessage" : "",
                        "syncingTo" : "",
                        "syncSourceHost" : "",
                        "syncSourceId" : -1,
                        "infoMessage" : "",
                        "configVersion" : 3
                },
                {
                        "_id" : 2,
                        "name" : "replicaset-mongodb-secondary-0.replicaset-mongodb-headless.default.svc.cluster.local:27017",
                        "health" : 1,
                        "state" : 2,
                        "stateStr" : "SECONDARY",
                        "uptime" : 151,
                        "optime" : {
                                "ts" : Timestamp(1575277917, 1),
                                "t" : NumberLong(3)
                        },
                        "optimeDurable" : {
                                "ts" : Timestamp(1575277917, 1),
                                "t" : NumberLong(3)
                        },
                        "optimeDate" : ISODate("2019-12-02T09:11:57Z"),
                        "optimeDurableDate" : ISODate("2019-12-02T09:11:57Z"),
                        "lastHeartbeat" : ISODate("2019-12-02T09:12:03.523Z"),
                        "lastHeartbeatRecv" : ISODate("2019-12-02T09:12:04.610Z"),
                        "pingMs" : NumberLong(59),
                        "lastHeartbeatMessage" : "",
                        "syncingTo" : "replicaset-mongodb-primary-0.replicaset-mongodb-headless.default.svc.cluster.local:27017",
                        "syncSourceHost" : "replicaset-mongodb-primary-0.replicaset-mongodb-headless.default.svc.cluster.local:27017",
                        "syncSourceId" : 0,
                        "infoMessage" : "",
                        "configVersion" : 3
                }
        ],
        "ok" : 1,
        "operationTime" : Timestamp(1575277917, 1),
        "$clusterTime" : {
                "clusterTime" : Timestamp(1575277917, 1),
                "signature" : {
                        "hash" : BinData(0,"DBAs7wvoV8RAAvzpr7IxTVtMNZo="),
                        "keyId" : NumberLong("6765739961367920641")
                }
        }
}
```
Now I want to load data into my replicaset through a .net dataloader application. I first did a port-forward and then connected to my replicaset via connection string:
```C#
MongoClient dbClient = new MongoClient($"mongodb://root:rootpassword@localhost:27017?replicaSet=rs0&authSource=admin");
```
However it always failed with a timeout exception when I insert BsonDocument.
```
System.TimeoutException
  HResult=0x80131505
  Message=A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "ReplicaSet", Type : "ReplicaSet", State : "Disconnected", Servers : [] }.
  Source=MongoDB.Driver.Core
  StackTrace:
   at MongoDB.Driver.Core.Clusters.Cluster.ThrowTimeoutException(IServerSelector selector, ClusterDescription description)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChanged(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Clusters.Cluster.SelectServer(IServerSelector selector, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupportedAfterServerSelection(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupported(CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.StartImplicitSession(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionBase`1.<>c__DisplayClass64_0.<InsertOne>b__0(IEnumerable`1 requests, BulkWriteOptions bulkWriteOptions)
   at MongoDB.Driver.MongoCollectionBase`1.InsertOne(TDocument document, InsertOneOptions options, Action`2 bulkWrite)
   at MongoDB.Driver.MongoCollectionBase`1.InsertOne(TDocument document, InsertOneOptions options, CancellationToken cancellationToken)
   at DemographicDataLoader.Program.<>c__DisplayClass1_0.<Main>b__0(Int32 i) in C:\Users\v-lehsie\Desktop\ReverseGeocoder\private\DataMarketPlace\DataPipeline\Demographic\ConsoleApp1\Program.cs:line 64
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)

```

I have gotten stuck into the problem for days. Are there any steps I missed?
Thanks.

**Comment by javsalgar** [comment]
Hi,

I saw that the mongo command worked inside the pods, but did you try running the `mongo` command in the same host you did kubectl port-forward? This may give us more information about the issue.

**Comment by cow5566bad** [comment]
Hi javsalger, 

Thanks for your reply, I did some further trails.
Now I can access the replicaset inside the cluster with both these urls:

- mongo "mongodb://root:rootpassword@replicaset-mongodb-primary-0.replicaset-mongodb-headless.default.svc.cluster.local:27017"
- mongo "mongodb://root:rootpassword@replicaset-mongodb-primary-0.replicaset-mongodb-headless.default.svc.cluster.local:27017,replicaset-mongodb-secondary-0.replicaset-mongodb-headless.default.svc.cluster.local:27017,replicaset-mongodb-arbiter.default.svc.cluster.local:27017/admin?replicaSet=rs0"

It will take me to rs0:PRIMARY mongo shell, worked fine.

Then I tried to expose all my replicaset-mongodb with type=LoadBalancer, which also worked fine.
```c++
NAME                             TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)           AGE
kubernetes                       ClusterIP      10.0.0.1       <none>           443/TCP           32d
replicaset-mongodb               ClusterIP      10.0.242.121   <none>           27017/TCP         8h
replicaset-mongodb-arbiter-0     LoadBalancer   10.0.210.75    51.143.113.26    27017:30829/TCP   41m
replicaset-mongodb-headless      ClusterIP      None           <none>           27017/TCP         8h
replicaset-mongodb-primary-0     LoadBalancer   10.0.163.135   52.143.81.76     27017:30325/TCP   8h
replicaset-mongodb-secondary-0   LoadBalancer   10.0.122.136   51.143.114.129   27017:31758/TCP   42m
```

The problem is when i try to connect remotely following the same style,
```C#
MongoClient dbClient = new MongoClient("mongodb://root:rootpassword@52.143.81.76:27017,52.143.113.26:27017,52.143.114.129:27017/admin?replicaSet=rs0");
```
it gave me
```C++
System.TimeoutException
  HResult=0x80131505
  Message=A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "ReplicaSet", Type : "ReplicaSet", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/replicaset-mongodb-arbiter-0.replicaset-mongodb-headless.default.svc.cluster.local:27017" }", EndPoint: "Unspecified/replicaset-mongodb-arbiter-0.replicaset-mongodb-headless.default.svc.cluster.local:27017", State: "Disconnected", Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server. ---> System.Net.Sockets.SocketException: No such host is known
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ResolveEndPointsAsync(EndPoint initial)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)", LastUpdateTimestamp: "2019-12-04T03:40:58.0189679Z" }, { ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/replicaset-mongodb-primary-0.replicaset-mongodb-headless.default.svc.cluster.local:27017" }", EndPoint: "Unspecified/replicaset-mongodb-primary-0.replicaset-mongodb-headless.default.svc.cluster.local:27017", State: "Disconnected", Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server. ---> System.Net.Sockets.SocketException: No such host is known
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ResolveEndPointsAsync(EndPoint initial)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)", LastUpdateTimestamp: "2019-12-04T03:40:58.0120977Z" }, { ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/replicaset-mongodb-secondary-0.replicaset-mongodb-headless.default.svc.cluster.local:27017" }", EndPoint: "Unspecified/replicaset-mongodb-secondary-0.replicaset-mongodb-headless.default.svc.cluster.local:27017", State: "Disconnected", Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server. ---> System.Net.Sockets.SocketException: No such host is known
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.ResolveEndPointsAsync(EndPoint initial)
   at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)", LastUpdateTimestamp: "2019-12-04T03:40:58.0226635Z" }] }.
  Source=MongoDB.Driver.Core
  StackTrace:
   at MongoDB.Driver.Core.Clusters.Cluster.ThrowTimeoutException(IServerSelector selector, ClusterDescription description)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
   at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChanged(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Clusters.Cluster.SelectServer(IServerSelector selector, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupportedAfterServerSelection(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoClient.AreSessionsSupported(CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.StartImplicitSession(CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionBase`1.<>c__DisplayClass64_0.<InsertOne>b__0(IEnumerable`1 requests, BulkWriteOptions bulkWriteOptions)
   at MongoDB.Driver.MongoCollectionBase`1.InsertOne(TDocument document, InsertOneOptions options, Action`2 bulkWrite)
   at MongoDB.Driver.MongoCollectionBase`1.InsertOne(TDocument document, InsertOneOptions options, CancellationToken cancellationToken)
   at DemographicDataLoader.Program.<>c__DisplayClass1_0.<Main>b__0(Int32 i) in C:\Users\v-lehsie\Desktop\ReverseGeocoder\private\DataMarketPlace\DataPipeline\Demographic\ConsoleApp1\Program.cs:line 106
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)

```
However, I can connect with the primary node directly with
```c#
MongoClient dbClient = new MongoClient("mongodb://root:rootpassword@52.143.81.76:27017/admin");
```

But directly connect to primary node and insert data cause some corrupted database insertion like this(I only insert data to database "Demographic"):
```C++
rs0:PRIMARY> show dbs
@emographic  0.000GB
Damographic  0.000GB
Demkgraphic  0.000GB
Democraphic  0.000GB
Demographic  0.014GB
Demographig  0.000GB
Demographmc  0.000GB
Demograplic  0.000GB
admin        0.000GB
config       0.000GB
local        0.061GB
```
