### ISSUE TITLE
stable/kibana data too large for kibana

### ISSUE THREAD

**Issue by avarf** [helm/charts#19635]
**Describe the bug**
I am using Kibana with Elasticsearch and fluentbit and Kibana faced error and when I checked the logs I saw that the data was too large for kibana and it went beyond its limit.

I checked the values file but I couldn't find a limit for kibana and also I haven't set up a resource limit for it when I installed it.

How I can change this limit?

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

helm ls
NAME      	REVISION	UPDATED                 	STATUS  	CHART                       	APP VERSION	NAMESPACE 
kibana    	1       	Fri Dec  6 15:42:46 2019	DEPLOYED	kibana-3.2.4                	6.7.0      	logging 
```

**Which chart**:
stable/kibana

**What you expected to happen**:
Either there should be a value in the values file that we can set for the limit OR kibana uses the resource limits as the limit for the data size.

**How to reproduce it** (as minimally and precisely as possible):
Request a large amount of data.

**Anything else we need to know**:
Logs:
```
{"type":"error","@timestamp":"2019-12-17T09:28:16Z","tags":[],"pid":1,"level":"error","error":{"message":"[parent] Data too large, data for [<http_request>] would be [1027332392/979.7mb], which is larger than the limit of [1011774259/964.9mb], real usage: [1027332392/979.7mb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b, accounting=749742302/715mb]: [circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [1027332392/979.7mb], which is larger than the limit of [1011774259/964.9mb], real usage: [1027332392/979.7mb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b, accounting=749742302/715mb], with { bytes_wanted=1027332392 & bytes_limit=1011774259 & durability=\"PERMANENT\" }","name":"Error","stack":"[circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [1027332392/979.7mb], which is larger than the limit of [1011774259/964.9mb], real usage: [1027332392/979.7mb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b, accounting=749742302/715mb], with { bytes_wanted=1027332392 & bytes_limit=1011774259 & durability=\"PERMANENT\" } :: {\"path\":\"/.kibana/doc/config%3A6.7.0\",\"query\":{},\"statusCode\":429,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"circuit_breaking_exception\\\",\\\"reason\\\":\\\"[parent] Data too large, data for [<http_request>] would be [1027332392/979.7mb], which is larger than the limit of [1011774259/964.9mb], real usage: [1027332392/979.7mb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b, accounting=749742302/715mb]\\\",\\\"bytes_wanted\\\":1027332392,\\\"bytes_limit\\\":1011774259,\\\"durability\\\":\\\"PERMANENT\\\"}],\\\"type\\\":\\\"circuit_breaking_exception\\\",\\\"reason\\\":\\\"[parent] Data too large, data for [<http_request>] would be [1027332392/979.7mb], which is larger than the limit of [1011774259/964.9mb], real usage: [1027332392/979.7mb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b, accounting=749742302/715mb]\\\",\\\"bytes_wanted\\\":1027332392,\\\"bytes_limit\\\":1011774259,\\\"durability\\\":\\\"PERMANENT\\\"},\\\"status\\\":429}\"}\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:308:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:267:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4935:19)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/app/kibana","path":"/app/kibana","href":"/app/kibana"},"message":"[parent] Data too large, data for [<http_request>] would be [1027332392/979.7mb], which is larger than the limit of [1011774259/964.9mb], real usage: [1027332392/979.7mb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b, accounting=749742302/715mb]: [circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [1027332392/979.7mb], which is larger than the limit of [1011774259/964.9mb], real usage: [1027332392/979.7mb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=0/0b, accounting=749742302/715mb], with { bytes_wanted=1027332392 & bytes_limit=1011774259 & durability=\"PERMANENT\" }"}
```

**Comment by avarf** [comment]
This is related to https://github.com/elastic/kibana/issues/56500
