### ISSUE TITLE
[stable/redmine] Bundler problem

### ISSUE THREAD

**Issue by lucamaggioni** [helm/charts#20214]
Hi

Kubernetes version: 1.16.3
helm version: 3.0.2
chart: stable/redmine

Issue:

I'm installing redmine with this command
`helm install redmine --values redmine.yaml stable/redmine`

... and with this configuration (redmine.yaml)
```
persistence:
  enabled: true
  storageClass: nfs-online
  accessMode: ReadWriteOnce
  size: 1Gi

mariadb:
  master:
    persistence:
      enabled: false

```

.... so a maria db without persistence and the redmine persisted, but i face this problem in the redmine pod:

```
redmine INFO  ########################################################################
redmine INFO   Installation parameters for redmine:
redmine INFO     Persisted data and properties have been restored.
redmine INFO     Any input specified will not take effect.
redmine INFO   This installation requires no credentials.
redmine INFO  ########################################################################
redmine INFO
nami    INFO  redmine successfully initialized
INFO  ==> Starting redmine...
INFO  ==> Starting redmine...
Please configure your config/database.yml first
bundler: failed to load command: passenger (/opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/bin/passenger)
Bundler::ProductionError: You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the /opt/bitnami/redmine/Gemfile freeze
by running `bundle install --no-deployment`.

You have deleted from the Gemfile:
* mysql2 (~> 0.5.0)
* pg (~> 1.1.4)

  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/definition.rb:466:in `ensure_equivalent_gemfile_and_lockfile'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:13:in `setup'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler.rb:107:in `setup'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/setup.rb:20:in `<top (required)>'
  /opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /opt/bitnami/ruby/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```
... and the container goes in CrashLoopBackOff.

If I disable the persistence in redmine everithing goes well.. but I need persistence for images & attachments.

Can you help me?

Thanks
Regards
Luca

**Comment by juan131** [comment]
Hi Luca,

It looks like some issue during the 1st initialization of the container. Since you're persisting the data, the `CrashLoopBackOff` is reached since the data is in an inconsistent state.

Could you try this workaround?

- Install the chart (disabling persistence)
- Once Redmine finished the 1st boot and it's initialized correctly, upgrade your chart release enabling persistence

**Comment by lucamaggioni** [comment]
I've tried your workaround but didn't work: nothings changes when I activate persistence with an upgrade.

Should I try other things?

**Comment by lucamaggioni** [comment]
should I try downgrading to helm  2?

Can you reproduce my problem with helm 3?

Thanks
Luca

**Comment by juan131** [comment]
Hi @lucamaggioni 

Sorry for the late response. 

Could you please share the logs of the Redmine container **before** doing the upgrade? Please also share the **values.yaml** and command you're using to install Redmine the 1st time.

It would be great if you could uncomment this section in the default **values.yaml** to increase the verbosity in the logs:

```yaml
# extraVars:
#   - name: NAMI_DEBUG
#     value: --log-level trace
```

**Comment by lucamaggioni** [comment]
Hi @juan131 

Thank you your kind support!

So here's the details requested.

First of all I have this redmine.yaml values file:
```
persistence:
  enabled: false
  storageClass: nfs-online
  accessMode: ReadWriteOnce
  size: 1Gi

extraVars:
  - name: NAMI_DEBUG
    value: --log-level trace

mariadb:
  master:
    persistence:
      enabled: false

```
... where I've disabled redmine persistence and I've increased the verbosity in the logs as you requested.

Then I run this:
```
root@techmi-k8s02-master01:~# helm install redmine --values redmine.yaml stable/redmine --version 14.1.6
NAME: redmine
LAST DEPLOYED: Tue Jan 28 07:49:17 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the Redmine URL:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w redmine'


  export SERVICE_IP=$(kubectl get svc --namespace default redmine --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
  echo "Redmine URL: http://$SERVICE_IP/"

2. Login with the following credentials

  echo Username: user
  echo Password: $(kubectl get secret --namespace default redmine -o jsonpath="{.data.redmine-password}" | base64 --decode)
root@techmi-k8s02-master01:/tmp/helm#
```

Now, here's the container log:

```
root@techmi-k8s02-master01:~# kubectl logs redmine-79f875db7c-pqvmd
app-entrypoint.sh 07:50:09.79
app-entrypoint.sh 07:50:09.80 Welcome to the Bitnami redmine container
app-entrypoint.sh 07:50:09.80 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
app-entrypoint.sh 07:50:09.80 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
app-entrypoint.sh 07:50:09.81 Send us your feedback at containers@bitnami.com
app-entrypoint.sh 07:50:09.81
nami    INFO  Initializing redmine
redmine DEBUG Creating Redmine System User...
redmine DEBUG ==> Detected MariaDB/MySQL database
redmine INFO  Configuring Redmine database...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at redmine-mariadb:3306
mysql-c TRACE [canConnect] Testing connection with 'bn_redmine' user
mysql-c TRACE [showDatabases] Getting databases for 'bn_redmine' user
mysql-c TRACE [execute] Executing: mysql -N -P 3306 -hredmine-mariadb -ubn_redmine -py99DrwPJOR -e SHOW DATABASES;
mysql-c TRACE [execute] Result: {"code":0,"stdout":"bitnami_redmine\ninformation_schema\ntest\n","stderr":""}
mysql-c TRACE [showDatabases] Databases: bitnami_redmine
information_schema
test

mysql-c TRACE [canConnect] Connection with 'bn_redmine' user is successful
mysql-c INFO  MySQL server listening and working at redmine-mariadb:3306
redmine INFO  Preparing Redmine environment...
redmine INFO  Generating new secret...
ruby    TRACE [runProgram] Executing: /opt/bitnami/ruby/bin/ruby /opt/bitnami/ruby/bin/bundle,exec,rake,generate_secret_token
redmine INFO  Migrating database...
ruby    TRACE [runProgram] Executing: /opt/bitnami/ruby/bin/ruby /opt/bitnami/ruby/bin/bundle,exec,rake,db:migrate
ruby    TRACE [runProgram] Executing: /opt/bitnami/ruby/bin/ruby /opt/bitnami/ruby/bin/bundle,exec,rake,redmine:plugins:migrate
ruby    TRACE [runProgram] Executing: /opt/bitnami/ruby/bin/ruby /opt/bitnami/ruby/bin/bundle,exec,rake,redmine:load_default_data
redmine TRACE [prepareDataToPersist] Preparing /opt/bitnami/redmine/conf/configuration.yml to persist in /bitnami/redmine/conf/configuration.yml
redmine TRACE [prepareDataToPersist] Preparing /opt/bitnami/redmine/conf/database.yml to persist in /bitnami/redmine/conf/database.yml
redmine TRACE [prepareDataToPersist] Preparing /opt/bitnami/redmine/public/plugin_assets to persist in /bitnami/redmine/public/plugin_assets
redmine TRACE [prepareDataToPersist] Preparing /opt/bitnami/redmine/plugins to persist in /bitnami/redmine/plugins
redmine TRACE [prepareDataToPersist] Preparing /opt/bitnami/redmine/files to persist in /bitnami/redmine/files
redmine TRACE [configurePermissions] File to chown: /home/redmine
redmine TRACE [configurePermissions] File to chmod: /home/redmine
redmine TRACE [configurePermissions] File to chown: /opt/bitnami/redmine/tmp
redmine TRACE [configurePermissions] File to chmod: /opt/bitnami/redmine/tmp
redmine TRACE [configurePermissions] File to chown: /opt/bitnami/redmine/tmp/pdf
redmine TRACE [configurePermissions] File to chmod: /opt/bitnami/redmine/tmp/pdf
redmine TRACE [configurePermissions] File to chown: /bitnami/redmine/public/plugin_assets
redmine TRACE [configurePermissions] File to chmod: /bitnami/redmine/public/plugin_assets
redmine TRACE [configurePermissions] File to chown: /bitnami/redmine/files
redmine TRACE [configurePermissions] File to chmod: /bitnami/redmine/files
redmine TRACE [configurePermissions] File to chown: /opt/bitnami/redmine/logs
redmine TRACE [configurePermissions] File to chmod: /opt/bitnami/redmine/logs
redmine INFO
redmine INFO  ########################################################################
redmine INFO   Installation parameters for redmine:
redmine INFO     Username: user
redmine INFO     Password: **********
redmine INFO   (Passwords are not shown for security reasons)
redmine INFO  ########################################################################
redmine INFO
nami    INFO  redmine successfully initialized
app-entrypoint.sh 07:51:22.95 INFO  ==> Starting redmine...
run.sh 07:51:22.98 INFO  ==> Starting redmine...
 [passenger_native_support.so] trying to compile for the current user (redmine) and Ruby interpreter...
     (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
     Warning: compilation didn't succeed. To learn why, read this file:
     /tmp/passenger_native_support-rcfdqm.log
 [passenger_native_support.so] finding downloads for the current Ruby interpreter...
     (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
     Could not download https://github.com/phusion/passenger/releases/download/release-6.0.4/rubyext-ruby-2.6.5-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
     Trying next mirror...
     Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.4/rubyext-ruby-2.6.5-x86_64-linux.tar.gz: The requested URL returned error: 404
     Trying next mirror...
     Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.4/rubyext-ruby-2.6.5-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
 [passenger_native_support.so] will not be used (can't compile or download)
  --> Passenger will still operate normally.
=============== Phusion Passenger Standalone web server started ===============
PID file: /opt/bitnami/redmine/tmp/pids/redmine.pid
Log file: /opt/bitnami/redmine/logs/production.log
Environment: production
Accessible via: http://0.0.0.0:3000/

You can stop Phusion Passenger Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
===============================================================================
App 129 output:  [passenger_native_support.so] trying to compile for the current user (redmine) and Ruby interpreter...
App 129 output:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 129 output:  [passenger_native_support.so] trying to compile for the current user (redmine) and Ruby interpreter...
App 129 output:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 129 output:      Warning: compilation didn't succeed. To learn why, read this file:
App 129 output:      /tmp/passenger_native_support-xodhfs.log
App 129 output:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
App 129 output:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 129 output:      Could not download https://github.com/phusion/passenger/releases/download/release-6.0.4/rubyext-ruby-2.6.5-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
App 129 output:      Trying next mirror...
App 129 output:      Warning: compilation didn't succeed. To learn why, read this file:
App 129 output:      /tmp/passenger_native_support-xodhfs.log
App 129 output:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
App 129 output:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 129 output:      Could not download https://github.com/phusion/passenger/releases/download/release-6.0.4/rubyext-ruby-2.6.5-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
App 129 output:      Trying next mirror...
App 129 output:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.4/rubyext-ruby-2.6.5-x86_64-linux.tar.gz: The requested URL returned error: 404
App 129 output:      Trying next mirror...
[ N 2020-01-28 07:51:28.0474 94/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 129 output:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.4/rubyext-ruby-2.6.5-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
App 129 output:  [passenger_native_support.so] will not be used (can't compile or download)
App 129 output:   --> Passenger will still operate normally.
App 129 output:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.4/rubyext-ruby-2.6.5-x86_64-linux.tar.gz: The requested URL returned error: 404
App 129 output:      Trying next mirror...
[ N 2020-01-28 07:51:28.0474 94/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 129 output:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.4/rubyext-ruby-2.6.5-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
App 129 output:  [passenger_native_support.so] will not be used (can't compile or download)
App 129 output:   --> Passenger will still operate normally.
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Started GET "/" for 172.16.4.1 at 2020-01-28 07:51:33 +0000
Processing by WelcomeController#index as HTML
  Current user: anonymous
Started HEAD "/" for 127.0.0.1 at 2020-01-28 07:51:34 +0000
Processing by WelcomeController#index as HTML
  Current user: anonymous
Started GET "/" for 172.16.4.1 at 2020-01-28 07:51:33 +0000
Processing by WelcomeController#index as HTML
  Current user: anonymous
Started HEAD "/" for 127.0.0.1 at 2020-01-28 07:51:34 +0000
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendering welcome/index.html.erb within layouts/base
  Rendered welcome/index.html.erb within layouts/base (11.9ms)
Completed 200 OK in 1676ms (Views: 46.8ms | ActiveRecord: 42.4ms)
  Rendering welcome/index.html.erb within layouts/base
  Rendered welcome/index.html.erb within layouts/base (15.4ms)
Completed 200 OK in 1611ms (Views: 51.7ms | ActiveRecord: 52.4ms)
  Rendering welcome/index.html.erb within layouts/base
  Rendered welcome/index.html.erb within layouts/base (11.9ms)
Completed 200 OK in 1676ms (Views: 46.8ms | ActiveRecord: 42.4ms)
  Rendering welcome/index.html.erb within layouts/base
  Rendered welcome/index.html.erb within layouts/base (15.4ms)
Completed 200 OK in 1611ms (Views: 51.7ms | ActiveRecord: 52.4ms)
Started GET "/" for 172.16.4.1 at 2020-01-28 07:51:35 +0000
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendering welcome/index.html.erb within layouts/base
  Rendered welcome/index.html.erb within layouts/base (1.4ms)
Completed 200 OK in 38ms (Views: 13.5ms | ActiveRecord: 13.7ms)
Started GET "/" for 172.16.4.1 at 2020-01-28 07:51:35 +0000
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendering welcome/index.html.erb within layouts/base
  Rendered welcome/index.html.erb within layouts/base (1.4ms)
Completed 200 OK in 38ms (Views: 13.5ms | ActiveRecord: 13.7ms)
Started GET "/" for 172.16.4.1 at 2020-01-28 07:51:45 +0000
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendering welcome/index.html.erb within layouts/base
  Rendered welcome/index.html.erb within layouts/base (1.4ms)
Completed 200 OK in 36ms (Views: 13.0ms | ActiveRecord: 12.6ms)
Started GET "/" for 172.16.4.1 at 2020-01-28 07:51:45 +0000
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendering welcome/index.html.erb within layouts/base
  Rendered welcome/index.html.erb within layouts/base (1.4ms)
Completed 200 OK in 36ms (Views: 13.0ms | ActiveRecord: 12.6ms)
```
... and the log goes on.

Thanks
Regards
Luca

**Comment by lucamaggioni** [comment]
... then I've performed the upgrade in this way.

First I've modified redmine.yaml values file in this way:
```
persistence:
  enabled: true
  storageClass: nfs-online
  accessMode: ReadWriteOnce
  size: 1Gi

extraVars:
  - name: NAMI_DEBUG
    value: --log-level trace

mariadb:
  db:
    name: bitnami_redmine
    user: bn_redmine
    password: mypass
  master:
    persistence:
      enabled: false
```
... this enables the persistence in redmine...  then I perform an upgrade:
```
root@techmi-k8s02-master01:/tmp/helm# helm upgrade redmine --values redmine.yaml stable/redmine --version 14.1.6
Release "redmine" has been upgraded. Happy Helming!
NAME: redmine
LAST DEPLOYED: Tue Jan 28 08:13:30 2020
NAMESPACE: default
STATUS: deployed
REVISION: 2
NOTES:
1. Get the Redmine URL:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w redmine'


  export SERVICE_IP=$(kubectl get svc --namespace default redmine --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
  echo "Redmine URL: http://$SERVICE_IP/"

2. Login with the following credentials

  echo Username: user
  echo Password: $(kubectl get secret --namespace default redmine -o jsonpath="{.data.redmine-password}" | base64 --decode)
root@techmi-k8s02-master01:/tmp/helm#

```

... and here's the redmine's container logs:
```
root@techmi-k8s02-master01:/tmp/helm# kubectl logs -f redmine-b76d55c84-66cp2
app-entrypoint.sh 08:37:37.46
app-entrypoint.sh 08:37:37.47 Welcome to the Bitnami redmine container
app-entrypoint.sh 08:37:37.47 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
app-entrypoint.sh 08:37:37.47 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
app-entrypoint.sh 08:37:37.48 Send us your feedback at containers@bitnami.com
app-entrypoint.sh 08:37:37.48
nami    INFO  Initializing redmine
redmine DEBUG Creating Redmine System User...
redmine DEBUG ==> Detected MariaDB/MySQL database
redmine INFO  Redmine has been already initialized, restoring...
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/conf/configuration.yml to /opt/bitnami/redmine/conf/configuration.yml
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/conf/database.yml to /opt/bitnami/redmine/conf/database.yml
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/public/plugin_assets to /opt/bitnami/redmine/public/plugin_assets
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/plugins to /opt/bitnami/redmine/plugins
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/files to /opt/bitnami/redmine/files
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at redmine-mariadb:3306
mysql-c TRACE [canConnect] Testing connection with 'bn_redmine' user
mysql-c TRACE [showDatabases] Getting databases for 'bn_redmine' user
mysql-c TRACE [execute] Executing: mysql -N -P 3306 -hredmine-mariadb -ubn_redmine -pmypass -e SHOW DATABASES;
mysql-c TRACE [execute] Result: {"code":0,"stdout":"bitnami_redmine\ninformation_schema\ntest\n","stderr":""}
mysql-c TRACE [showDatabases] Databases: bitnami_redmine
information_schema
test

mysql-c TRACE [canConnect] Connection with 'bn_redmine' user is successful
mysql-c INFO  MySQL server listening and working at redmine-mariadb:3306
redmine INFO  Generating new secret...
ruby    TRACE [runProgram] Executing: /opt/bitnami/ruby/bin/ruby /opt/bitnami/ruby/bin/bundle,exec,rake,generate_secret_token
redmine INFO  Migrating database...
ruby    TRACE [runProgram] Executing: /opt/bitnami/ruby/bin/ruby /opt/bitnami/ruby/bin/bundle,exec,rake,db:migrate
ruby    TRACE [runProgram] Executing: /opt/bitnami/ruby/bin/ruby /opt/bitnami/ruby/bin/bundle,exec,rake,redmine:plugins:migrate
redmine TRACE [configurePermissions] File to chown: /home/redmine
redmine TRACE [configurePermissions] File to chmod: /home/redmine
redmine TRACE [configurePermissions] File to chown: /opt/bitnami/redmine/tmp
redmine TRACE [configurePermissions] File to chmod: /opt/bitnami/redmine/tmp
redmine TRACE [configurePermissions] File to chown: /opt/bitnami/redmine/tmp/pdf
redmine TRACE [configurePermissions] File to chmod: /opt/bitnami/redmine/tmp/pdf
redmine TRACE [configurePermissions] File to chown: /bitnami/redmine/public/plugin_assets
redmine TRACE [configurePermissions] File to chmod: /bitnami/redmine/public/plugin_assets
redmine TRACE [configurePermissions] File to chown: /bitnami/redmine/files
redmine TRACE [configurePermissions] File to chmod: /bitnami/redmine/files
redmine TRACE [configurePermissions] File to chown: /opt/bitnami/redmine/logs
redmine TRACE [configurePermissions] File to chmod: /opt/bitnami/redmine/logs
redmine INFO
redmine INFO  ########################################################################
redmine INFO   Installation parameters for redmine:
redmine INFO     Persisted data and properties have been restored.
redmine INFO     Any input specified will not take effect.
redmine INFO   This installation requires no credentials.
redmine INFO  ########################################################################
redmine INFO
nami    INFO  redmine successfully initialized
app-entrypoint.sh 08:38:30.42 INFO  ==> Starting redmine...
run.sh 08:38:30.45 INFO  ==> Starting redmine...
Please configure your config/database.yml first
bundler: failed to load command: passenger (/opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/bin/passenger)
Bundler::ProductionError: You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the /opt/bitnami/redmine/Gemfile freeze
by running `bundle config unset deployment`.

You have deleted from the Gemfile:
* mysql2 (~> 0.5.0)
* pg (~> 1.1.4)

  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:466:in `ensure_equivalent_gemfile_and_lockfile'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:13:in `setup'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
  /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'
root@techmi-k8s02-master01:/tmp/helm#

```

**Comment by juan131** [comment]
Hi @lucamaggioni 

I was unable to reproduce the issue following the same steps you followed. The only difference between my testing environment and your is the `storageClass`. You are using `nfs-online`:

```yaml
persistence:
  ...
  storageClass: nfs-online
```

While I'm using the 'standard' one.

It looks like the `database.yml ` is not correctly generated during the initialization seems you obtain the warning message below when starting Redmine:

```
Please configure your config/database.yml first
```

However, that file was suppose to have been generated, see these other logs: 

```
ruby    TRACE [runProgram] Executing: /opt/bitnami/ruby/bin/ruby /opt/bitnami/ruby/bin/bundle,exec,rake,db:migrate
...
redmine TRACE [prepareDataToPersist] Preparing /opt/bitnami/redmine/conf/database.yml to persist in /bitnami/redmine/conf/database.yml
```

Could you check if you can reproduce the issue using the "standard" storageClass?

> IMPORTANT NOTE: (not related to this issue) I had to set here the maria db password because if I let the chart generate the random one, while performing an update, the secret is generated again, so the redmine app fails on startup during the upgrade because the password is wrong (should I open another issue?).

We are aware of it but it seems it's note explicitly detailed in the NOTES.txt nor the README.md, please free to open a different issue to discuss this. Thanks in advance

**Comment by lucamaggioni** [comment]
No change when using standard storageClass.

I've noticed that when I do not use persistence, the ACL flag is setted:

```
root@redmine-585b965599-hvp6h:/# ls -la /bitnami/redmine/conf/
total 32
drwxr-xr-x+ 2 root    root 4096 Feb 18 08:43 .
drwxrwxrwx+ 6 root    root 4096 Feb 18 08:44 ..
-rw-r--r--+ 1 bitnami root 8529 Feb 18 08:43 configuration.yml
-rw-r--r--+ 1 bitnami root 1517 Feb 18 08:43 database.yml

```

... while using persistence, is not setted:

```
root@redmine-5f9c7bd6db-j9f5n:/# ls -la /bitnami/redmine/conf/
total 24
drwxr-xr-x 2 root    root 4096 Feb 18 09:03 .
drwxrwxrwx 6 root    root 4096 Feb 18 09:03 ..
-rw-r--r-- 1 bitnami root 8529 Feb 18 09:03 configuration.yml
-rw-r--r-- 1 bitnami root 1517 Feb 18 09:03 database.yml
```

Anu suggestion?

**Comment by lucamaggioni** [comment]
The interesting thing is that with a persistent volume created manually in hostPath mode, everything works... but it's not scalable nor consistent:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: man-pv-redmine-01
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  volumeMode: Filesystem

```

**Comment by lucamaggioni** [comment]
I've also tried  to use a persistent volume claim created manually by me (just like the one in the last post)... which use the nfs, just like this:


```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: man-pv-redmine-01
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  nfs:
    path: /servicepool-earth/online/k8s02/manual/redmine-01
    server: 192.168.0.251
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  volumeMode: Filesystem

```


... and here we have another behaviour... the pod stuck in this way:



```
root@techmi-k8s02-master01:~# kubectl logs -n redmine-01 redmine-01-6496fb4d57-q6jtc -f
app-entrypoint.sh 13:46:54.34
app-entrypoint.sh 13:46:54.34 Welcome to the Bitnami redmine container
app-entrypoint.sh 13:46:54.35 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
app-entrypoint.sh 13:46:54.35 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
app-entrypoint.sh 13:46:54.35 Send us your feedback at containers@bitnami.com
app-entrypoint.sh 13:46:54.35
nami    INFO  Initializing redmine
redmine DEBUG Creating Redmine System User...
redmine DEBUG ==> Detected MariaDB/MySQL database
redmine INFO  Redmine has been already initialized, restoring...
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/conf/configuration.yml to /opt/bitnami/redmine/conf/configuration.yml
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/conf/database.yml to /opt/bitnami/redmine/conf/database.yml
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/public/plugin_assets to /opt/bitnami/redmine/public/plugin_assets
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/plugins to /opt/bitnami/redmine/plugins
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/files to /opt/bitnami/redmine/files
mysql-c INFO  Trying to connect to MySQL server

```

... here the pod stays in this state for minutes... and then die

**Comment by lucamaggioni** [comment]
By adding 1001 group to the nfs folder the problem was solved, so it was only a permission problem.

Thanks
Regards
Luca
