### ISSUE TITLE
[stable/grafana] grafana-sc-datasources init container fails in an Istio environment

### ISSUE THREAD

**Issue by nitinmohan87** [helm/charts#20699]
**Describe the bug**
`grafana-sc-datasources` init container fails to talk to kubernetes API server in an Istio environment. When a pod comes up in an istio-injected namespace, Istio forwards all traffic from the pod to `istio-proxy` container which starts as a regular container. So any kubernetes "init container" that must do network operations (e.g. talking to kubernetes API server) cannot run to completion because `istio-proxy` has not come up at all yet. So there is a race condition which prevents grafana-sc-datasources to run to completion.

```
prom-grafana-8668697b67-8x7sb                          0/3     Init:CrashLoopBackOff   3          90s
prom-kube-state-metrics-7c768c977f-blknt               2/2     Running                 2          89s
prom-prometheus-node-exporter-f94gw                    1/1     Running                 0          90s
prom-prometheus-operator-operator-5f6d66d66-m6vgd      3/3     Running                 2          89s
prometheus-prom-prometheus-operator-prometheus-0       4/4     Running                 0          58s
```
```
$ kubectl -n monitoring logs prom-grafana-8668697b67-8x7sb -c grafana-sc-datasources
Starting collector
No folder annotation was provided, defaulting to k8s-sidecar-target-directory
Selected resource type: ('secret', 'configmap')
Config for cluster api loaded...
2020-02-12 00:16:31,055 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7e2677ef90>: Failed to establish a new connec
tion: [Errno 111] Connection refused')': /api/v1/namespaces/monitoring/secrets
2020-02-12 00:16:31,056 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7e264b4190>: Failed to establish a new connec
tion: [Errno 111] Connection refused')': /api/v1/namespaces/monitoring/secrets
2020-02-12 00:16:31,056 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7e264b4250>: Failed to establish a new connec
tion: [Errno 111] Connection refused')': /api/v1/namespaces/monitoring/secrets
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 316, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f7e264b4210>: Failed to establish a new connection: [Errno 111] Connection refused

Traceback (most recent call last):
  File "/app/sidecar.py", line 54, in <module>
    main()
  File "/app/sidecar.py", line 47, in main
    namespace, folderAnnotation, res)
  File "/app/resources.py", line 44, in listResources
    ret = getattr(v1, _list_namespaced[resource])(namespace=namespace)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12884, in list_namespaced_secret
    (data) = self.list_namespaced_secret_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12984, in list_namespaced_secret_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 355, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 326, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='172.20.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/monitoring/secrets (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7e264b4210>: Failed
to establish a new connection: [Errno 111] Connection refused'))
```

**Version of Helm and Kubernetes**:
Kubernetes: 1.14
Helm: 2.13.1

**Which chart**:
stable/grafana

**What happened**:
1. Set up istio-injection to automatic for the `monitoring` namespace which injects istio-proxy sidecar into any new pods in that namespace.
2. Installed grafana through the prometheus operator setup.

Prometheus grafana pod crash loops during Init stage.

**What you expected to happen**:
Grafana pods to come up with istio injection enabled

**How to reproduce it** (as minimally and precisely as possible):
1. Setup Istio (mTLS/CNI don't make a difference). So a simple istio setup is enough.
2. Set monitoring namespace with istio-injection enabled label to automatically inject istio proxy.
3. Install grafana chart

Grafana pod will crash loop in the Init stage

I am hoping if there is a way to get around this issue.

**Comment by marshallford** [comment]
I'm running into this issue as well. I don't think this problem is solvable given this discussion: https://discuss.istio.io/t/k8s-istio-sidecar-injection-with-other-init-containers/845

**Comment by marshallford** [comment]
FYI for others: The chart has been updated since this issue was posted. The `grafana-sc-datasources` container was moved from an init container to the normal containers list.

**Comment by alfsch** [comment]
@marshallford I don't see where the grafana-sc-datasources is moved. Only for grafana-sc-dashboards this is done.

**Comment by marshallford** [comment]
@alfsch That very well could be. It's been a long time since I have looked at this chart, that said I vaguely remember some back and forth around the time of my comment (git reverts, PRs, etc) on the correct location of the `grafana-sc-*` containers.

**Comment by perezjasonr** [comment]
This should probably be reopened. I believe datasources is still init container per issue, I just ran into this as well.

https://github.com/grafana/helm-charts/issues/237

**Comment by quorak** [comment]
me too!

**Comment by bluefishforsale** [comment]
Also having this issue.

kube-prometheu-stack : 

this is new, after upgrading from version: 17.1.0 -> version: 20.0.1
and walking over values.yaml the sections by hand.

specifically with the log messages of :
` urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.32.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/monitoring/secrets?labelSelector=grafana_datasource (Caused by SSLError(SSLC
 ertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))`
 
 
 I have these settings for operator and grafana
 `
 grafana:
  enabled: true
  namespaceOverride: ""
  forceDeployDatasources: false
  forceDeployDashboards: false
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: America/Los_Angeles
  adminPassword: prom-operator
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    labels: {}
    hosts:
      - grafana.svc.cluster.local
    path: /
    tls: []
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      annotations: {}
      multicluster:
        global:
          enabled: false
        etcd:
          enabled: false
      provider:
        allowUiUpdates: false
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
        url: http://prom-kube-prometheus-stack-prometheus.monitoring:9090
      annotations: {}
      createPrometheusReplicasDatasources: false
      label: grafana_datasource
      `
