### ISSUE TITLE
Not able to configure external REDIS and POSTGRESS with airflow

### ISSUE THREAD

**Issue by gakhrejah** [helm/charts#21430]
Hey Team,

Thanks for this awesome helm template , its really useful

**Describe the bug**
I am facing an issue to configure external REDIS and POSTGRESS instance with the airflow .
So we have an RDS instance and Elastic cache instance on AWS and we want to configure this with our AIRFLOW. Below is the configmap for the environment variables

# Source: airflow/templates/configmap-env.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "release-name-env"
  namespace: airflow
  labels:
    app: airflow
    release: release-name
data:
  TZ: Etc/UTC
  POSTGRES_HOST: "xxxxxxx.rds.amazonaws.com"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "airflow"
  REDIS_HOST: "xxxxxxxxxxxxxx.cache.amazonaws.com"
  REDIS_PORT: "6379"
  AIRFLOW__CELERY__FLOWER_URL_PREFIX: ""
  AIRFLOW__CELERY__WORKER_CONCURRENCY: "1"
  FLOWER_PORT: "5555"
  AIRFLOW__CELERY__CELERY_CONCURRENCY: "5"
  EXECUTOR: "Celery"
  FERNET_KEY: ""
  DO_WAIT_INITDB: "false"
  AIRFLOW__CORE__DONOT_PICKLE: "false"
  AIRFLOW__CORE__DAGS_FOLDER: "/usr/local/airflow/dags"
  AIRFLOW__CORE__BASE_LOG_FOLDER: "/usr/local/airflow/logs"
  AIRFLOW__CORE__DAG_PROCESSOR_MANAGER_LOG_LOCATION: "/usr/local/airflow/logs/dag_processor_manager/dag_processor_manager.log"
  AIRFLOW__SCHEDULER__CHILD_PROCESS_LOG_DIRECTORY: "/usr/local/airflow/logs/scheduler"
  AIRFLOW__WEBSERVER__BASE_URL: "http://localhost:8080"
  AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "false"

**Version of Helm and Kubernetes**:
We are using EKS 
**Which chart**:

**What happened**:
Our Dags are getting in the queued state . We are not able to run those dags and below is the error LOGS

ingest_bigquery_data', '2020-03-10T08:33:00+00:00', '--local', '--pool', 'bq_realtime', '-sd', 'DAGS_FOLDER/bigquery_connector/pipeline_base.py']
[2020-03-11 11:10:06,611] {{timeout.py:42}} ERROR - Process timed out, PID: 398
10.109.232.194 - - [11/Mar/2020:11:10:06 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.14+"
[2020-03-11 11:10:06 +0000] [85] [INFO] Handling signal: ttin
[2020-03-11 11:10:06,714] {{celery_executor.py:226}} ERROR - Error sending Celery task:Timeout, PID: 398
Celery Task ID: ('capterra_google_analytics_data_import', 'ingest_bigquery_data', <Pendulum [2020-03-10T08:33:00+00:00]>, 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/functional.py", line 43, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 921, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/executors/celery_executor.py", line 120, in send_task_to_executor
    result = task.apply_async(args=[command], queue=queue)
  File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 568, in apply_async
    **options
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 775, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/lib/python3.7/site-packages/celery/app/amqp.py", line 559, in send_task_message
    **properties
  File "/usr/local/lib/python3.7/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 518, in _ensured
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kombu/messaging.py", line 187, in _publish
    channel = self.channel
  File "/usr/local/lib/python3.7/site-packages/kombu/messaging.py", line 209, in _get_channel
    channel = self._channel = channel()
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/functional.py", line 45, in __call__
    value = self.__value__ = self.__contract__()
  File "/usr/local/lib/python3.7/site-packages/kombu/messaging.py", line 224, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 868, in default_channel
    self.ensure_connection(**conn_opts)
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 430, in ensure_connection
    callback, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 283, in connect
    return self.connection
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 839, in connection
    self._connection = self._establish_connection()
  File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 794, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 941, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 923, in create_channel
    channel = self.Channel(connection)
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/redis.py", line 527, in __init__
    self.client.ping()
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1037, in ping
    return self.execute_command('PING')
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 994, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 502, in connect
    self.on_connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 576, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 637, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 290, in read_response
    response = self._buffer.readline()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 224, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 182, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/usr/local/lib/python3.7/site-packages/redis/_compat.py", line 58, in recv
    return sock.recv(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 43, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 398

**What you expected to happen**:
Dags should RUN

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
If i configure POSTGRESS and REDIS locally then it is working fine as expected

Please let me know if i am missing here , Let me know if you need more details on this

**Comment by gakhrejah** [comment]
Plus , so we have a helm template for executor="Kubernetesexecutor" and if we choose this executor do we require REDIS to be there
