### ISSUE TITLE
[stable/rocketchat] failed to connect to server [rocketchat-mongodb:27017] on first connect

### ISSUE THREAD

**Issue by nccurry** [helm/charts#21470]
**Describe the bug**
RocketChat pod cannot authentication with mongodb.

**Version of Helm and Kubernetes**:
```
[root@e6420 rocketchat]# helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

[root@e6420 rocketchat]# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3+k3s1", GitCommit:"5b17a175ce333dfb98cb8391afeb1f34219d9275", GitTreeState:"clean", BuildDate:"2020-02-27T07:28:53Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3+k3s1", GitCommit:"5b17a175ce333dfb98cb8391afeb1f34219d9275", GitTreeState:"clean", BuildDate:"2020-02-27T07:28:53Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
stable/rocketchat

**What happened**:
Deploying Rocketchat with the helm chart results in the RocketChat pod throwing the following error:
```
[root@e6420 rocketchat]# kubectl logs -f rocketchat-rocketchat-6bc74bdc8d-g82ss
/app/bundle/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^

MongoNetworkError: failed to connect to server [rocketchat-mongodb:27017] on first connect [MongoError: Authentication failed.
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/auth/auth_provider.js:46:25
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/auth/scram.js:215:18
    at Connection.messageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connect.js:334:5)
    at Connection.emit (events.js:210:5)
    at processMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:364:10)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:533:15)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  ok: 0,
  errmsg: 'Authentication failed.',
  code: 18,
  codeName: 'AuthenticationFailed',
  operationTime: [Timestamp],
  '$clusterTime': [Object],
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:431:11)
    at Pool.emit (events.js:210:5)
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:557:14
    at callback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connect.js:109:5)
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connect.js:352:21
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/auth/auth_provider.js:66:11
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/auth/scram.js:215:18
    at Connection.messageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connect.js:334:5)
    at Connection.emit (events.js:210:5)
    at processMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:364:10)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:533:15)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {}
}
```

**What you expected to happen**:
Functioning Rocketchat

**How to reproduce it** (as minimally and precisely as possible):
Use the following values.yml
```
image:
  tag: 3.0.3

mongodb:
  mongodbRootPassword: rocketchat
  mongodbUsername: rocketchat
  mongodbPassword: rocketchat
  mongodbDatabase: rocketchat

ingress:
  enabled: true
```
```
helm install rocketchat stable/rocketchat -f values.yml --namespace rocketchat
```

If I try to connect manually from another pod in the same namespace I get a similar error when trying with either the contents of MONGO_URL or MONGO_OPLOG_URL.

```
[root@fedora /]# mongo "mongodb://root:rocketchat@rocketchat-mongodb:27017/local?replicaSet=rs0&authSource=admin"
MongoDB shell version v4.2.3
connecting to: mongodb://rocketchat-mongodb:27017/local?authSource=admin&compressors=disabled&gssapiServiceName=mongodb&replicaSet=rs0
2020-03-15T21:26:05.061+0000 I  NETWORK  [js] Starting new replica set monitor for rs0/rocketchat-mongodb:27017
2020-03-15T21:26:05.061+0000 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Connecting to rocketchat-mongodb:27017
2020-03-15T21:26:05.063+0000 I  NETWORK  [ReplicaSetMonitor-TaskExecutor] Confirmed replica set for rs0 is rs0/rocketchat-mongodb-primary-0.rocketchat-mongodb-headless.rocketchat.svc.cluster.local:27017
2020-03-15T21:26:05.063+0000 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Connecting to rocketchat-mongodb-primary-0.rocketchat-mongodb-headless.rocketchat.svc.cluster.local:27017
2020-03-15T21:26:05.065+0000 I  NETWORK  [ReplicaSetMonitor-TaskExecutor] Confirmed replica set for rs0 is rs0/rocketchat-mongodb-primary-0.rocketchat-mongodb-headless.rocketchat.svc.cluster.local:27017
2020-03-15T21:26:05.108+0000 I  NETWORK  [js] Marking host rocketchat-mongodb-primary-0.rocketchat-mongodb-headless.rocketchat.svc.cluster.local:27017 as failed :: caused by :: Location40659: can't connect to new replica set master [rocketchat-mongodb-primary-0.rocketchat-mongodb-headless.rocketchat.svc.cluster.local:27017], err: AuthenticationFailed: Authentication failed.
2020-03-15T21:26:05.108+0000 E  QUERY    [js] Error: can't connect to new replica set master [rocketchat-mongodb-primary-0.rocketchat-mongodb-headless.rocketchat.svc.cluster.local:27017], err: AuthenticationFailed: Authentication failed. :
connect@src/mongo/shell/mongo.js:341:17
@(connect):2:6
2020-03-15T21:26:05.110+0000 F  -        [main] exception: connect failed
2020-03-15T21:26:05.110+0000 E  -        [main] exiting with code 1
```

```
[root@fedora /]# mongo "mongodb://rocketchat:rocketchat@rocketchat-mongodb:27017/rocketchat"
MongoDB shell version v4.2.3
connecting to: mongodb://rocketchat-mongodb:27017/rocketchat?compressors=disabled&gssapiServiceName=mongodb
2020-03-15T21:22:53.108+0000 E  QUERY    [js] Error: Authentication failed. :
connect@src/mongo/shell/mongo.js:341:17
@(connect):2:6
2020-03-15T21:22:53.111+0000 F  -        [main] exception: connect failed
2020-03-15T21:22:53.111+0000 E  -        [main] exiting with code 1
```

The startup logs for mongodb

```
[root@e6420 rocketchat]# kubectl logs rocketchat-mongodb-primary-0

Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MongoDB setup **
INFO  ==> Validating settings in MONGODB_* env vars...
INFO  ==> Initializing MongoDB...
INFO  ==> Deploying MongoDB with persisted data...
INFO  ==> No injected configuration files found. Creating default config files...
INFO  ==> Writing keyfile for replica set authentication: mMZ3LBBgwO /opt/bitnami/mongodb/conf/keyfile
INFO  ==> 
INFO  ==> ########################################################################
INFO  ==>  Installation parameters for MongoDB:
INFO  ==>    Persisted data and properties have been restored.
INFO  ==>    Any input specified will not take effect.
INFO  ==> (Passwords are not shown for security reasons)
INFO  ==> ########################################################################
INFO  ==> 
INFO  ==> Loading custom scripts...
find: '/docker-entrypoint-initdb.d/': No such file or directory
INFO  ==> ** MongoDB setup finished! **

INFO  ==> ** Starting MongoDB **
2020-03-15T20:56:45.205+0000 I STORAGE  [main] Max cache overflow file size custom option: 0
2020-03-15T20:56:45.205+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
2020-03-15T20:56:45.208+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2020-03-15T20:56:45.225+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/bitnami/mongodb/data/db 64-bit host=rocketchat-mongodb-primary-0
2020-03-15T20:56:45.225+0000 I CONTROL  [initandlisten] db version v4.0.12
2020-03-15T20:56:45.225+0000 I CONTROL  [initandlisten] git version: 5776e3cbf9e7afe86e6b29e22520ffb6766e95d4
2020-03-15T20:56:45.225+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0k  28 May 2019
2020-03-15T20:56:45.225+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2020-03-15T20:56:45.225+0000 I CONTROL  [initandlisten] modules: none
2020-03-15T20:56:45.225+0000 I CONTROL  [initandlisten] build environment:
2020-03-15T20:56:45.225+0000 I CONTROL  [initandlisten]     distmod: debian92
2020-03-15T20:56:45.225+0000 I CONTROL  [initandlisten]     distarch: x86_64
2020-03-15T20:56:45.225+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2020-03-15T20:56:45.225+0000 I CONTROL  [initandlisten] options: { config: "/opt/bitnami/mongodb/conf/mongodb.conf", net: { bindIpAll: true, ipv6: false, port: 27017, unixDomainSocket: { enabled: true, pathPrefix: "/opt/bitnami/mongodb/tmp" } }, processManagement: { fork: false, pidFilePath: "/opt/bitnami/mongodb/tmp/mongodb.pid" }, replication: { enableMajorityReadConcern: true, replSetName: "rs0" }, security: { authorization: "enabled", keyFile: "/opt/bitnami/mongodb/conf/keyfile" }, setParameter: { enableLocalhostAuthBypass: "true" }, storage: { dbPath: "/bitnami/mongodb/data/db", directoryPerDB: false, journal: { enabled: true } }, systemLog: { destination: "file", logAppend: true, logRotate: "reopen", path: "/opt/bitnami/mongodb/logs/mongodb.log", quiet: false, verbosity: 0 } }
2020-03-15T20:56:45.225+0000 I STORAGE  [initandlisten] Detected data files in /bitnami/mongodb/data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2020-03-15T20:56:45.226+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7430M,cache_overflow=(file_max=0M),session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2020-03-15T20:56:46.031+0000 I STORAGE  [initandlisten] WiredTiger message [1584305806:31965][1:0x7fd5fff7d080], txn-recover: Main recovery loop: starting at 9/18432 to 10/256
2020-03-15T20:56:46.032+0000 I STORAGE  [initandlisten] WiredTiger message [1584305806:32427][1:0x7fd5fff7d080], txn-recover: Recovering log 9 through 10
2020-03-15T20:56:46.121+0000 I STORAGE  [initandlisten] WiredTiger message [1584305806:121293][1:0x7fd5fff7d080], txn-recover: Recovering log 10 through 10
2020-03-15T20:56:46.182+0000 I STORAGE  [initandlisten] WiredTiger message [1584305806:182724][1:0x7fd5fff7d080], txn-recover: Set global recovery timestamp: 5e6e642600000001
2020-03-15T20:56:46.226+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(1584292902, 1)
2020-03-15T20:56:46.227+0000 I STORAGE  [initandlisten] Triggering the first stable checkpoint. Initial Data: Timestamp(1584292902, 1) PrevStable: Timestamp(0, 0) CurrStable: Timestamp(1584292902, 1)
2020-03-15T20:56:46.238+0000 I STORAGE  [initandlisten] Starting OplogTruncaterThread local.oplog.rs
2020-03-15T20:56:46.238+0000 I STORAGE  [initandlisten] The size storer reports that the oplog contains 8882 records totaling to 977430 bytes
2020-03-15T20:56:46.238+0000 I STORAGE  [initandlisten] Scanning the oplog to determine where to place markers for truncation
2020-03-15T20:56:46.290+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/bitnami/mongodb/data/db/diagnostic.data'
2020-03-15T20:56:46.293+0000 I REPL     [initandlisten] Rollback ID is 1
2020-03-15T20:56:46.294+0000 I REPL     [initandlisten] Recovering from stable timestamp: Timestamp(1584292902, 1) (top of oplog: { ts: Timestamp(1584292902, 1), t: 8 }, appliedThrough: { ts: Timestamp(0, 0), t: -1 }, TruncateAfter: Timestamp(0, 0))
2020-03-15T20:56:46.294+0000 I REPL     [initandlisten] Starting recovery oplog application at the stable timestamp: Timestamp(1584292902, 1)
2020-03-15T20:56:46.294+0000 I REPL     [initandlisten] No oplog entries to apply for recovery. Start point is at the top of the oplog.
2020-03-15T20:56:46.294+0000 I CONTROL  [LogicalSessionCacheRefresh] Sessions collection is not set up; waiting until next sessions refresh interval: Replication has not yet been configured
2020-03-15T20:56:46.295+0000 I REPL     [replexec-0] New replica set config in use: { _id: "rs0", version: 1, protocolVersion: 1, writeConcernMajorityJournalDefault: true, members: [ { _id: 0, host: "rocketchat-mongodb-primary-0.rocketchat-mongodb-headless.rocketchat.svc.cluster.local:27017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 5.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: -1, catchUpTakeoverDelayMillis: 30000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5e6c3fcc3dc1be524e3a12f9') } }
2020-03-15T20:56:46.295+0000 I REPL     [replexec-0] This node is rocketchat-mongodb-primary-0.rocketchat-mongodb-headless.rocketchat.svc.cluster.local:27017 in the config
2020-03-15T20:56:46.295+0000 I REPL     [replexec-0] transition to STARTUP2 from STARTUP
2020-03-15T20:56:46.295+0000 I REPL     [replexec-0] Starting replication storage threads
2020-03-15T20:56:46.295+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
2020-03-15T20:56:46.296+0000 I REPL     [replexec-0] transition to RECOVERING from STARTUP2
2020-03-15T20:56:46.296+0000 I REPL     [replexec-0] Starting replication fetcher thread
2020-03-15T20:56:46.296+0000 I REPL     [replexec-0] Starting replication applier thread
2020-03-15T20:56:46.296+0000 I REPL     [replexec-0] Starting replication reporter thread
2020-03-15T20:56:46.296+0000 I REPL     [rsSync-0] Starting oplog application
2020-03-15T20:56:46.296+0000 I REPL     [rsSync-0] transition to SECONDARY from RECOVERING
2020-03-15T20:56:46.296+0000 I REPL     [rsSync-0] conducting a dry run election to see if we could be elected. current term: 8
2020-03-15T20:56:46.296+0000 I REPL     [replexec-0] dry election run succeeded, running for election in term 9
2020-03-15T20:56:46.299+0000 I REPL     [replexec-0] election succeeded, assuming primary role in term 9
2020-03-15T20:56:46.299+0000 I REPL     [replexec-0] transition to PRIMARY from SECONDARY
2020-03-15T20:56:46.299+0000 I REPL     [replexec-0] Resetting sync source to empty, which was :27017
2020-03-15T20:56:46.299+0000 I REPL     [replexec-0] Entering primary catch-up mode.
2020-03-15T20:56:46.299+0000 I REPL     [replexec-0] Exited primary catch-up mode.
2020-03-15T20:56:46.299+0000 I REPL     [replexec-0] Stopping replication producer
2020-03-15T20:56:48.297+0000 I REPL     [rsSync-0] transition to primary complete; database writes are now permitted
```

**Comment by nccurry** [comment]
Executing the contents of secret that the rocketchat pod is using manually results in the same error:

```[root@fedora /]# mongo "mongodb://rocketchat:rocketchat@rocketchat-mongodb:27017/rocketchat"
MongoDB shell version v4.2.3
connecting to: mongodb://rocketchat-mongodb:27017/rocketchat?compressors=disabled&gssapiServiceName=mongodb
2020-03-15T21:22:53.108+0000 E  QUERY    [js] Error: Authentication failed. :
connect@src/mongo/shell/mongo.js:341:17
@(connect):2:6
2020-03-15T21:22:53.111+0000 F  -        [main] exception: connect failed
2020-03-15T21:22:53.111+0000 E  -        [main] exiting with code 1
```

**Comment by nccurry** [comment]
Using the following charts/values result in a successful deployment:
```
[root@e6420 rocketchat]# cat bitnami.mongodb.values.yml 
# https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml

mongodbRootPassword: rocketchat
mongodbUsername: rocketchat
mongodbPassword: rocketchat
mongodbDatabase: rocketchat

replicaSet:
  enabled: true
  replicas:
    secondary: 0
    arbiter: 0

ingress:
  enabled: true
```

```
[root@e6420 rocketchat]# cat stable.rocketchat.values.yml 
# https://github.com/helm/charts/blob/master/stable/rocketchat/values.yaml

image:
  tag: 3.0.3

externalMongodbUrl: "mongodb://rocketchat:rocketchat@mongodb-primary-0.mongodb-headless.rocketchat.svc.cluster.local:27017/rocketchat"
externalMongodbOplogUrl: "mongodb://root:rocketchat@mongodb-primary-0.mongodb-headless.rocketchat.svc.cluster.local:27017/local?replicaSet=rs0&authSource=admin"

mongodb:
  enabled: false

ingress:
  enabled: true

```

**Comment by nccurry** [comment]
This was probably being caused by stale pv's persistent credentials between deployments.
Closing
