### ISSUE TITLE
[stable/datadog] kubelet check missing permissions when run enabled `dedicated: true` rbac

### ISSUE THREAD

**Issue by cep21** [helm/charts#22045]
I see 403 in the agent logs.  I think switching the flag `clusterChecksRunner.rbac.dedicated` removed some permissions from the datadog agent that it needs to run the kubelet plugin.

Output of `agent status`
```
    kubelet (3.6.0)
    ---------------
      Instance ID: kubelet:d884b5186b651429 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubelet.d/conf.yaml.default
      Total Runs: 4,036
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-04-21 17:23:41.000000 UTC
      Last Successful Execution Date : Never
      Error: Unable to detect the kubelet URL automatically.
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 713, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/kubelet/kubelet.py", line 292, in check
          raise CheckException("Unable to detect the kubelet URL automatically.")
      datadog_checks.base.errors.CheckException: Unable to detect the kubelet URL automatically.
```

**Comment by cep21** [comment]
You may need to remove this `if` right here: https://github.com/helm/charts/blob/master/stable/datadog/templates/rbac.yaml#L87

**Comment by cep21** [comment]
CC: @clamoriniere

**Comment by ahmed-mez** [comment]
Thanks @cep21 for reporting this. We're working on a fix https://github.com/helm/charts/pull/22108
