### ISSUE TITLE
stable/graylog - Graylog is not working with self-signed certificate

### ISSUE THREAD

**Issue by zerowebcorp** [helm/charts#22609]
I have a self-generated ssl files added to the pods as  graylog.serverFiles

As per this instruction

`Each Graylog node coordinates with each other through the DNS entry exposed via the headless service, so when generating the certificates, be sure to include a SAN entry for *.graylog[-<suffix>].<namespace>.cluster.local (or your configured FQDN).`

I have added the SAN entry. However, graylog is not accepting this SSL because it is not in Java cacerts 

```
2020-05-31 15:16:04,267 WARN    [ProxiedResource] - Unable to call https://graylog-0.graylog.graylog-nonprod.svc.cluster.local:9000/api/system/inputstates on node <7da583d8-a8e2-4182-b0d0-58c8eccf5ed7>: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target - {}
```

The above message is being generated when I try to start the Input. 

Is there any way to add this into the cacert or override cacert file?

**Comment by GaneshbabuRamamoorthy** [comment]
@getvivekv did you fix this problem?

I am also getting the same issue, I am running graylog via helm with multiple nodes.

```
2020-07-28 13:03:02,859 ERROR   [AnyExceptionClassMapper] - Unhandled exception in REST resource - {}
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.
provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:198) ~[?:1.8.0_252]
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1967) ~[?:1.8.0_252]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:331) ~[?:1.8.0_252]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:325) ~[?:1.8.0_252]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1688) ~[?:1.8.0_252]
```

**Comment by GaneshbabuRamamoorthy** [comment]
Hi @getvivekv 

this script helped me to resolve the error,

https://github.com/helm/charts/issues/17399
