### ISSUE TITLE
[incubator/druid] java.lang.IllegalArgumentException: [/opt/data/segments/.../index.zip] does not exist

### ISSUE THREAD

**Issue by asdf2014** [helm/charts#22911]
**Describe the bug**

**Version of Helm and Kubernetes**:

3.2.3
1.18.3

**Which chart**:

https://hub.helm.sh/charts/incubator/druid

**What happened**:

After loading the sample data, an IllegalArgumentException is thrown.

```java
$ kubectl logs pod/druid-1592893333-historical-0

2020-06-22T23:41:00,213 INFO [ZKCoordinator--0] org.apache.druid.server.coordination.ZkCoordinator - Completed request [LOAD: wikipedia_2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z_2020-06-22T23:29:53.781Z]
2020-06-22T23:41:00,213 INFO [ZkCoordinator] org.apache.druid.server.coordination.ZkCoordinator - zNode[/druid/loadQueue/10.244.1.36:8083/wikipedia_2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z_2020-06-22T23:29:53.781Z] was removed
2020-06-22T23:41:05,207 INFO [ZKCoordinator--0] org.apache.druid.server.coordination.SegmentLoadDropHandler - Loading segment wikipedia_2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z_2020-06-22T23:29:53.781Z
2020-06-22T23:41:05,209 WARN [ZKCoordinator--0] org.apache.druid.server.coordination.BatchDataSegmentAnnouncer - No path to unannounce segment[wikipedia_2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z_2020-06-22T23:29:53.781Z]
2020-06-22T23:41:05,209 INFO [ZKCoordinator--0] org.apache.druid.server.SegmentManager - Told to delete a queryable for a dataSource[wikipedia] that doesn't exist.
2020-06-22T23:41:05,210 INFO [ZKCoordinator--0] org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager - Deleting directory[var/druid/segment-cache/wikipedia/2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z/2020-06-22T23:29:53.781Z/0]
2020-06-22T23:41:05,210 INFO [ZKCoordinator--0] org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager - Deleting directory[var/druid/segment-cache/wikipedia/2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z/2020-06-22T23:29:53.781Z]
2020-06-22T23:41:05,210 INFO [ZKCoordinator--0] org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager - Deleting directory[var/druid/segment-cache/wikipedia/2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z]
2020-06-22T23:41:05,210 INFO [ZKCoordinator--0] org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager - Deleting directory[var/druid/segment-cache/wikipedia]
2020-06-22T23:41:05,210 WARN [ZKCoordinator--0] org.apache.druid.server.coordination.SegmentLoadDropHandler - Unable to delete segmentInfoCacheFile[var/druid/segment-cache/info_dir/wikipedia_2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z_2020-06-22T23:29:53.781Z]
2020-06-22T23:41:05,210 ERROR [ZKCoordinator--0] org.apache.druid.server.coordination.SegmentLoadDropHandler - Failed to load segment for dataSource: {class=org.apache.druid.server.coordination.SegmentLoadDropHandler, exceptionType=class org.apache.druid.segment.loading.SegmentLoadingException, exceptionMessage=Exception loading segment[wikipedia_2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z_2020-06-22T23:29:53.781Z], segment=DataSegment{binaryVersion=9, id=wikipedia_2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z_2020-06-22T23:29:53.781Z, loadSpec={type=>local, path=>/opt/data/segments/wikipedia/2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z/2020-06-22T23:29:53.781Z/0/index.zip}, dimensions=[channel, cityName, comment, countryIsoCode, countryName, diffUrl, flags, isAnonymous, isMinor, isNew, isRobot, isUnpatrolled, namespace, page, regionIsoCode, regionName, user], metrics=[count, sum_added, sum_commentLength, sum_deleted, sum_delta, sum_deltaBucket], shardSpec=NumberedShardSpec{partitionNum=0, partitions=0}, lastCompactionState=null, size=6164665}}
org.apache.druid.segment.loading.SegmentLoadingException: Exception loading segment[wikipedia_2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z_2020-06-22T23:29:53.781Z]
	at org.apache.druid.server.coordination.SegmentLoadDropHandler.loadSegment(SegmentLoadDropHandler.java:262) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.server.coordination.SegmentLoadDropHandler.addSegment(SegmentLoadDropHandler.java:306) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.server.coordination.SegmentChangeRequestLoad.go(SegmentChangeRequestLoad.java:49) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.server.coordination.ZkCoordinator.lambda$childAdded$2(ZkCoordinator.java:147) ~[druid-server-0.18.1.jar:0.18.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalArgumentException: Cannot construct instance of `org.apache.druid.segment.loading.LocalLoadSpec`, problem: [/opt/data/segments/wikipedia/2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z/2020-06-22T23:29:53.781Z/0/index.zip] does not exist
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3922) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3853) ~[jackson-databind-2.10.2.jar:2.10.2]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.loadInLocation(SegmentLoaderLocalCacheManager.java:241) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.loadInLocationWithStartMarker(SegmentLoaderLocalCacheManager.java:230) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.loadSegmentWithRetry(SegmentLoaderLocalCacheManager.java:191) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegmentFiles(SegmentLoaderLocalCacheManager.java:163) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegment(SegmentLoaderLocalCacheManager.java:130) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.server.SegmentManager.getAdapter(SegmentManager.java:212) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.server.SegmentManager.loadSegment(SegmentManager.java:171) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.server.coordination.SegmentLoadDropHandler.loadSegment(SegmentLoadDropHandler.java:258) ~[druid-server-0.18.1.jar:0.18.1]
	... 8 more
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.apache.druid.segment.loading.LocalLoadSpec`, problem: [/opt/data/segments/wikipedia/2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z/2020-06-22T23:29:53.781Z/0/index.zip] does not exist
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1732) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:491) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:514) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:285) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3917) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3853) ~[jackson-databind-2.10.2.jar:2.10.2]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.loadInLocation(SegmentLoaderLocalCacheManager.java:241) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.loadInLocationWithStartMarker(SegmentLoaderLocalCacheManager.java:230) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.loadSegmentWithRetry(SegmentLoaderLocalCacheManager.java:191) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegmentFiles(SegmentLoaderLocalCacheManager.java:163) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegment(SegmentLoaderLocalCacheManager.java:130) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.server.SegmentManager.getAdapter(SegmentManager.java:212) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.server.SegmentManager.loadSegment(SegmentManager.java:171) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.server.coordination.SegmentLoadDropHandler.loadSegment(SegmentLoadDropHandler.java:258) ~[druid-server-0.18.1.jar:0.18.1]
	... 8 more
Caused by: java.lang.IllegalArgumentException: [/opt/data/segments/wikipedia/2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z/2020-06-22T23:29:53.781Z/0/index.zip] does not exist
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148) ~[guava-16.0.1.jar:?]
	at org.apache.druid.segment.loading.LocalLoadSpec.<init>(LocalLoadSpec.java:51) ~[druid-server-0.18.1.jar:0.18.1]
	at sun.reflect.GeneratedConstructorAccessor56.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:68) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3917) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3853) ~[jackson-databind-2.10.2.jar:2.10.2]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.loadInLocation(SegmentLoaderLocalCacheManager.java:241) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.loadInLocationWithStartMarker(SegmentLoaderLocalCacheManager.java:230) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.loadSegmentWithRetry(SegmentLoaderLocalCacheManager.java:191) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegmentFiles(SegmentLoaderLocalCacheManager.java:163) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.segment.loading.SegmentLoaderLocalCacheManager.getSegment(SegmentLoaderLocalCacheManager.java:130) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.server.SegmentManager.getAdapter(SegmentManager.java:212) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.server.SegmentManager.loadSegment(SegmentManager.java:171) ~[druid-server-0.18.1.jar:0.18.1]
	at org.apache.druid.server.coordination.SegmentLoadDropHandler.loadSegment(SegmentLoadDropHandler.java:258) ~[druid-server-0.18.1.jar:0.18.1]
	... 8 more
2020-06-22T23:41:05,214 INFO [ZkCoordinator] org.apache.druid.server.coordination.ZkCoordinator - zNode[/druid/loadQueue/10.244.1.36:8083/wikipedia_2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z_2020-06-22T23:29:53.781Z] was removed
2020-06-22T23:41:05,214 INFO [ZKCoordinator--0] org.apache.druid.server.coordination.ZkCoordinator - Completed request [LOAD: wikipedia_2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z_2020-06-22T23:29:53.781Z]
2020-06-22T23:41:05,570 DEBUG [qtp194672584-80] org.apache.druid.jetty.RequestLog - 10.244.1.1 GET //10.244.1.36:8083/status/health HTTP/1.1
```

**What you expected to happen**:

No error appears

**How to reproduce it** (as minimally and precisely as possible):

Load example data

**Anything else we need to know**:

**Comment by asdf2014** [comment]
@maver1ck @AWaterColorPen PTAL

**Comment by asdf2014** [comment]
That's odds, after using the HDFS cluster as the deep storage for the Apache Druid cluster, this problem disappeared. I can't find the index.zip file in Historical node, but it can be found in the MiddleManager node. This problem may occur due to the Segment can't be published from MiddleManager to Historical node. After further analysis, I assume that the root cause is that the value of `druid_storage_type` is local, and the MiddleManager and Historical node don't share the same Persistent Volumes. What do you think?

**Comment by AWaterColorPen** [comment]
@asdf2014 
Your are right! The default `druid_storage_type` value is `local`. We have to set the deep storage for the Apache Druid cluster.

**Comment by asdf2014** [comment]
Hi, @AWaterColorPen . Thanks for your comment. I built an HDFS cluster using the [Gradiant/charts](https://github.com/Gradiant/charts) . Should we include a HDFS chart in our [incubator/duird](https://hub.helm.sh/charts/incubator/druid) chart? Any good suggestions?

**Comment by AWaterColorPen** [comment]
From my understanding, Druid deep storage can be one of cloud storage, HDFS, or a shared filesystem. And Druid cluster can keep healthy without HDFS cluster. The HDFS cluster can serve many others not specified for Druid cluster. 

Maybe it is a lot heavy to include a HDFS chart in the `incubator/duird` chart.

**Comment by asdf2014** [comment]
@AWaterColorPen Yep, I agree with you. But there is still a situation where many customers sharing a single HDFS cluster will cause resource contention.

> Maybe it is a lot heavy to include a HDFS chart in the incubator/duird chart.

Can we just add the HDFS chart to the incubator/druid chart as a dependency? Then we don't need to maintain it and only load it when needed.

**Comment by AWaterColorPen** [comment]
@asdf2014 
If incubator/druid chart will read some values from the dependency to build our template yaml files, it is fine to add the HDFS chart as a dependency.
If no, it is better to install one separately.

Maybe you means a **druid-operator** chart just like [stable/prometheus-operator](https://hub.helm.sh/charts/stable/prometheus-operator) 😄. it is not only prometheus self, but includes multiple components.

**Comment by asdf2014** [comment]
@AWaterColorPen That's exactly what we need :+1::+1::+1:

**Comment by asdf2014** [comment]
@AWaterColorPen I found [druidio/druid-operator](https://hub.docker.com/r/druidio/druid-operator/tags), but it uses the 0.16.0 version of Apache Druid image, and I have encountered many issues when trying to use it.. :sweat_smile:

**Comment by asdf2014** [comment]
FYI, https://github.com/druid-io/druid-operator
