### ISSUE TITLE
[stable/airflow] missing kubernetes section example in values.yml

### ISSUE THREAD

**Issue by arthurzenika** [helm/charts#22941]
**Describe the bug**

When deploying airflow in kubernetes mode I get the following error : 

```
____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 37, in <module>
    args.func(args)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/bin/cli.py", line 900, in webserver
    app = cached_app_rbac(None) if settings.RBAC else cached_app(None)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/www/app.py", line 232, in cached_app
    app = create_app(config, testing)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/www/app.py", line 87, in create_app
    from airflow.www import views
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/www/views.py", line 97, in <module>
    dagbag = models.DagBag(settings.DAGS_FOLDER, store_serialized_dags=STORE_SERIALIZED_DAGS)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 95, in __init__
    executor = get_default_executor()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/executors/__init__.py", line 48, in get_default_executor
    DEFAULT_EXECUTOR = _get_executor(executor_name)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/executors/__init__.py", line 87, in _get_executor
    return KubernetesExecutor()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/executors/kubernetes_executor.py", line 715, in __init__
    self.kube_config = KubeConfig()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/executors/kubernetes_executor.py", line 291, in __init__
    self._validate()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/executors/kubernetes_executor.py", line 309, in _validate
    'In kubernetes mode the following must be set in the `kubernetes` '
airflow.exceptions.AirflowConfigException: In kubernetes mode the following must be set in the `kubernetes` config section: `dags_volume_claim` or `dags_volume_host` or `dags_in_image` or `git_repo and git_branch and git_dags_folder_mount_point`

```

**Version of Helm and Kubernetes**:
``` 
helm version                                                                               jeu. 25 juin 2020 09:30:50
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

**Which chart**:

stable/airflow

**What happened**:

```
Containers with unready status: [airflow-web]
```

**What you expected to happen**:

More documentation in https://github.com/helm/charts/blob/master/stable/airflow/values.yaml#L22

**Comment by thesuperzapper** [comment]
You must provide those configs when using `KubernetesExecutor`.

The reason we can't automatically set these from the `dags.git.*` is because there is a significant difference in the formatting of things like secrets for SSH keys. I am planning on moving the git-sync container to the same one that airflow uses, which means people will only have to set `dags.git.*` for it to work.

See here: https://github.com/helm/charts/issues/22637#issuecomment-637983741
