### ISSUE TITLE
[incubator/druid] failed to load data while using the druid from the helm chart

### ISSUE THREAD

**Issue by xsqian** [helm/charts#23250]
**Describe the bug**
Load Data Failed with Druid with this helm installation

**Version of Helm and Kubernetes**:
Helm: v3.2.4, AWS EKS 1.16

**Which chart**:
incubator/druid

**What happened**:
install helm chart on AWS EKS successfully

**What you expected to happen**:
However, when using the druid console to perform a data loading job, it failed

**How to reproduce it** (as minimally and precisely as possible):
re-load data will reproduce the same error

**Anything else we need to know**:

![image](https://user-images.githubusercontent.com/4673843/87864577-c0dafb80-c91e-11ea-9e96-f6aecc89a5b8.png)

`{
  "id": "index_parallel_wikipedia_cobkjmmp_2020-07-19T00:24:30.142Z",
  "groupId": "index_parallel_wikipedia_cobkjmmp_2020-07-19T00:24:30.142Z",
  "type": "index_parallel",
  "createdTime": "2020-07-19T00:24:30.148Z",
  "queueInsertionTime": "1970-01-01T00:00:00.000Z",
  "statusCode": "FAILED",
  "status": "FAILED",
  "runnerStatusCode": "WAITING",
  "duration": 64,
  "location": {
    "host": "10.0.2.143",
    "port": 8100,
    "tlsPort": -1
  },
  "dataSource": "wikipedia",
  "errorMsg": null
}`

**Comment by xsqian** [comment]
Here is the logs from the kubernetes:
`2020-07-19T05:13:42,871 INFO [main] org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=druid-1595135562-zookeeper-headless:2181 sessionTimeout=30000 watcher=org.apache.curator.ConnectionState@23a918c7
2020-07-19T05:13:42,894 INFO [main] org.apache.curator.framework.imps.CuratorFrameworkImpl - Default schema
2020-07-19T05:13:43,007 INFO [main] org.apache.druid.indexing.worker.WorkerCuratorCoordinator - WorkerCuratorCoordinator good to go sir. Server[10.0.2.190:8091]
2020-07-19T05:13:43,023 WARN [main-SendThread(druid-1595135562-zookeeper-headless:2181)] org.apache.zookeeper.ClientCnxn - Session 0x0 for server druid-1595135562-zookeeper-headless:2181, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address druid-1595135562-zookeeper-headless:2181 because it's not resolvable
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1001) ~[zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) [zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
`

**Comment by AWaterColorPen** [comment]
#22911 #23201 same issue.
The default druid_storage_type value is local. you have to set the your deep storage for the Apache Druid cluster

**Comment by xsqian** [comment]
@AWaterColorPen What would be the druid_storage_type for s3 on AWS eks? Do you have an example values.yaml? Thanks!

**Comment by AWaterColorPen** [comment]
@xsqian you can set `configVars.druid_storage_type` value to `s3` and add other s3 deep storage settings https://druid.apache.org/docs/latest/configuration/index.html#s3-deep-storage  under `configVars` when you install the chart.
for example: 
```
helm install --generate-name incubator/druid \
   --set configVars.druid_storage_type=s3 \
   --set configVars.druid_storage_bucket=balabala \
   --set configVars.druid_storage_ baseKey=balabala
```

**Comment by xsqian** [comment]
@AWaterColorPen great, that works!
Related to the issue, there was an error in the values.yaml file for the JVM option with "**--**Xms256m". However, this was fixed in https://github.com/helm/charts/commit/8e6b29a83197a7f27e59b6a11ea205eccd521582 Jul 28, 2020
You can close the issue now.
Thanks,
Xingsheng
