### ISSUE TITLE
[stable/jenkins] git client plugin timeout issue

### ISSUE THREAD

**Issue by gaurav8297** [helm/charts#3193]
**Which chart**:
stable/jenkins

**What happened**:
I want to increase the git global timeout so i updated JavaOpts:"-Dorg.jenkinsci.plugins.gitclient.Git.timeOut=20" in values.yaml and installed jenkins with helm but git global time out is still 10 min.

I want to use git push in jenkins pipeline with 20 min timeout.

**Comment by muniyalr** [comment]
Tried with git clone a huge repo with executor on the jenkins master node and it had taken 20 min as the timeout than the default value of 10, 

```
ERROR: Timeout after 20 minutes
ERROR: Error cloning remote repo 'origin'
git --version # timeout=20
```
even the java process was started with 20 min timeout on master.

**Comment by mattfarina** [comment]
cc @lachie83 @viglesiasce

**Comment by viglesiasce** [comment]
I believe that will only set it for the Jenkins master. You will need to set the value in the executor image.

**Comment by gaurav8297** [comment]
Hey @viglesiasce i did set the env var in agent pod as **JAVA_OPTS="Dorg.jenkinsci.plugins.gitclient.Git.timeOut=200"** but now also git push is timed out after 10 min.

Here's the log
```
Pushing HEAD to branch refs/heads/master at repo deis
 > git --version # timeout=200
using GIT_SSH to set credentials 
 > git push ssh://<my-repo> HEAD:refs/heads/master -f
```
I don't understand why there is no # timeout=200 in git push command.

Thanks

**Comment by Bhavya525k** [comment]
git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://myrepo,git +refs/heads/*:refs/remotes/origin/*
ERROR: Timeout after 10 minutes
ERROR: Error fetching remote repo 'origin'


Getting the above error while running gradle build on Jenkins.  Steps taken so far

1. Tried to create SSH credential in Bitbucket and then added it to jenkins.  

Please help me resolve the issue. Thanks.

**Comment by TestingPCF** [comment]
Please provide the help on below Error.
Building in workspace C:\Program Files (x86)\Jenkins\workspace\TestingPCF3
Cloning the remote Git repository
Cloning repository https://github.com/TestingPCF/spring-boot-web-thymeleaf_new.git
 > C:\Abhishek\SVN\Software\Git-2.7.0-64-bit.exe init C:\Program Files (x86)\Jenkins\workspace\TestingPCF3 # timeout=10
ERROR: Timeout after 10 minutes
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init C:\Program Files (x86)\Jenkins\workspace\TestingPCF3
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:787)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:579)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
	at hudson.scm.SCM.checkout(SCM.java:504)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
	at hudson.model.Run.execute(Run.java:1819)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: hudson.plugins.git.GitException: Command "C:\Abhishek\SVN\Software\Git-2.7.0-64-bit.exe init C:\Program Files (x86)\Jenkins\workspace\TestingPCF3" returned status code -1:
stdout:
