### ISSUE TITLE
Kafka pod recover issue with NFS PV

### ISSUE THREAD

**Issue by js-315385995** [helm/charts#3898]
**Is this a request for help?**:
YES

**Version of Helm and Kubernetes**:
helm: 2.8
Kubernetes: 1.8.5

**Which chart**:
https://github.com/kubernetes/charts/tree/master/incubator/kafka

**What happened**:

Kafka service failed with exception after pod deletion.

**What you expected to happen**:

Kafka service should come up again.

**How to reproduce it** (as minimally and precisely as possible):

We were trying to run a Kafka cluster on Kubernetes using NFS provisioner. The cluster came up fine. However when we killed one of the Kafka pods, the replacement pod failed to come up.

Persistent volume before pod deletion:

    mount
    10.102.32.184:/export/pvc-ce1461b3-1b38-11e8-a88e-005056073f99 on /opt/kafka/data type nfs4     (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=10.133.40.245,local_lock=none,addr=10.102.32.184)

    ls -al /opt/kafka/data/logs
    total 4
    drwxr-sr-x 2 99 99 152 Feb 26 21:07 .
    drwxrwsrwx 3 99 99  18 Feb 26 21:07 ..
    -rw-r--r-- 1 99 99   0 Feb 26 21:07 .lock
    -rw-r--r-- 1 99 99   0 Feb 26 21:07 cleaner-offset-checkpoint
    -rw-r--r-- 1 99 99  57 Feb 26 21:07 meta.properties
    -rw-r--r-- 1 99 99   0 Feb 26 21:07 recovery-point-offset-checkpoint
    -rw-r--r-- 1 99 99   0 Feb 26 21:07 replication-offset-checkpoint

    cat /opt/kafka/data/logs   /meta.properties
    #
    Mon Feb 26 21:07:08 UTC 2018
    version=0
    broker.id=1003

Deleting the pod:

    kubectl delete pod kafka-iced-unicorn-1

Persistent volume in newly created pod:

    ls -al /opt/kafka/data/logs
    total 4
    drwxr-sr-x 2 99 99 180 Feb 26 21:10 .
    drwxrwsrwx 3 99 99  18 Feb 26 21:07 ..
    -rw-r--r-- 1 99 99   0 Feb 26 21:10 .kafka_cleanshutdown
    -rw-r--r-- 1 99 99   0 Feb 26 21:07 .lock
    -rw-r--r-- 1 99 99   0 Feb 26 21:07 cleaner-offset-checkpoint
    -rw-r--r-- 1 99 99  57 Feb 26 21:07 meta.properties
    -rw-r--r-- 1 99 99   0 Feb 26 21:07 recovery-point-offset-checkpoint
    -rw-r--r-- 1 99 99   0 Feb 26 21:07 replication-offset-checkpoint

    cat /opt/kafka/data/logs/meta.properties
    
    #Mon Feb 26 21:07:08 UTC 2018
    version=0
    broker.id=1003

We see the following error in the Kafka logs:

    [2018-02-26 21:26:40,606] INFO [ThrottledRequestReaper-Produce], Starting          (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
    [2018-02-26 21:26:40,711] FATAL [Kafka Server 1002], Fatal error during         KafkaServer startup.     Prepare to shutdown (kafka.server.KafkaServer)
    java.io.IOException: Invalid argument
    at java.io.UnixFileSystem.createFileExclusively(Native Method)
    at java.io.File.createNewFile(File.java:1012)
    at kafka.utils.FileLock.<init>(FileLock.scala:28)
    at kafka.log.LogManager$$anonfun$lockLogDirs$1.apply(LogManager.scala:104)
    at kafka.log.LogManager$$anonfun$lockLogDirs$1.apply(LogManager.scala:103)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at kafka.log.LogManager.lockLogDirs(LogManager.scala:103)
    at kafka.log.LogManager.<init>(LogManager.scala:65)
    at kafka.server.KafkaServer.createLogManager(KafkaServer.scala:648)
    at kafka.server.KafkaServer.startup(KafkaServer.scala:208)
    at io.confluent.support.metrics.SupportedServerStartable.startup(SupportedServerStartable.java:102)
    at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:49)
    [2018-02-26 21:26:40,713] INFO [Kafka Server 1002], shutting down (kafka.server.KafkaServer)
    [2018-02-26 21:26:40,715] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)

Has anyone come across this issue with NFS provisioner?

**Anything else we need to know**:
This scenario works fine using Rook provisioner or using no persistent volume at all.

**Comment by parrinha** [comment]
Hello, 

Did you find something? I have some similar behavior, but when  the pod goes down, the restart failed to initialize, and the logs of the pod shows warning about corrupted offsets and a clean action like this:

[2018-04-30 14:32:27,052] WARN Found a corrupted index file due to requirement failed: Corrupt index found, index file (/opt/kafka/data/logs/__consumer_offsets-35/00000000000000000000.index) has non-zero size but the last offset is 0 which is no larger than the base offset 0.}. deleting /opt/kafka/data/logs/__consumer_offsets-35/00000000000000000000.timeindex, /opt/kafka/data/logs/__consumer_offsets-35/00000000000000000000.index, and /opt/kafka/data/logs/__consumer_offsets-35/00000000000000000000.txnindex and rebuilding index... (kafka.log.Log)
[2018-04-30 14:32:27,218] INFO Loading producer state from offset 0 for partition __consumer_offsets-5 with message format version 2 (kafka.log.Log)

I can see hundreds of restart tries, but the pod only goes up again when I enter in the pvc and delete all the __consumer_offset* directories. 

I'm using NFS pv also. 

Regards

**Comment by js-315385995** [comment]
Hi Parrina,

I've only ever seen that error when the pv was full.

Thanks

**Comment by parrinha** [comment]
Thanks,

Finally I managed to fix this updating the "readiness probe" parameter, incrementing the initialDelaySeconds  so this gives Kafka time for fix the corrupted indexes and start the pod again before the readinessProbe return any result. I understand that other way is to delete this offsets as and administrator task and let Kafka recreate them, so the node can start again without problems.

Regards
