### ISSUE TITLE
[stable/kubernetes-dashboard] cluster-admin not found

### ISSUE THREAD

**Issue by caulagi** [helm/charts#4102]
I am able to install kubernetes-dashboard 0.5.3 but get the following error when installing the latest version -

```bash
$ helm install stable/kubernetes-dashboard --version 0.5.3
NAME:   lazy-coral
LAST DEPLOYED: Sun Mar 11 14:45:31 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Pod(related)
NAME                                              READY  STATUS             RESTARTS  AGE
lazy-coral-kubernetes-dashboard-7fbdb7db4f-dh5tq  0/1    ContainerCreating  0         0s

==> v1/Service
NAME                             TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)  AGE
lazy-coral-kubernetes-dashboard  ClusterIP  100.64.180.159  <none>       80/TCP   1s

==> v1beta1/Deployment
NAME                             DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
lazy-coral-kubernetes-dashboard  1        1        1           0          1s


NOTES:
*********************************************************************************
*** PLEASE BE PATIENT: kubernetes-dashboard may take a few minutes to install ***
*********************************************************************************

Get the Kubernetes Dashboard URL by running:
  export POD_NAME=$(kubectl get pods -n default -l "app=kubernetes-dashboard,release=lazy-coral" -o jsonpath="{.items[0].metadata.name}")
  echo http://127.0.0.1:9090/
  kubectl -n default port-forward $POD_NAME 9090:9090

$ helm install stable/kubernetes-dashboard
Error: release deadly-jackal failed: roles.rbac.authorization.k8s.io "deadly-jackal-kubernetes-dashboard" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["secrets"], ResourceNames:["kubernetes-dashboard-key-holder"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["secrets"], ResourceNames:["deadly-jackal-kubernetes-dashboard"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["secrets"], ResourceNames:["kubernetes-dashboard-key-holder"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["secrets"], ResourceNames:["deadly-jackal-kubernetes-dashboard"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["secrets"], ResourceNames:["kubernetes-dashboard-key-holder"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["secrets"], ResourceNames:["deadly-jackal-kubernetes-dashboard"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["configmaps"], ResourceNames:["kubernetes-dashboard-settings"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["configmaps"], ResourceNames:["kubernetes-dashboard-settings"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["services"], ResourceNames:["heapster"], APIGroups:[""], Verbs:["proxy"]} PolicyRule{Resources:["services/proxy"], ResourceNames:["heapster"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services/proxy"], ResourceNames:["http:heapster:"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services/proxy"], ResourceNames:["https:heapster:"], APIGroups:[""], Verbs:["get"]}] user=&{system:serviceaccount:kube-system:tiller 214d2a02-252e-11e8-9426-023924570e5a [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[clusterroles.rbac.authorization.k8s.io "cluster-admin" not found]
```

It seems like it is related to https://github.com/kubernetes/charts/pull/3935. What am I missing? More details below -

**Version of Helm and Kubernetes**: Helm version 2.8.1. Kubernetes version 1.8.6. The cluster was created with kops 1.8.1 with default options `kops create cluster <redacted> --cloud aws --zones us-west-1a`

**Comment by caulagi** [comment]
I got misled by just seeing charts get installed for 0.5.3 but I see the following errors after the chart is installed -

```bash
2018/03/12 19:15:56 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2018/03/12 19:15:56 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: unexpected object: &Secret{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Data:map[string][]byte{},Type:,StringData:map[string]string{},}
2018/03/12 19:15:58 Storing encryption key in a secret
panic: secrets is forbidden: User "system:serviceaccount:default:tiller" cannot create secrets in the namespace "kube-system"

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.(*rsaKeyHolder).init(0xc4203a69c0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:131 +0x2d3
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.NewRSAKeyHolder(0x1a7ee00, 0xc4203cfd40, 0xc4203cfd40, 0x127b962)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:170 +0x83
main.initAuthManager(0x1a7e300, 0xc420052900, 0xc420591c68, 0x1)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:183 +0x12f
main.main()
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:101 +0x28c
```

This is already tracked in https://github.com/kubernetes/charts/issues/3104, so I will close this. Excuse the noise.
