### ISSUE TITLE
[incubator/fluentd-cloudwatch] header field value cannot include CR/LF

### ISSUE THREAD

**Issue by jacobtomlinson** [helm/charts#4732]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-29T10:10:42Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: incubator/fluentd-cloudwatch

**What happened**: I get an error when running the chart

```
2018-04-05 10:18:09 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-04-05 10:18:10 +0000 error_class="ArgumentError" error="header field value cannot include CR/LF" plugin_id="object:2ac2e86fe1c4"
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http/header.rb:20:in `block in initialize_http_header'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http/header.rb:16:in `each'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http/header.rb:16:in `initialize_http_header'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http/generic_request.rb:44:in `initialize'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http/request.rb:15:in `initialize'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/handler.rb:143:in `new'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/handler.rb:143:in `build_net_request'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/handler.rb:74:in `block in transmit'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/handler.rb:123:in `block in session'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/connection_pool.rb:99:in `session_for'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/handler.rb:121:in `session'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/handler.rb:73:in `transmit'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/handler.rb:47:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/plugins/content_length.rb:12:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/json/error_handler.rb:8:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/signature_v4.rb:66:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/retry_errors.rb:92:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/json/handler.rb:11:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/request.rb:70:in `send_request'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-cloudwatchlogs-1.2.0/lib/aws-sdk-cloudwatchlogs/client.rb:725:in `describe_log_groups'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:403:in `log_group_exists?'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:152:in `block in write'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:144:in `each'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:144:in `write'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:354:in `write_chunk'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:333:in `pop'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/output.rb:342:in `try_flush'
  2018-04-05 10:18:09 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/output.rb:149:in `run'
```

**What you expected to happen**: No errors

**How to reproduce it** (as minimally and precisely as possible): Run with minimal config and defaults

```
rbac:
  create: true
awsRegion: '<REGION>'
logGroupName: '<LOG GROUP>'
```

**Anything else we need to know**: The error seems to be coming from the cloudwatch fluentd plugin. I have raised ryotarai/fluent-plugin-cloudwatch-logs#101 with them.

**Comment by varu3** [comment]
I think It's from [r61359](https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/61359) because HTTP doesn't allow CRLF in their header value. I upgraded aws-sdk-core and solved.

I rewrite this Dockerfile the latest version of aws-sdk-core and built it.
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v0.12/debian-cloudwatch/Dockerfile

**Comment by jacobtomlinson** [comment]
Ok great thanks! Could you share the updated docker file? Or even better raise a PR against that repo to fix it upstream.

**Comment by jacobtomlinson** [comment]
I am still getting the same error with the latest versions of `aws-sdk-core`, `aws-sdk-cloudwatch` and `fluent-plugin-cloudwatch-logs`.

I've added to the dockerfile

```
RUN gem update aws-sdk-core aws-sdk-cloudwatchlogs fluent-plugin-cloudwatch-logs
```

Error

```
2018-04-10 12:07:40 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-04-10 12:07:38 +0000 error_class="ArgumentError" error="header field value cannot include CR/LF" plugin_id="object:2b1e275954f0"
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http/header.rb:20:in `block in initialize_http_header'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http/header.rb:16:in `each'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http/header.rb:16:in `initialize_http_header'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http/generic_request.rb:44:in `initialize'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http/request.rb:15:in `initialize'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/handler.rb:143:in `new'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/handler.rb:143:in `build_net_request'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/handler.rb:74:in `block in transmit'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/handler.rb:123:in `block in session'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/connection_pool.rb:99:in `session_for'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/handler.rb:121:in `session'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/handler.rb:73:in `transmit'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/net_http/handler.rb:47:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/plugins/content_length.rb:12:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/json/error_handler.rb:8:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/signature_v4.rb:66:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/retry_errors.rb:92:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/json/handler.rb:11:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-3.19.0/lib/seahorse/client/request.rb:70:in `send_request'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-cloudwatchlogs-1.2.0/lib/aws-sdk-cloudwatchlogs/client.rb:725:in `describe_log_groups'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:403:in `log_group_exists?'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:152:in `block in write'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:144:in `each'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:144:in `write'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:354:in `write_chunk'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:333:in `pop'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/output.rb:342:in `try_flush'
  2018-04-10 12:07:40 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/output.rb:149:in `run'
```

**Comment by alhafoudh** [comment]
any update?

**Comment by jacobtomlinson** [comment]
I ended up building my own image with the following `Dockerfile` to get it working:

```
# from fluent/fluentd-kubernetes-daemonset:v0.12-alpine-cloudwatch

# RUN gem update aws-sdk-core aws-sdk-cloudwatchlogs fluent-plugin-cloudwatch-logs

# -----------------------------------------------

FROM fluent/fluentd:v0.12.33-debian

MAINTAINER Eduardo Silva <eduardo@treasure-data.com>
USER root
WORKDIR /home/fluent
ENV PATH /home/fluent/.gem/ruby/2.3.0/bin:$PATH

RUN buildDeps="sudo make gcc g++ libc-dev ruby-dev libffi-dev" \
     && apt-get update \
     && apt-get upgrade -y \
     && apt-get install \
     -y --no-install-recommends \
     $buildDeps \
    && echo 'gem: --no-document' >> /etc/gemrc \
    && gem install fluent-plugin-secure-forward \
    && gem install fluent-plugin-record-reformer \
    && gem install fluent-plugin-detect-exceptions -v 0.0.9 \
    && gem install aws-sdk-core -v 3.19.0 \
    && gem install fluent-plugin-cloudwatch-logs -v 0.4.5 \
    && gem install fluent-plugin-kubernetes_metadata_filter \
    && gem install ffi \
    && gem install fluent-plugin-systemd -v 0.0.8 \
    && SUDO_FORCE_REMOVE=yes \
    apt-get purge -y --auto-remove \
                  -o APT::AutoRemove::RecommendsImportant=false \
                  $buildDeps \
 && rm -rf /var/lib/apt/lists/* \
    && gem sources --clear-all \
    && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

# Copy configuration files
COPY ./conf/fluent.conf /fluentd/etc/
COPY ./conf/systemd.conf /fluentd/etc/
COPY ./conf/kubernetes.conf /fluentd/etc/

# Copy plugins
COPY plugins /fluentd/plugins/
COPY entrypoint.sh /fluentd/entrypoint.sh

# Environment variables
ENV FLUENTD_OPT=""
ENV FLUENTD_CONF="fluent.conf"

# jemalloc is memory optimization only available for td-agent
# td-agent is provided and QA'ed by treasuredata as rpm/deb/.. package
# -> td-agent (stable) vs fluentd (edge)
#ENV LD_PRELOAD="/usr/lib/libjemalloc.so.2"

# Run Fluentd
CMD ["/fluentd/entrypoint.sh"]

```

**Comment by KevinJMcGarry** [comment]
@jacobtomlinson can you confirm your Dockerfile? I copied it and used the image it built in place of my fluent/fluentd-kubernetes-daemonset image, but my pods are exiting with this error --

error: Could not find 'bundler' (>= 0) among 62 total gem(s)
Checked in 'GEM_PATH=/home/fluent/.gem/ruby/2.3.0:/root/.gem/ruby/2.3.0:/var/lib/gems/2.3.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0:/usr/share/rubygems-integration/2.3.0:/usr/share/rubygems-integration/all', execute `gem env` for more information

**Comment by kawaja** [comment]
I have same issue with:

Helm:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Config:
```
logGroupName: <log group>
awsRegion: <region>
rbac:
   serviceAccountName: <account with cluster admin account>
image:
  tag: cloudwatch
extraVars:
  - "{ name: FLUENT_UID, value: '0' }"
```

Docker Image:
```
sha256:e8783ac6e589a2d1ba14f06fe4903837f3d8c3c43dae563a27accf7e73d7f0e6

$ docker inspect <container>
[
  {
    "Image": "sha256:e8783ac6e589a2d1ba14f06fe4903837f3d8c3c43dae563a27accf7e73d7f0e6",
    .
    .
    "Config": {
      .
      .
      "Labels": {
        "Description": "Fluentd docker image",
        "Vendor": "Fluent Organization",
        "Version": "1.1",
        .
        .
       }
    }
  }
]
```

Log Excerpt:
```
  2018-08-20 10:52:58 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:403:in `log_group_exists?'
  2018-08-20 10:52:58 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:152:in `block in write'
  2018-08-20 10:52:58 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:144:in `each'
  2018-08-20 10:52:58 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:144:in `write'
  2018-08-20 10:52:58 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/buffer.rb:354:in `write_chunk'
  2018-08-20 10:52:58 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/buffer.rb:333:in `pop'
  2018-08-20 10:52:58 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/output.rb:342:in `try_flush'
  2018-08-20 10:52:58 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.4.0/gems/fluentd-0.12.43/lib/fluent/output.rb:149:in `run'
2018-08-20 10:52:59 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 7, namespace_cache_api_updates: 11, pod_cache_api_updates: 11, id_cache_miss: 11
2018-08-20 10:53:01 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-08-20 10:52:57 +0000 error_class="ArgumentError" error="header field value cannot include CR/LF" plugin_id="object:2af660313f2c"
  2018-08-20 10:53:01 +0000 [warn]: suppressed same stacktrace
2018-08-20 10:53:03 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-08-20 10:53:02 +0000 error_class="ArgumentError" error="header field value cannot include CR/LF" plugin_id="object:2af660313f2c"
  2018-08-20 10:53:03 +0000 [warn]: suppressed same stacktrace
2018-08-20 10:53:05 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-08-20 10:53:10 +0000 error_class="ArgumentError" error="header field value cannot include CR/LF" plugin_id="object:2af660313f2c"
  2018-08-20 10:53:05 +0000 [warn]: suppressed same stacktrace
2018-08-20 10:53:11 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-08-20 10:53:24 +0000 error_class="ArgumentError" error="header field value cannot include CR/LF" plugin_id="object:2af660313f2c"
  2018-08-20 10:53:11 +0000 [warn]: suppressed same stacktrace
2018-08-20 10:53:26 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-08-20 10:53:58 +0000 error_class="ArgumentError" error="header field value cannot include CR/LF" plugin_id="object:2af660313f2c"
  2018-08-20 10:53:26 +0000 [warn]: suppressed same stacktrace
2018-08-20 10:53:34 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 7, namespace_cache_api_updates: 11, pod_cache_api_updates: 11, id_cache_miss: 11
2018-08-20 10:54:00 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-08-20 10:55:09 +0000 error_class="ArgumentError" error="header field value cannot include CR/LF" plugin_id="object:2af660313f2c"
  2018-08-20 10:54:00 +0000 [warn]: suppressed same stacktrace
2018-08-20 10:54:07 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 7, namespace_cache_api_updates: 11, pod_cache_api_updates: 11, id_cache_miss: 11
2018-08-20 10:54:38 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 7, namespace_cache_api_updates: 11, pod_cache_api_updates: 11, id_cache_miss: 11
2018-08-20 10:55:10 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 7, namespace_cache_api_updates: 11, pod_cache_api_updates: 11, id_cache_miss: 11
2018-08-20 10:55:11 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-08-20 10:57:19 +0000 error_class="ArgumentError" error="header field value cannot include CR/LF" plugin_id="object:2af660313f2c"
  2018-08-20 10:55:11 +0000 [warn]: suppressed same stacktrace
2018-08-20 10:55:41 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 7, namespace_cache_api_updates: 11, pod_cache_api_updates: 11, id_cache_miss: 11
```
