### ISSUE TITLE
Fluentd-CloudWatch 

### ISSUE THREAD

**Issue by jicowan** [helm/charts#5196]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.9.0-rc4", GitCommit:"030d2c066bcf5a37931e0169b7921f3758d97095", GitTreeState:"clean"}

**Which chart**:
Fluentd-CloudFormation

**What happened**:
Failed to push logs to CloudWatch
Logs from container: 
```
2018-04-23 01:49:15 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-04-23 01:49:16 +0000 error_class="ArgumentError" error="header field value cannot include CR/LF" plugin_id="object:2adb4e1df0ac"
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http/header.rb:20:in `block in initialize_http_header'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http/header.rb:16:in `each'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http/header.rb:16:in `initialize_http_header'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http/generic_request.rb:44:in `initialize'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/2.3.0/net/http/request.rb:15:in `initialize'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/seahorse/client/net_http/handler.rb:141:in `new'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/seahorse/client/net_http/handler.rb:141:in `build_net_request'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/seahorse/client/net_http/handler.rb:72:in `block in transmit'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/seahorse/client/net_http/handler.rb:121:in `block in session'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/seahorse/client/net_http/connection_pool.rb:96:in `session_for'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/seahorse/client/net_http/handler.rb:119:in `session'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/seahorse/client/net_http/handler.rb:71:in `transmit'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/seahorse/client/net_http/handler.rb:45:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/seahorse/client/plugins/content_length.rb:12:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/aws-sdk-core/json/error_handler.rb:8:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/aws-sdk-core/plugins/request_signer.rb:88:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/aws-sdk-core/plugins/retry_errors.rb:89:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/aws-sdk-core/json/handler.rb:11:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/seahorse/client/plugins/response_target.rb:21:in `call'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/seahorse/client/request.rb:70:in `send_request'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.10.50/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.4.0/lib/fluent/plugin/out_cloudwatch_logs.rb:298:in `log_group_exists?'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.4.0/lib/fluent/plugin/out_cloudwatch_logs.rb:121:in `block in write'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.4.0/lib/fluent/plugin/out_cloudwatch_logs.rb:113:in `each'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.4.0/lib/fluent/plugin/out_cloudwatch_logs.rb:113:in `write'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:354:in `write_chunk'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/buffer.rb:333:in `pop'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/output.rb:342:in `try_flush'
  2018-04-23 01:49:15 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.33/lib/fluent/output.rb:149:in `run'
2018-04-23 01:49:16 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-04-23 01:49:18 +0000 error_class="ArgumentError" error="header field value cannot include CR/LF" plugin_id="object:2adb4e1df0ac"
  2018-04-23 01:49:16 +0000 [warn]: suppressed same stacktrace
2018-04-23 01:49:16 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 6, namespace_cache_api_updates: 6, pod_cache_api_updates: 6, id_cache_miss: 6
2018-04-23 01:49:18 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-04-23 01:49:22 +0000 error_class="ArgumentError" error="header field value cannot include CR/LF" plugin_id="object:2adb4e1df0ac"
  2018-04-23 01:49:18 +0000 [warn]: suppressed same stacktrace
2018-04-23 01:49:22 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-04-23 01:49:31 +0000 error_class="ArgumentError" error="header field value cannot include CR/LF" plugin_id="object:2adb4e1df0ac"
  2018-04-23 01:49:22 +0000 [warn]: suppressed same stacktrace
2018-04-23 01:49:31 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-04-23 01:49:45 +0000 error_class="ArgumentError" error="header field value cannot include CR/LF" plugin_id="object:2adb4e1df0ac"
  2018-04-23 01:49:31 +0000 [warn]: suppressed same stacktrace
2018-04-23 01:49:45 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-04-23 01:50:15 +0000 error_class="ArgumentError" error="header field value cannot include CR/LF" plugin_id="object:2adb4e1df0ac"
  2018-04-23 01:49:45 +0000 [warn]: suppressed same stacktrace
2018-04-23 01:49:46 +0000 [info]: stats - namespace_cache_size: 2, pod_cache_size: 6, namespace_cache_api_updates: 6, pod_cache_api_updates: 6, id_cache_miss: 6
```

**What you expected to happen**:
Logs should be pushed to CloudWatch 

**How to reproduce it** (as minimally and precisely as possible):
Instantiate the chart. 

**Anything else we need to know**:
There's been a recent update to the Ruby gem for Fluentd.  See: 
https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/pull/91.

**Comment by etiennetremel** [comment]
Until this get fixed, using a previous sha256 for the image tag works: 
```
image: fluent/fluentd-kubernetes-daemonset
imageTag: v0.12.33-cloudwatch@sha256:0a6763c174ac9456ae3b71ae4485ff5f9ab7ecd5a1542e71248a72c54666f02c
```
