### ISSUE TITLE
Pod CrashLoopBackOff

### ISSUE THREAD

**Issue by IvanBiv** [helm/charts#5493]
[stable/kubernetes-dashboard]

`$helm install stable/kubernetes-dashboard`

```
kube@server2:/$ kubectl get pods
NAME                                                 READY     STATUS              RESTARTS   AGE
quiet-dingo-kubernetes-dashboard-b98c5885c-ppvr6     0/1       CrashLoopBackOff    7          13m


kube@server2:/$ kubectl describe pods quiet-dingo-kubernetes-dashboard-b98c5885c-ppvr6
Name:           quiet-dingo-kubernetes-dashboard-b98c5885c-ppvr6
Namespace:      default
Node:           server1/192.168.88.11
Start Time:     Thu, 10 May 2018 12:04:58 +0300
Labels:         app=kubernetes-dashboard
                kubernetes.io/cluster-service=true
                pod-template-hash=654714417
                release=quiet-dingo
Annotations:    <none>
Status:         Running
IP:             10.244.2.99
Controlled By:  ReplicaSet/quiet-dingo-kubernetes-dashboard-b98c5885c
Containers:
  kubernetes-dashboard:
    Container ID:  docker://937d70edbfc9442ed40828d80f8f9c1dd86706aa7a6f5a76d533a7235d95e650
    Image:         k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3
    Image ID:      docker-pullable://k8s.gcr.io/kubernetes-dashboard-amd64@sha256:dc4026c1b595435ef5527ca598e1e9c4343076926d7d62b365c44831395adbd0
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      --auto-generate-certificates
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 10 May 2018 12:22:57 +0300
      Finished:     Thu, 10 May 2018 12:23:09 +0300
    Ready:          False
    Restart Count:  8
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:        100m
      memory:     50Mi
    Liveness:     http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /certs from kubernetes-dashboard-certs (rw)
      /tmp from tmp-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from quiet-dingo-kubernetes-dashboard-token-fzgwx (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  kubernetes-dashboard-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  quiet-dingo-kubernetes-dashboard
    Optional:    false
  tmp-volume:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  quiet-dingo-kubernetes-dashboard-token-fzgwx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  quiet-dingo-kubernetes-dashboard-token-fzgwx
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                From               Message
  ----     ------                 ----               ----               -------
  Normal   Scheduled              21m                default-scheduler  Successfully assigned quiet-dingo-kubernetes-dashboard-b98c5885c-ppvr6 to server1
  Normal   SuccessfulMountVolume  21m                kubelet, server1   MountVolume.SetUp succeeded for volume "tmp-volume"
  Normal   SuccessfulMountVolume  21m                kubelet, server1   MountVolume.SetUp succeeded for volume "quiet-dingo-kubernetes-dashboard-token-fzgwx"
  Normal   SuccessfulMountVolume  21m                kubelet, server1   MountVolume.SetUp succeeded for volume "kubernetes-dashboard-certs"
  Normal   Pulling                21m                kubelet, server1   pulling image "k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3"
  Normal   Pulled                 21m                kubelet, server1   Successfully pulled image "k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3"
  Normal   Created                20m (x4 over 21m)  kubelet, server1   Created container
  Normal   Started                20m (x4 over 21m)  kubelet, server1   Started container
  Normal   Pulled                 19m (x4 over 21m)  kubelet, server1   Container image "k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3" already present on machine
  Warning  BackOff                1m (x86 over 20m)  kubelet, server1   Back-off restarting failed container

```

In logs I see:
```
panic: secrets is forbidden: User "system:serviceaccount:default:quiet-dingo-kubernetes-dashboard" cannot create secrets in the namespace "kube-system"

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.(*rsaKeyHolder).init(0xc4200c8640)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:131 +0x2d3
github.com/kubernetes/dashboard/src/app/backend/auth/jwe.NewRSAKeyHolder(0x1a7ee00, 0xc420457c20, 0xc420457c20, 0x127b962)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/auth/jwe/keyholder.go:170 +0x83
main.initAuthManager(0x1a7e300, 0xc42001b0e0, 0xc420599c68, 0x1)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:183 +0x12f
main.main()
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:101 +0x28c
```

What is happened?

UPDATE
If set `rbac.clusterAdminRole=true` than work, I see this is bad way.

**Comment by nordri** [comment]
Hello,
I'm facing the same problem.
Dashboard is trying to create secrets outside his namespace and fails.
The only workaround till now is to grant admin privileges but is not recommended.
Could be a bug?
Cheers!

**Comment by ozbillwang** [comment]
I have the same issue and fixed with clusterAdminRole to true. Thanks.

But my question is, could we split all charts into seperate repositories? With that I can try old versions, if latest version doesn't work for me.

Does helm support to install chart with release/version?
