### ISSUE TITLE
STABLE/REDIS - ReplyError: Ready check failed: NOAUTH Authentication required. with "new" redis master/slave deploy

### ISSUE THREAD

**Issue by pkelleratwork** [helm/charts#5583]
**Is this a request for help?**: YES

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG**

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
1.9.3
```

**Which chart**: 
stable/redis

**What happened**: redis no longer works with cluster - getting `ReplyError: Ready check failed: NOAUTH Authentication required.` 

**What you expected to happen**: it should start like the single node version

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

This was never an issue with the single instance redis helm deploy. I depended on that for my cluster - it worked wonderfully. I had to set up a new instance on the cluster and got the "**master/slave**" setup by default. I cannot spin up the instance now because the apis fail to connect to redis and master/slave throw errors.

**api log**
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
ReplyError: Ready check failed: NOAUTH Authentication required.
    at parseError (/ronin/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/ronin/node_modules/redis-parser/lib/parser.js:303:14)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c node build/main.js
Directory: /ronin
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/ronin/yarn-error.log".
```

**redis master log**
```
744:C 15 May 19:01:27.000 # Failed opening the RDB file dump.rdb (in server root dir /bitnami/redis/data) for saving: Permission denied
28:M 15 May 19:01:27.047 # Background saving error
28:M 15 May 19:01:27.047 # Connection with slave 100.96.2.43:6379 lost.
28:M 15 May 19:01:27.048 # SYNC failed. BGSAVE child returned an error
28:M 15 May 19:01:28.003 * Slave 100.96.2.43:6379 asks for synchronization
28:M 15 May 19:01:28.003 * Full resync requested by slave 100.96.2.43:6379
28:M 15 May 19:01:28.003 * Starting BGSAVE for SYNC with target: disk
28:M 15 May 19:01:28.003 * Background saving started by pid 745
745:C 15 May 19:01:28.004 # Failed opening the RDB file dump.rdb (in server root dir /bitnami/redis/data) for saving: Permission denied
28:M 15 May 19:01:28.051 # Background saving error
28:M 15 May 19:01:28.051 # Connection with slave 100.96.2.43:6379 lost.
28:M 15 May 19:01:28.051 # SYNC failed. BGSAVE child returned an error
28:M 15 May 19:01:29.005 * Slave 100.96.2.43:6379 asks for synchronization
28:M 15 May 19:01:29.005 * Full resync requested by slave 100.96.2.43:6379
28:M 15 May 19:01:29.005 * Starting BGSAVE for SYNC with target: disk
28:M 15 May 19:01:29.006 * Background saving started by pid 746
746:C 15 May 19:01:29.006 # Failed opening the RDB file dump.rdb (in server root dir /bitnami/redis/data) for saving: Permission denied
28:M 15 May 19:01:29.053 # Background saving error
28:M 15 May 19:01:29.053 # Connection with slave 100.96.2.43:6379 lost.
28:M 15 May 19:01:29.053 # SYNC failed. BGSAVE child returned an error
28:M 15 May 19:01:30.009 * Slave 100.96.2.43:6379 asks for synchronization
28:M 15 May 19:01:30.009 * Full resync requested by slave 100.96.2.43:6379
28:M 15 May 19:01:30.009 * Starting BGSAVE for SYNC with target: disk
28:M 15 May 19:01:30.009 * Background saving started by pid 747
747:C 15 May 19:01:30.010 # Failed opening the RDB file dump.rdb (in server root dir /bitnami/redis/data) for saving: Permission denied
28:M 15 May 19:01:30.056 # Background saving error
28:M 15 May 19:01:30.056 # Connection with slave 100.96.2.43:6379 lost.
28:M 15 May 19:01:30.056 # SYNC failed. BGSAVE child returned an error
28:M 15 May 19:01:31.011 * Slave 100.96.2.43:6379 asks for synchronization
28:M 15 May 19:01:31.012 * Full resync requested by slave 100.96.2.43:6379
28:M 15 May 19:01:31.012 * Starting BGSAVE for SYNC with target: disk
28:M 15 May 19:01:31.012 * Background saving started by pid 748
748:C 15 May 19:01:31.012 # Failed opening the RDB file dump.rdb (in server root dir /bitnami/redis/data) for saving: Permission denied
28:M 15 May 19:01:31.058 # Background saving error
28:M 15 May 19:01:31.058 # Connection with slave 100.96.2.43:6379 lost.
28:M 15 May 19:01:31.058 # SYNC failed. BGSAVE child returned an error
28:M 15 May 19:01:32.015 * Slave 100.96.2.43:6379 asks for synchronization
28:M 15 May 19:01:32.015 * Full resync requested by slave 100.96.2.43:6379
28:M 15 May 19:01:32.015 * Starting BGSAVE for SYNC with target: disk
28:M 15 May 19:01:32.015 * Background saving started by pid 754
754:C 15 May 19:01:32.015 # Failed opening the RDB file dump.rdb (in server root dir /bitnami/redis/data) for saving: Permission denied
28:M 15 May 19:01:32.061 # Background saving error
28:M 15 May 19:01:32.061 # Connection with slave 100.96.2.43:6379 lost.
28:M 15 May 19:01:32.062 # SYNC failed. BGSAVE child returned an error
28:M 15 May 19:01:33.019 * Slave 100.96.2.43:6379 asks for synchronization
28:M 15 May 19:01:33.019 * Full resync requested by slave 100.96.2.43:6379
28:M 15 May 19:01:33.019 * Starting BGSAVE for SYNC with target: disk
28:M 15 May 19:01:33.019 * Background saving started by pid 755
755:C 15 May 19:01:33.019 # Failed opening the RDB file dump.rdb (in server root dir /bitnami/redis/data) for saving: Permission denied
```

**redis slave error**
```
42:S 15 May 19:02:24.205 * Master replied to PING, replication can continue...
42:S 15 May 19:02:24.206 * Partial resynchronization not possible (no cached master)
42:S 15 May 19:02:24.207 * Full resync from master: ba37d577a4663ff72a0d7fd1d7d17367c8960af7:0
42:S 15 May 19:02:24.296 # I/O error reading bulk count from MASTER: Resource temporarily unavailable
42:S 15 May 19:02:25.207 * Connecting to MASTER test-redis-master:6379
42:S 15 May 19:02:25.208 * MASTER <-> SLAVE sync started
42:S 15 May 19:02:25.208 * Non blocking connect for SYNC fired the event.
42:S 15 May 19:02:25.209 * Master replied to PING, replication can continue...
42:S 15 May 19:02:25.210 * Partial resynchronization not possible (no cached master)
42:S 15 May 19:02:25.211 * Full resync from master: ba37d577a4663ff72a0d7fd1d7d17367c8960af7:0
42:S 15 May 19:02:25.299 # I/O error reading bulk count from MASTER: Resource temporarily unavailable
42:S 15 May 19:02:26.211 * Connecting to MASTER test-redis-master:6379
42:S 15 May 19:02:26.212 * MASTER <-> SLAVE sync started
42:S 15 May 19:02:26.212 * Non blocking connect for SYNC fired the event.
42:S 15 May 19:02:26.213 * Master replied to PING, replication can continue...
42:S 15 May 19:02:26.214 * Partial resynchronization not possible (no cached master)
42:S 15 May 19:02:26.215 * Full resync from master: ba37d577a4663ff72a0d7fd1d7d17367c8960af7:0
42:S 15 May 19:02:26.302 # I/O error reading bulk count from MASTER: Resource temporarily unavailable
42:S 15 May 19:02:27.214 * Connecting to MASTER test-redis-master:6379
42:S 15 May 19:02:27.215 * MASTER <-> SLAVE sync started
42:S 15 May 19:02:27.216 * Non blocking connect for SYNC fired the event.
42:S 15 May 19:02:27.216 * Master replied to PING, replication can continue...
42:S 15 May 19:02:27.217 * Partial resynchronization not possible (no cached master)
42:S 15 May 19:02:27.218 * Full resync from master: ba37d577a4663ff72a0d7fd1d7d17367c8960af7:0
42:S 15 May 19:02:27.304 # I/O error reading bulk count from MASTER: Resource temporarily unavailable
42:S 15 May 19:02:28.217 * Connecting to MASTER test-redis-master:6379
42:S 15 May 19:02:28.218 * MASTER <-> SLAVE sync started
42:S 15 May 19:02:28.218 * Non blocking connect for SYNC fired the event.
42:S 15 May 19:02:28.218 * Master replied to PING, replication can continue...
42:S 15 May 19:02:28.220 * Partial resynchronization not possible (no cached master)
42:S 15 May 19:02:28.220 * Full resync from master: ba37d577a4663ff72a0d7fd1d7d17367c8960af7:0
42:S 15 May 19:02:28.307 # I/O error reading bulk count from MASTER: Resource temporarily unavailable
```

**Comment by ryandawsonuk** [comment]
I suspect this was due to accessing redis without authentication. I hit `NOAUTH Authentication required` when switching to the chart and found it went away when I set `usePassword: false`
