### ISSUE TITLE
[stable/spinnaker] Fresh install unable to complete 'kubernetes to prod'

### ISSUE THREAD

**Issue by flah00** [helm/charts#6175]
**Is this a request for help?**:
Maybe?

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug, I think

**Version of Helm and Kubernetes**:
helm 2.9.1 and k8s 1.8.4

**Which chart**:
stable/spinnaker

**What happened**:
```yaml
storageBucket: org-spinnaker

minio:
  accessKey: KEY
  secretKey: SECRET

accounts:
- name: quay
  address: https://quay.io
  repositories:
    - org/image
  username: org+jenkins
  password: PW

kubeConfig:
  enabled: true
  contexts:
    - dev

deck:
  host: spinnaker.org.com
  port: 9000
  protocol: http
  ingress:
    enabled: true
    tls:
      - secretName: org-tls
        hosts:
          - spinnaker.org.com
    annotations:
      ingress.kubernetes.io/whitelist-source-range: >
        10.10.0.0/16
gate:
  allowedOriginsPattern: '^https?://(?:localhost|127.0.0.1|[^/]+\.org\.com|69.112.144.18)(?::[1-9]\d*)?/?$'
```

**What you expected to happen**:

Load balancer modal should appear, but page is unchanged

**How to reproduce it** (as minimally and precisely as possible):
Instructions from [kubernetes from source to prod](https://www.spinnaker.io/guides/tutorials/codelabs/kubernetes-source-to-prod/) 
1. Create application, name nginx, fill in email, create
2. Click on 'load balancers'
3. Click 'create load balancer'
4. Modal should load, but JS error in console appears instead 

```
TypeError: Cannot read property 'providerVersion' of null
    at versionSelection.service.ts:21
    at u (angular.js:16832)
    at angular.js:16876
    at d.$digest (angular.js:17971)
    at angular.js:18200
    at i (angular.js:6274)
    at angular.js:6554 "Possibly unhandled rejection: {}"
```

**Anything else we need to know**:

1. Also seeing possibly unrelated error in clouddriver 
```
2018-06-18 14:21:19.052 ERROR 1 --- [ecutionAction-1] .d.r.p.a.DockerRegistryImageCachingAgent : Could not load tags for org/image

retrofit.RetrofitError: timeout
        at retrofit.RetrofitError.networkError(RetrofitError.java:27) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395) ~[retrofit-1.9.0.jar:na]
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
        at com.sun.proxy.$Proxy125.getTags(Unknown Source) ~[na:na]
        at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$DockerRegistryService$getTags.call(Unknown Source) ~[na:na]
        at com.netflix.spinnaker.clouddriver.docker.registry.api.v2.client.DockerRegistryClient$_getTags_closure12.doCall(DockerRegistryClient.groovy:340) ~[clouddriver-docker-1.775.0-SNAPSHOT.jar:1.775.0-SNAPSHOT]
```
2. Also noticed spinnaker configmap has `vic-goog/image` as repository name, for my quay

**Comment by flah00** [comment]
Changes I had to make, with quay

@viglesiasce any interest in folding these changes in? I could open a PR (without the appr stuff). I suppose the `repository` key should be available in the values.yaml? 

```diff
diff --git a/stable/spinnaker/Chart.yaml b/stable/spinnaker/Chart.yaml
index 611d2118..ba26dc3e 100644
--- a/stable/spinnaker/Chart.yaml
+++ b/stable/spinnaker/Chart.yaml
@@ -1,7 +1,7 @@
 apiVersion: v1
 description: Open source, multi-cloud continuous delivery platform for releasing software changes with high velocity and confidence.
 name: spinnaker
-version: 0.5.0
+version: 0.5.1
 appVersion: 1.6.0
 home: http://spinnaker.io/
 sources:
diff --git a/stable/spinnaker/requirements.yaml b/stable/spinnaker/requirements.yaml
index a48134d9..68b88633 100644
--- a/stable/spinnaker/requirements.yaml
+++ b/stable/spinnaker/requirements.yaml
@@ -1,3 +1,14 @@
+appr:
+- name: quay.io/org/redis-chart
+  version: :beta
+  repository: appr://
+- name: quay.io/org/minio-chart
+  version: :beta
+  repository: appr://
+- name: quay.io/org/jenkins-chart
+  version: :beta
+  repository: appr://
+
 dependencies:
 - name: redis
   version: 1.1.6
diff --git a/stable/spinnaker/templates/configmap/spinnaker-config.yaml b/stable/spinnaker/templates/configmap/spinnaker-config.yaml
index 8689d794..9a65460c 100644
--- a/stable/spinnaker/templates/configmap/spinnaker-config.yaml
+++ b/stable/spinnaker/templates/configmap/spinnaker-config.yaml
@@ -76,18 +76,14 @@ data:
         - name: {{ $context }}
           kubeconfigFile: /tmp/kube/config
           context: {{ $context }}
-          dockerRegistries:
-          {{- range $index, $account := $.Values.accounts }}
-          - accountName: {{ $account.name }}
-          {{ end }}
+          configureImagePullSecrets: true
+          providerVersion: V2
         {{ end }}
         {{- else }}
         - name: local
           serviceAccount: true
-          dockerRegistries:
-            {{- range $index, $account := .Values.accounts }}
-            - accountName: {{ $account.name }}
-            {{- end }}
+          configureImagePullSecrets: true
+          providerVersion: V2
         {{- end }}
     dockerRegistry:
       {{ if .Values.accounts }}
@@ -251,18 +247,12 @@ data:
         - name: {{ $context }}
           kubeconfigFile: /tmp/kube/{{ $.Values.kubeConfig.secretKey }}
           context: {{ $context }}
-          dockerRegistries:
-          {{- range $index, $account := $.Values.accounts }}
-          - accountName: {{ $account.name }}
-          {{ end }}
+          providerVersion: V2
         {{ end }}
         {{- else }}
         - name: local
           serviceAccount: true
-          dockerRegistries:
-            {{- range $index, $account := .Values.accounts }}
-            - accountName: {{ $account.name }}
-            {{- end }}
+          providerVersion: V2
         {{- end }}
     dockerRegistry:
       enabled: true
@@ -468,7 +458,7 @@ data:
         primaryCredentials:
           name: {{ $account.name }}
           address: {{ $account.address }}
-          repository: vic-goog/gceme
+          repository: org/dockerfiles
           {{- if $account.username }}
           username: {{ $account.username }}
           email: {{ $account.email }}
```
