### ISSUE TITLE
jenkins/stable install not working. Failed Loading plugin Pipeline: Multibranch v2.19 (workflow-multibranch)

### ISSUE THREAD

**Issue by mtbvang** [helm/charts#6356]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
 kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-rancher1", GitCommit:"f6320ca7027d8244abb6216fbdb73a2b3eb2f4f9", GitTreeState:"clean", BuildDate:"2018-05-29T22:28:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

**Which chart**:
stable/jenkins

**What happened**:
I'm trying to install jenkins using `helm install stable/jenkins --namespace cicd` and going to the login url http://172.42.42.13:8080/login I'm getting the following browser error:

172.42.42.13 didn’t send any data.
ERR_EMPTY_RESPONSE

In the jenkins container I see:
```
SEVERE: Failed Loading plugin Pipeline: Multibranch v2.19 (workflow-multibranch)
java.io.IOException: Pipeline: Multibranch v2.19 failed to load.
 - Pipeline: Job v2.15 is older than required. To fix, install v2.21 or later.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:655)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:515)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jun 27, 2018 2:55:47 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Pipeline: Declarative v1.3 (pipeline-model-definition)
java.io.IOException: Pipeline: Declarative v1.3 failed to load.
 - Pipeline: Multibranch v2.19 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:655)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:515)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jun 27, 2018 2:55:47 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Loading plugin Pipeline v2.5 (workflow-aggregator)
java.io.IOException: Pipeline v2.5 failed to load.
 - Pipeline: Multibranch v2.19 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:655)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:515)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

It also seems to take the init container about 40mins to download all the plugins or they don't download at all and the jenkins container never comes up.  The init container logs contain curl timeout issues. 
```
....
> branch-api depends on cloudbees-folder:6.1.0,scm-api:2.2.7,structs:1.9
27/06/2018 16:25:10curl: (28) Operation timed out after 20000 milliseconds with 0 out of 0 bytes received
27/06/2018 16:25:1014:25:10 Failure (28) Retrying in 1 seconds...
27/06/2018 16:25:31curl: (28) Operation timed out after 20001 milliseconds with 0 out of 0 bytes received
27/06/2018 16:25:3114:25:31 Failure (28) Retrying in 1 seconds...
....
27/06/2018 16:35:33WAR bundled plugins:
27/06/2018 16:35:33
27/06/2018 16:35:33
27/06/2018 16:35:33Installed plugins:
27/06/2018 16:35:33ace-editor:1.1
27/06/2018 16:35:33apache-httpcomponents-client-4-api:4.5.5-3.0
...
27/06/2018 16:35:33workflow-support:2.19
27/06/2018 16:35:33Cleaning up locks
```
The servers/VMs that the containers are running on have internet access and a dig and curl of the plugin update site works. I'm wondering why the jenkins container can't reach the plugin update site.

**What you expected to happen**:
Jenkins installs and I can access the GUI in the browser URL output by running 

```
export SERVICE_IP=$(kubectl get svc --namespace cicd jenkins-v1 --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
  echo http://$SERVICE_IP:8080/login
```

**How to reproduce it** (as minimally and precisely as possible):
helm install stable/jenkins --namespace cicd  --name jenkins-v1

**Anything else we need to know**:
I am installing this on a cluster created by Rancher running on some local vagrant VMs. The VM OS is Ubuntu 16.04.

**Comment by Nodraak** [comment]
If you update [this line](https://github.com/kubernetes/charts/blob/63653fd596a88f2cf45139999155ec60d7b422b2/stable/jenkins/values.yaml#L90) and replace v2.15 by v2.21 does it work better?

**Comment by uwehdaub** [comment]
You can delete the plugin workflow-job from the list, because it's automatically installed as a dependency of workflow-aggregator. And then it's also at the right version. At least this is what I do.

**Comment by BrunoQuaresma** [comment]
It was fixed -> https://github.com/helm/charts/pull/6988

**Comment by davidkarlsen** [comment]
Is this ok with the latest chart version so that this issue can be closed?

**Comment by BrunoQuaresma** [comment]
@davidkarlsen I think so.
