### ISSUE TITLE
incubator/elasticsearch/templates/master-svc.yaml contains ClusterIP:None, which prevents clusters from spinning up

### ISSUE THREAD

**Issue by sokoow** [helm/charts#6971]
**Is this a request for help?**:
NO
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

**Which chart**:
incubator/elasticsearch

**What happened**:
Upon trying to deploy version 2.4.6 of ES, we've found that incubator/elasticsearch/templates/master-svc.yaml contains a line ClusterIP: None, which causes following error:

```kubectl logs pugnacious-jellyfish-elasticsearch-client-5599f5d97f-627fb
[2018-07-30 12:59:58,899][INFO ][node ] [pugnacious-jellyfish-elasticsearch-client-5599f5d97f-627fb] version[2.4.6], pid[1], build[5376dca/2017-07-18T12:17:44Z]
[2018-07-30 12:59:58,901][INFO ][node ] [pugnacious-jellyfish-elasticsearch-client-5599f5d97f-627fb] initializing ...
[2018-07-30 13:00:00,436][INFO ][plugins ] [pugnacious-jellyfish-elasticsearch-client-5599f5d97f-627fb] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
Exception in thread "main" java.lang.IllegalArgumentException: Failed to resolve address for [pugnacious-jellyfish-elasticsearch-discovery.default.svc.cluster.local]
Likely root cause: java.net.UnknownHostException: pugnacious-jellyfish-elasticsearch-discovery.default.svc.cluster.local: Name or service not known
at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
at java.net.InetAddress.getAllByName(InetAddress.java:1192)
at java.net.InetAddress.getAllByName(InetAddress.java:1126)
at org.elasticsearch.transport.netty.NettyTransport.parse(NettyTransport.java:744)
at org.elasticsearch.transport.netty.NettyTransport.addressesFromString(NettyTransport.java:696)
at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:426)
at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.<init>(UnicastZenPing.java:160)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at <<<guice>>>
at org.elasticsearch.node.Node.<init>(Node.java:213)
at org.elasticsearch.node.Node.<init>(Node.java:140)
at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)```

After changing ClusterIP setting to contain IP, all runs fine. This seems to be a cyclic dependency problem, when dicscovery fails to start, and it prevents whole cluster from coming up. 

Can this line in file be templatized please ?

**What you expected to happen**:
Working ES cluster upon installing chart.

**How to reproduce it** (as minimally and precisely as possible):
Try to install incubator/elasticsearch chart with version 2.4.6 of ES, either by modifying values.yaml file or providing helm install parameters

**Anything else we need to know**:
Nope, not yet :)

**Comment by phroggyy** [comment]
However, after changing this and setting `cluster.xpackEnable` in my local environment, I'm hitting a 503 error. Seeing this in the ES client's logs
```
[2018-09-10T16:24:40,657][WARN ][r.suppressed             ] path: /talents, params: {index=talents}
org.elasticsearch.transport.RemoteTransportException: [calling-uakari-elasticsearch-master-0][10.1.5.81:9300][indices:admin/create]
Caused by: org.elasticsearch.discovery.MasterNotDiscoveredException: ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:209) ~[elasticsearch-5.6.0.jar:5.6.0]
```

**Comment by RTodorov** [comment]
Hi there. I'm also facing this issue trying to deploy ES5. Can I help somehow?
