### ISSUE TITLE
[stable/jenkins] MissingPropertyException : Script Security plugin issue

### ISSUE THREAD

**Issue by nalbam** [helm/charts#7541]
**Is this a request for help?**:

I found a problem.
and I found a solution.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT and FEATURE REQUEST

add InstallPlugins `script-security:1.44`

**Version of Helm and Kubernetes**:
```
$ helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

stable/jenkins

**What happened**:
```
groovy.lang.MissingPropertyException: No such property: logRotator for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:130)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:159)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.run(WorkflowScript:4)
```

**What you expected to happen**:

build succeed

**How to reproduce it** (as minimally and precisely as possible):

Remove jenkins
Reinstall stable/jenkins
Build anything

**Anything else we need to know**:

I found a same issue.
https://issues.jenkins-ci.org/projects/JENKINS/issues/JENKINS-53421?filter=allopenissues

https://plugins.jenkins.io/script-security Version 1.45 (Sep 4, 2018)

'Downgrade to 1.44' 

```
Master:
  InstallPlugins:
    - script-security:1.44
```

**Comment by nalbam** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-53420
