### ISSUE TITLE
! ERROR Unable to retrieve the Spinnaker bill of materials for   version "1.9.1": Connection reset

### ISSUE THREAD

**Issue by pennpeng** [helm/charts#7594]
**Version of Helm and Kubernetes**:
Helm: v2.10.0
Kubernetes: v1.11.2

**Which chart**:
stable/spinnaker 1.1.0

**What happened**:
```
+ Get features
  Success
- No changes supplied.
+ hal --daemon-endpoint http://spinnaker-spinnaker-halyard:8064 deploy apply
+ Get current deployment
  Success
- Prep deployment
  Failure
Problems in default.security:
- WARNING Your UI or API domain does not have override base URLs
  set even though your Spinnaker deployment is a Distributed deployment on a
  remote cloud provider. As a result, you will need to open SSH tunnels against
  that deployment to access Spinnaker.
? We recommend that you instead configure an authentication
  mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker
  securely, and then register the intended Domain and IP addresses that your
  publicly facing services will be using.
Problems in Global:
! ERROR Unable to retrieve the Spinnaker bill of materials for
  version "1.9.1": Connection reset


- Failed to prep Spinnaker deployment

```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by pennpeng** [comment]
debug:
```
    "message" : "Validating security with OAuth2Validator",
    "stage" : "Running validation",
    "timestamp" : 1536302076799
  }, {
    "message" : "Validating security with PublicServiceValidator",
    "stage" : "Running validation",
    "timestamp" : 1536302076799
  } ],
  "children" : [ ],
  "uuid" : "38b1bb42-d6a1-470c-b052-535721fe9947",
  "timedOut" : false,
  "version" : "1.9.1-20180830145737",
  "state" : "FAILED",
  "response" : {
    "responseBody" : null,
    "problemSet" : {
      "problems" : [ {
        "message" : "Unable to retrieve the Spinnaker bill of materials for version \"1.9.1\": Read timed out",
        "remediation" : null,
        "options" : null,
        "severity" : "FATAL",
        "location" : "Global"
      }, {
        "message" : "Your UI or API domain does not have override base URLs set even though your Spinnaker deployment is a Distributed deployment on a remote cloud provider. As a result, you will need to open SSH tunnels against that deployment to access Spinnaker.",
        "remediation" : "We recommend that you instead configure an authentication mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker securely, and then register the intended Domain and IP addresses that your publicly facing services will be using.",
        "options" : null,
        "severity" : "WARNING",
        "location" : "default.security"
      } ]
    }
  },
  "fatalError" : {
    "cause" : null,
    "stackTrace" : [ {
      "methodName" : "getBillOfMaterials",
      "fileName" : "VersionsService.java",
      "lineNumber" : 77,
      "className" : "com.netflix.spinnaker.halyard.config.services.v1.VersionsService",
      "nativeMethod" : false
    }, {
      "methodName" : "getBillOfMaterials",
      "fileName" : "ArtifactService.java",
      "lineNumber" : 71,
      "className" : "com.netflix.spinnaker.halyard.deploy.services.v1.ArtifactService",
      "nativeMethod" : false
    }, {
      "methodName" : "getDeploymentDetails",
      "fileName" : "DeployService.java",
      "lineNumber" : 327,
      "className" : "com.netflix.spinnaker.halyard.deploy.services.v1.DeployService",
      "nativeMethod" : false
    }, {
      "methodName" : "prep",
      "fileName" : "DeployService.java",
      "lineNumber" : 207,
      "className" : "com.netflix.spinnaker.halyard.deploy.services.v1.DeployService",
      "nativeMethod" : false
    }, {
      "methodName" : "lambda$prep$18",
      "fileName" : "DeploymentController.java",
      "lineNumber" : 238,
      "className" : "com.netflix.spinnaker.halyard.controllers.v1.DeploymentController",
      "nativeMethod" : false
    }, {
      "methodName" : "build",
      "fileName" : "DaemonResponse.java",
      "lineNumber" : 127,
      "className" : "com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder",
      "nativeMethod" : false
    }, {
      "methodName" : "lambda$submitTask$1",
      "fileName" : "TaskRepository.java",
      "lineNumber" : 48,
      "className" : "com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository",
      "nativeMethod" : false
    }, {
      "methodName" : "run",
      "fileName" : "Thread.java",
      "lineNumber" : 748,
      "className" : "java.lang.Thread",
      "nativeMethod" : false
    } ],
    "problems" : {
      "problems" : [ {
        "message" : "Unable to retrieve the Spinnaker bill of materials for version \"1.9.1\": Read timed out",
        "remediation" : null,
        "options" : null,
        "severity" : "FATAL",
        "location" : "Global"
      }, {
        "message" : "Your UI or API domain does not have override base URLs set even though your Spinnaker deployment is a Distributed deployment on a remote cloud provider. As a result, you will need to open SSH tunnels against that deployment to access Spinnaker.",
        "remediation" : "We recommend that you instead configure an authentication mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker securely, and then register the intended Domain and IP addresses that your publicly facing services will be using.",
        "options" : null,
        "severity" : "WARNING",
        "location" : "default.security"
      } ]
    },
    "responseCode" : 409,
    "message" : "Unable to retrieve the Spinnaker bill of materials for version \"1.9.1\": Read timed out",
    "localizedMessage" : "Unable to retrieve the Spinnaker bill of materials for version \"1.9.1\": Read timed out",
    "suppressed" : [ ]
  },
  "runningJobs" : [ ]
- Prep deployment
  Failure
Problems in default.security:
- WARNING Your UI or API domain does not have override base URLs
  set even though your Spinnaker deployment is a Distributed deployment on a
  remote cloud provider. As a result, you will need to open SSH tunnels against
  that deployment to access Spinnaker.
? We recommend that you instead configure an authentication
  mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker
  securely, and then register the intended Domain and IP addresses that your
  publicly facing services will be using.

Problems in Global:
! ERROR Unable to retrieve the Spinnaker bill of materials for
  version "1.9.1": Read timed out

- Failed to prep Spinnaker deployment
com.netflix.spinnaker.halyard.cli.services.v1.ExpectedDaemonFailureException: Failed to prep Spinnaker deployment
	at com.netflix.spinnaker.halyard.cli.services.v1.OperationHandler.get(OperationHandler.java:45)
	at com.netflix.spinnaker.halyard.cli.command.v1.AbstractRemoteActionCommand.runRemoteAction(AbstractRemoteActionCommand.java:50)
	at com.netflix.spinnaker.halyard.cli.command.v1.deploy.ApplyDeployCommand.getRemoteAction(ApplyDeployCommand.java:107)
	at com.netflix.spinnaker.halyard.cli.command.v1.AbstractRemoteActionCommand.executeThis(AbstractRemoteActionCommand.java:103)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.safeExecuteThis(NestableCommand.java:201)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:149)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:152)
	at com.netflix.spinnaker.halyard.cli.command.v1.NestableCommand.execute(NestableCommand.java:152)
	at com.netflix.spinnaker.halyard.cli.Main.main(Main.java:46)
Caused by: java.lang.Exception: Unable to retrieve the Spinnaker bill of materials for version "1.9.1": Read timed out
	at com.netflix.spinnaker.halyard.config.services.v1.VersionsService.getBillOfMaterials(VersionsService.java:77)
	at com.netflix.spinnaker.halyard.deploy.services.v1.ArtifactService.getBillOfMaterials(ArtifactService.java:71)
	at com.netflix.spinnaker.halyard.deploy.services.v1.DeployService.getDeploymentDetails(DeployService.java:327)
	at com.netflix.spinnaker.halyard.deploy.services.v1.DeployService.prep(DeployService.java:207)
	at com.netflix.spinnaker.halyard.controllers.v1.DeploymentController.lambda$prep$18(DeploymentController.java:238)
	at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:127)
	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48)
	at java.lang.Thread.run(Thread.java:748)
spinnaker@spinnaker-spinnaker-halyard-0:/workdir$ 
```
