### ISSUE TITLE
[stable/spinnaker-1.1.0]helm install always TIME_OUT

### ISSUE THREAD

**Issue by kaybinwong** [helm/charts#7609]
**Is this a request for help?**:
help
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
not sure yet

**Version of Helm and Kubernetes**:
```
[root@a-docker-cluster01 rancher]# helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
[root@a-docker-cluster01 rancher]# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
[stable/spinnaker] version 1.1.0

**What happened**:

values.yaml
```yaml
halyard:
  spinnakerVersion: 1.9.1
  image:
    repository: anjia0532/spinnaker-marketplace.halyard
    tag: 1.9.1
  # Provide a config map with Hal commands that will be run the core config (storage)
  # The config map should contain a script in the config.sh key
  additionalConfig:
    enabled: false
    configMapName: my-halyard-config
    configMapKey: config.sh

# Define which registries and repositories you want available in your
# Spinnaker pipeline definitions
# For more info visit:
#   https://www.spinnaker.io/setup/providers/docker-registry/

# Configure your Docker registries here
dockerRegistries:
- name: dockerhub
  address: index.docker.io
  repositories:
    - library/alpine
    - library/ubuntu
    - library/centos
    - library/nginx
- name: habor
  address: https://registry.xxx.cc
  username: admin
  password: '1*1ya8aHC$'
  email: 1234@5678.com

# If you don't want to put your passwords into a values file
# you can use a pre-created secret instead of putting passwords
# (specify secret name in below `dockerRegistryAccountSecret`)
# per account above with data in the format:
# <name>: <password>

# dockerRegistryAccountSecret: myregistry-secrets

kubeConfig:
  # Use this when you want to register arbitrary clusters with Spinnaker
  # Upload your ~/kube/.config to a secret
  enabled: false
  secretName: my-kubeconfig
  secretKey: config
  # List of contexts from the kubeconfig to make available to Spinnaker
  contexts:
  - default
  deploymentContext: default

# Change this if youd like to expose Spinnaker outside the cluster
ingress:
  enabled: false
  # host: spinnaker.example.org
  # annotations:
    # ingress.kubernetes.io/ssl-redirect: 'true'
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # tls:
  #  - secretName: -tls
  #    hosts:
  #      - domain.com

# spinnakerFeatureFlags is a list of Spinnaker feature flags to enable
# Ref: https://www.spinnaker.io/reference/halyard/commands/#hal-config-features-edit
# spinnakerFeatureFlags:
#   - artifacts
#   - pipeline-templates
spinnakerFeatureFlags:
  - artifacts
  - jobs
  - chaos
  - infrastructure-stages
  - pipeline-templates
  - travis
  - mine-canary

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
# nodeSelector to provide to each of the Spinnaker components
nodeSelector: {}

# Redis password to use for the in-cluster redis service
# Redis is not exposed publically
redis:
  password: password
  nodeSelector: {}
  cluster:
    enabled: false
# Uncomment if you don't want to create a PVC for redis
#  master:
#    persistence:
#      enabled: 
  master:
    persistence:
      enabled: true
      size: 2Gi

# Minio access/secret keys for the in-cluster S3 usage
# Minio is not exposed publically
minio:
  enabled: true
  imageTag: latest # RELEASE.2018-06-09T02-18-09Z
  serviceType: ClusterIP
  accessKey: spinnakeradmin
  secretKey: spinnakeradmin
  bucket: "spinnaker"
  nodeSelector: {}
# Uncomment if you don't want to create a PVC for minio
#  persistence:
#    enabled: false
  persistence:
    enabled: true
    size: 5Gi
  minioConfig:
    storageClass:
      standardStorageClass: "rbd"
      reducedRedundancyStorageClass: "rbd"

gcs:
  enabled: false
  project: my-project-name
  bucket: "<GCS-BUCKET-NAME>"
  jsonKey: '<INSERT CLOUD STORAGE JSON HERE>'

s3:
  enabled: false
  bucket: "<S3-BUCKET-NAME>"
  # rootFolder: "front50"
  # region: "us-east-1"
  # endpoint: ""
  # accessKey: ""
  # secretKey: ""

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccounts to use.
  # If left blank it is auto-generated from the fullname of the release
  halyardName:
  spinnakerName:
```

helm command
```
helm install stable/spinnaker --version 1.1.0 --timeout 600000 --namespace spinnaker
```
the install deployment's logs
```
[root@a-docker-cluster01 rancher]# kubectl -n spinnaker get po
NAME                                        READY     STATUS             RESTARTS   AGE
rafting-orangutan-install-using-hal-c6n2m   0/1       CrashLoopBackOff   2          16m
rafting-orangutan-minio-6b4f547ccc-dmkkq    1/1       Running            0          16m
rafting-orangutan-redis-master-0            1/1       Running            0          16m
rafting-orangutan-spinna-halyard-0          1/1       Running            0          16m
[root@a-docker-cluster01 rancher]# kubectl -n spinnaker logs -f rafting-orangutan-install-using-hal-c6n2m 
+ export DAEMON_ENDPOINT=http://rafting-orangutan-spinna-halyard:8064
+ DAEMON_ENDPOINT=http://rafting-orangutan-spinna-halyard:8064
+ export 'HAL_COMMAND=hal --daemon-endpoint http://rafting-orangutan-spinna-halyard:8064'
+ HAL_COMMAND='hal --daemon-endpoint http://rafting-orangutan-spinna-halyard:8064'
+ hal --daemon-endpoint http://rafting-orangutan-spinna-halyard:8064 --ready
+ bash -xe /opt/halyard/scripts/config.sh
+ hal --daemon-endpoint http://rafting-orangutan-spinna-halyard:8064 config version edit --version 1.9.1
+ Get current deployment
  Success
* Edit Spinnaker version
  Running validation: Validating halconfig with HalconfigValidator
! ERROR null
[root@a-docker-cluster01 rancher]# kubectl -n spinnaker logs -f rafting-orangutan-install-using-hal-c6n2m 
+ export DAEMON_ENDPOINT=http://rafting-orangutan-spinna-halyard:8064
+ DAEMON_ENDPOINT=http://rafting-orangutan-spinna-halyard:8064
+ export 'HAL_COMMAND=hal --daemon-endpoint http://rafting-orangutan-spinna-halyard:8064'
+ HAL_COMMAND='hal --daemon-endpoint http://rafting-orangutan-spinna-halyard:8064'
+ hal --daemon-endpoint http://rafting-orangutan-spinna-halyard:8064 --ready
+ bash -xe /opt/halyard/scripts/config.sh
+ hal --daemon-endpoint http://rafting-orangutan-spinna-halyard:8064 config version edit --version 1.9.1
+ Get current deployment
  Success
* Edit Spinnaker version
  Running validation: Validating halconfig with HalconfigValidator
! ERROR null
```
the halyard statefulset's log
```
2018-09-07 15:13:45.186  INFO 6 --- [      Thread-26] c.n.s.h.c.r.v1.GoogleProfileReader       : Getting object contents of versions.yml
2018-09-07 15:14:44.951  INFO 6 --- [      Thread-25] c.n.s.h.core.tasks.v1.TaskRepository     : Interrupter has no work to do, [Get current deployment] (7e8192b8-d06d-4f14-9036-b20a6283dee3) - SUCCEEDED already completed.
2018-09-07 15:14:45.185  WARN 6 --- [      Thread-27] c.n.s.h.core.tasks.v1.TaskRepository     : Interrupting task [Edit Spinnaker version] (95097a83-e58d-4f79-98a4-6ac459e216d2) - RUNNING that timed out after 60000 millis.
2018-09-07 15:17:45.322  WARN 6 --- [      Thread-26] c.n.s.h.c.v.v1.HalconfigValidator        : Unexpected error comparing versions: com.netflix.spinnaker.halyard.core.error.v1.HalException: Could not load "versions.yml" from config bucket: connect timed out.
2018-09-07 15:17:45.322 ERROR 6 --- [      Thread-26] c.n.s.halyard.core.DaemonResponse        : Unknown exception encountered: 

com.netflix.spinnaker.halyard.core.tasks.v1.DaemonTaskInterrupted: Task interrupted without cause at Fri Sep 07 15:17:45 UTC 2018
	at com.netflix.spinnaker.halyard.core.tasks.v1.DaemonTaskHandler.message(DaemonTaskHandler.java:137) ~[halyard-core-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.config.validate.v1.ValidatorCollection.runMatchingValidators(ValidatorCollection.java:78) ~[halyard-config-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.config.validate.v1.ValidatorCollection.runMatchingValidators(ValidatorCollection.java:87) ~[halyard-config-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.config.validate.v1.ValidatorCollection.runAllValidators(ValidatorCollection.java:53) ~[halyard-config-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.config.services.v1.ValidateService.recursiveValidate(ValidateService.java:55) ~[halyard-config-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.config.services.v1.ValidateService.validateMatchingFilter(ValidateService.java:49) ~[halyard-config-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.config.services.v1.DeploymentService.validateDeploymentShallow(DeploymentService.java:157) ~[halyard-config-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.controllers.v1.DeploymentController.lambda$setVersion$30(DeploymentController.java:341) ~[halyard-web-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.core.DaemonResponse$UpdateRequestBuilder.build(DaemonResponse.java:156) ~[halyard-core-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48) ~[halyard-core-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]

2018-09-07 15:17:45.323  WARN 6 --- [      Thread-26] c.n.s.h.core.tasks.v1.TaskRepository     : Task [Edit Spinnaker version] (95097a83-e58d-4f79-98a4-6ac459e216d2) - RUNNING failed with unexpected reason: 

com.netflix.spinnaker.halyard.core.tasks.v1.DaemonTaskInterrupted: Task interrupted without cause at Fri Sep 07 15:17:45 UTC 2018
	at com.netflix.spinnaker.halyard.core.tasks.v1.DaemonTaskHandler.message(DaemonTaskHandler.java:137) ~[halyard-core-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.config.validate.v1.ValidatorCollection.runMatchingValidators(ValidatorCollection.java:78) ~[halyard-config-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.config.validate.v1.ValidatorCollection.runMatchingValidators(ValidatorCollection.java:87) ~[halyard-config-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.config.validate.v1.ValidatorCollection.runAllValidators(ValidatorCollection.java:53) ~[halyard-config-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.config.services.v1.ValidateService.recursiveValidate(ValidateService.java:55) ~[halyard-config-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.config.services.v1.ValidateService.validateMatchingFilter(ValidateService.java:49) ~[halyard-config-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.config.services.v1.DeploymentService.validateDeploymentShallow(DeploymentService.java:157) ~[halyard-config-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.controllers.v1.DeploymentController.lambda$setVersion$30(DeploymentController.java:341) ~[halyard-web-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.core.DaemonResponse$UpdateRequestBuilder.build(DaemonResponse.java:156) ~[halyard-core-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48) ~[halyard-core-1.9.1-20180830145737.jar:1.9.1-20180830145737]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]

2018-09-07 15:17:45.323  INFO 6 --- [      Thread-26] c.n.s.halyard.core.tasks.v1.DaemonTask   : [Edit Spinnaker version] (95097a83-e58d-4f79-98a4-6ac459e216d2) - TIMED_OUT killing all jobs created by this task 
2018-09-07 15:17:45.323  INFO 6 --- [      Thread-26] c.n.s.h.core.tasks.v1.TaskRepository     : Task [Edit Spinnaker version] (95097a83-e58d-4f79-98a4-6ac459e216d2) - TIMED_OUT completed
```

**What you expected to happen**:
all the pod are running correctly. and access the ui

**How to reproduce it** (as minimally and precisely as possible):
using the values and command above with aliyun ecs.

**Anything else we need to know**:
nothing

**Comment by Erically** [comment]
resolved?

**Comment by rumstead** [comment]
Same issue for me installing the helm chart on a minikube instance. Tried setting the proxies but nothing seems to be working. Any suggestions?

**Comment by Sluggerman** [comment]
Looks like [GoogleProfileReader](https://github.com/spinnaker/halyard/blob/version-1.22.2/halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/GoogleProfileReader.java) does not support proxy settings
