### ISSUE TITLE
Websocket connection: handshake error

### ISSUE THREAD

**Issue by bramvdklinkenberg** [helm/charts#7666]
**Is this a request for help?**:  Yes

**Version of Helm and Kubernetes**:
Helm v2.10.0
Kubernetes v1.11.1

**Which chart**: nginx-ingress

**What happened**: I am trying to get a websocket connection to work but I keep getting a handshake error on the client side.

> 2018-09-11T13:50:41,278 ERROR [Thread-1] ConnectionController.run(72) | Could not connect to server: java.util.concurrent.ExecutionException: javax.websocket.DeploymentException: Handshake error.
Sep 11, 2018 1:50:51 PM org.springframework.web.socket.sockjs.client.DefaultTransportRequest handleFailure
SEVERE: No more fallback transports after TransportRequest[url=ws://aftelapp-test.ns.nl/ws/544/11857f5df09141689d7a90e10c233a0e/websocket]
javax.websocket.DeploymentException: Handshake error.
        at org.glassfish.tyrus.client.ClientManager$3$1.run(ClientManager.java:674)
        at org.glassfish.tyrus.client.ClientManager$3.run(ClientManager.java:712)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.glassfish.tyrus.client.ClientManager$SameThreadExecutorService.execute(ClientManager.java:866)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:511)
        at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:355)
        at org.springframework.web.socket.client.standard.StandardWebSocketClient$1.call(StandardWebSocketClient.java:152)
        at org.springframework.web.socket.client.standard.StandardWebSocketClient$1.call(StandardWebSocketClient.java:149)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.glassfish.tyrus.core.HandshakeException: Response code was not 101: 400.
        at org.glassfish.tyrus.client.TyrusClientEngine.processResponse(TyrusClientEngine.java:320)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleHandshake(GrizzlyClientFilter.java:346)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:315)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
        ... 1 more

**What you expected to happen**: A working connection

**How to reproduce it** (as minimally and precisely as possible): 
- I deployed the nginx ingress chart and (no specific configuration) 
- I created the ingress with the annotation nginx.org/websocket-services

**Anything else we need to know**:
In the controller log I can see a 400 every time the client tries to make a connection to the cluster.

**Comment by bramvdklinkenberg** [comment]
See my svc and ingress yaml files.

[ingress.yaml.txt](https://github.com/helm/charts/files/2373705/ingress.yaml.txt)
[svc.yaml.txt](https://github.com/helm/charts/files/2373706/svc.yaml.txt)

I also tried this solution:
https://github.com/Azure/AKS/issues/408

**Comment by sjsaunde** [comment]
Please expand on what your problem was, seems you opened it and closed it on same day but didn't explain the fix to the issue.
