### ISSUE TITLE
Kafka Helm Chart : ZooKeeperClientTimeoutException

### ISSUE THREAD

**Issue by ashwiniudupa** [helm/charts#7730]
**Is this a request for help?**:YES 

**Version of Helm and Kubernetes**:$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

**Which chart**:Apache Kafka Helm Chart

**What happened**: I am trying to insall Kafka using Kafka Helm chart. I did "helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator" and then "helm install --name my-kafka incubator/kafka". But, my kafka is shutting down continuously and re-starting.
$ kubectl get pods
NAME                             READY     STATUS             RESTARTS   AGE
my-kafka-0                       0/1       CrashLoopBackOff   4          4m
my-kafka-zookeeper-0             1/1       Running            0          4m
my-kafka-zookeeper-1             1/1       Running            0          4m
my-kafka-zookeeper-2             1/1       Running            0          3m

Below are the logs:
[2018-09-14 07:18:18,190] INFO Client environment:user.dir=/ (org.apache.zookeeper.ZooKeeper)
[2018-09-14 07:18:18,191] INFO Initiating client connection, connectString=my-kafka-zookeeper:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@42a48628 (org.apache.zookeeper.ZooKeeper)
[2018-09-14 07:18:27,132] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2018-09-14 07:18:33,138] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
        at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply$mcV$sp(ZooKeeperClient.scala:225)
        at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:221)
        at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:221)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:250)
        at kafka.zookeeper.ZooKeeperClient.kafka$zookeeper$ZooKeeperClient$$waitUntilConnected(ZooKeeperClient.scala:221)
        at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:95)
        at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1538)
        at kafka.server.KafkaServer.kafka$server$KafkaServer$$createZkClient$1(KafkaServer.scala:348)
        at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:372)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
        at io.confluent.support.metrics.SupportedServerStartable.startup(SupportedServerStartable.java:117)
        at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:62)
[2018-09-14 07:18:33,141] INFO shutting down (kafka.server.KafkaServer)
[2018-09-14 07:18:33,142] WARN  (kafka.utils.CoreUtils$)
java.lang.NullPointerException
        at kafka.server.KafkaServer$$anonfun$shutdown$5.apply$mcV$sp(KafkaServer.scala:572)
        at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:85)
        at kafka.server.KafkaServer.shutdown(KafkaServer.scala:572)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:329)
        at io.confluent.support.metrics.SupportedServerStartable.startup(SupportedServerStartable.java:117)
        at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:62)
[2018-09-14 07:18:33,146] INFO shut down completed (kafka.server.KafkaServer)
[2018-09-14 07:18:33,147] INFO shutting down (kafka.server.KafkaServer)

The sessionTimeout is set as 6000 and I am seeing ZooKeeperClientTimeoutException happening before connection all the time.
Should I increase sessionTimeout time? If so, how to do it? Or, is there anything else I need to do?
Please help.

**Comment by cemsbr** [comment]
It seems that confluent collect our data by default (?!) and the collector is crashing the entire application.

```
[2018-09-27 20:27:22,550] WARN Please note that the support metrics collection feature ("Metrics") of Proactive Support is enabled.  With Metrics enabled, this broker is configured to collect and report certain broker and cluster metadata ("Metadata") about your use of the Confluent Platform (including without limitation, your remote internet protocol address) to Confluent, Inc. ("Confluent") or its parent, subsidiaries, affiliates or service providers every 24hours.  This Metadata may be transferred to any country in which Confluent maintains facilities.  For a more in depth discussion of how Confluent processes such information, please read our Privacy Policy located at http://www.confluent.io/privacy. By proceeding with `confluent.support.metrics.enable=true`, you agree to all such collection, transfer, storage and use of Metadata by Confluent.  You can turn the Metrics feature off by setting `confluent.support.metrics.enable=false` in the broker configuration and restarting the broker.  See the Confluent Platform documentation for further information. (io.confluent.support.metrics.SupportedServerStartable)
 [2018-09-27 20:27:36,766] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
	at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply$mcV$sp(ZooKeeperClient.scala:225)
	at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:221)
	at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:221)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:250)
	at kafka.zookeeper.ZooKeeperClient.kafka$zookeeper$ZooKeeperClient$$waitUntilConnected(ZooKeeperClient.scala:221)
	at kafka.zookeeper.ZooKeeperClient.&lt;init&gt;(ZooKeeperClient.scala:95)
	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1538)
	at kafka.server.KafkaServer.kafka$server$KafkaServer$$createZkClient$1(KafkaServer.scala:348)
	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:372)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
	at io.confluent.support.metrics.SupportedServerStartable.startup(SupportedServerStartable.java:117)
	at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:62)
[2018-09-27 20:27:36,768] INFO shutting down (kafka.server.KafkaServer)
[2018-09-27 20:27:36,769] WARN  (kafka.utils.CoreUtils$)
java.lang.NullPointerException
	at kafka.server.KafkaServer$$anonfun$shutdown$5.apply$mcV$sp(KafkaServer.scala:572)
	at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:85)
	at kafka.server.KafkaServer.shutdown(KafkaServer.scala:572)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:329)
	at io.confluent.support.metrics.SupportedServerStartable.startup(SupportedServerStartable.java:117)
	at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:62)
[2018-09-27 20:27:36,772] INFO shut down completed (kafka.server.KafkaServer)
[2018-09-27 20:27:36,773] INFO shutting down (kafka.server.KafkaServer) 
```

Adding the below to the yaml config **didn't** work:
```yaml
confluent:
  support:
    metrics:
      enable: false
```

**Comment by cablespaghetti** [comment]
@cemsbr I'm not particularly impressed by this either and will make a PR when I get some time to move us to a vanilla Kafka container. However this seems to disable their metrics collection:
```
configurationOverrides:
  "confluent.support.metrics.enable": false
```

I now get:
```
[2018-10-16 12:11:44,242] WARN The support metrics collection feature ("Metrics") of Proactive Support is disabled. (io.confluent.support.metrics.SupportedServerStartable)
```

**Comment by mapatel7** [comment]
This is still an issue.
