### ISSUE TITLE
[incubator/fluentd-cloudwatch]  Temporarily failed to flush the buffer. error_class="Net::HTTPFatalError" error="500 \"Internal Server Error\"

### ISSUE THREAD

**Issue by jsullivan5** [helm/charts#9667]
**This is a request for help.**:

---

**BUG REPORT (Maybe)**

**Version of Helm and Kubernetes**:

Kubernetes: v1.10
Helm: v2.11.0

**Which chart**:

incubator/fluentd-cloudwatch

**What happened**:

We have this chart deployed on an EKS cluster in AWS.  We are trying to configure Cloudwatch logs for the cluster.  We have set the `AWSOpsWorksCloudWatchLogs` on each worker node and Cloudwatch log groups.  When spinning up the cluster , we get this stack trace and logs are not streamed:

```
2018-11-30 19:04:21 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-11-30 19:04:22 +0000 error_class="Net::HTTPFatalError" error="500 \"Internal Server Error\"" plugin_id="object:2ac402f6ec94"
  2018-11-30 19:04:21 +0000 [warn]: /usr/lib/ruby/2.5.0/net/http/response.rb:122:in `error!'
  2018-11-30 19:04:21 +0000 [warn]: /usr/lib/ruby/2.5.0/net/http/response.rb:131:in `value'
  2018-11-30 19:04:21 +0000 [warn]: /usr/lib/ruby/2.5.0/net/http.rb:958:in `connect'
  2018-11-30 19:04:21 +0000 [warn]: /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  2018-11-30 19:04:21 +0000 [warn]: /usr/lib/ruby/2.5.0/net/http.rb:915:in `start'
  2018-11-30 19:04:21 +0000 [warn]: /usr/lib/ruby/2.5.0/delegate.rb:83:in `method_missing'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/seahorse/client/net_http/connection_pool.rb:297:in `start_session'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/seahorse/client/net_http/connection_pool.rb:96:in `session_for'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/seahorse/client/net_http/handler.rb:121:in `session'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/seahorse/client/net_http/handler.rb:73:in `transmit'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/seahorse/client/net_http/handler.rb:47:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/seahorse/client/plugins/content_length.rb:12:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/aws-sdk-core/json/error_handler.rb:8:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/aws-sdk-core/plugins/signature_v4.rb:66:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/aws-sdk-core/plugins/retry_errors.rb:171:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/aws-sdk-core/json/handler.rb:11:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/aws-sdk-core/plugins/endpoint_pattern.rb:28:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/aws-sdk-core/plugins/endpoint_discovery.rb:78:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.39.0/lib/seahorse/client/request.rb:70:in `send_request'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/aws-sdk-cloudwatchlogs-1.11.0/lib/aws-sdk-cloudwatchlogs/client.rb:785:in `describe_log_groups'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:403:in `log_group_exists?'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:152:in `block in write'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:144:in `each'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/fluent-plugin-cloudwatch-logs-0.4.5/lib/fluent/plugin/out_cloudwatch_logs.rb:144:in `write'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/fluentd-0.12.43/lib/fluent/buffer.rb:354:in `write_chunk'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/fluentd-0.12.43/lib/fluent/buffer.rb:333:in `pop'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/fluentd-0.12.43/lib/fluent/output.rb:342:in `try_flush'
  2018-11-30 19:04:21 +0000 [warn]: /fluentd/vendor/bundle/ruby/2.5.0/gems/fluentd-0.12.43/lib/fluent/output.rb:149:in `run'
2018-11-30 19:04:22 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-11-30 19:04:23 +0000 error_class="Net::HTTPFatalError" error="500 \"Internal Server Error\"" plugin_id="object:2ac402f6ec94"
  2018-11-30 19:04:22 +0000 [warn]: suppressed same stacktrace
2018-11-30 19:04:23 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-11-30 19:04:27 +0000 error_class="Net::HTTPFatalError" error="500 \"Internal Server Error\"" plugin_id="object:2ac402f6ec94"
  2018-11-30 19:04:23 +0000 [warn]: suppressed same stacktrace
2018-11-30 19:04:28 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-11-30 19:04:35 +0000 error_class="Net::HTTPFatalError" error="500 \"Internal Server Error\"" plugin_id="object:2ac402f6ec94"
  2018-11-30 19:04:28 +0000 [warn]: suppressed same stacktrace
2018-11-30 19:04:35 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-11-30 19:04:51 +0000 error_class="Net::HTTPFatalError" error="500 \"Internal Server Error\"" plugin_id="object:2ac402f6ec94"
  2018-11-30 19:04:35 +0000 [warn]: suppressed same stacktrace
2018-11-30 19:04:51 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-11-30 19:05:20 +0000 error_class="Net::HTTPFatalError" error="500 \"Internal Server Error\"" plugin_id="object:2ac402f6ec94"
  2018-11-30 19:04:51 +0000 [warn]: suppressed same stacktrace
```

**What you expected to happen**:

Expected Cloudwatch logs to stream from cluster.

**How to reproduce it** (as minimally and precisely as possible):

Add Cloudwatch Logging role to worker nodes in eks cluster via instance profile
Add Cloudwatch logging group for cluster
helm install incubator/fluentd-cloudwatch on eks cluster.

**Anything else we need to know**:

Any help is much appreciated!  😄

**Comment by jsullivan5** [comment]
We solved this.  Proxy service was pulling in an unexpected role for our fluentd node.  Cheers. 🍻
