### ISSUE TITLE
Kakfa cannot resolve zookeeper name

### ISSUE THREAD

**Issue by rtacconi** [helm/charts#9701]
```
[main] INFO org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=kafka-zookeeper:2181 sessionTimeout=40000 watcher=io.confluent.admin.utils.ZookeeperConnectionWatcher@1ddc4ec2
[main] ERROR io.confluent.admin.utils.ClusterStatus - Error while waiting for Zookeeper client to connect to the server [kafka-zookeeper:2181].
java.net.UnknownHostException: kafka-zookeeper: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380)
	at io.confluent.admin.utils.ClusterStatus.isZookeeperReady(ClusterStatus.java:83)
	at io.confluent.admin.utils.cli.ZookeeperReadyCommand.main(ZookeeperReadyCommand.java:73)``

I am getting that error. The other kafka pods can resolve the name. It has been working for days but now kafka-1 is failing. The other two are OK.

**Comment by sdankel** [comment]
@rtacconi Were you able to solve this?

**Comment by riccardotacconi** [comment]
It was a while ago, I am not working in that company anymore, I do not exactly remember how I fixed it. It can happen if kafka-zookeeper is not running/defined, or due to a DNS issue.
